### ISSUE TITLE
QUARTERLY rrule ?

### ISSUE THREAD

**Issue by stuaxo** [dateutil/dateutil#1005]
Hi,
   Would it be possible to add QUARTERLY to rrule ?

Cheers
S

**Comment by stuaxo** [comment]
(similar thing for half yearly too)

**Comment by simon-budig** [comment]
This is not necessary, you may specify MONTHLY with an interval of 3 resp. 6. See e.g. https://stackoverflow.com/questions/34568103/ics-calendar-feed-with-quarterly-recurring-events

**Comment by pganssle** [comment]
Yes, in general we try to avoid going beyond the spec laid out in the iCalendar RFCs (byeaster being a notable exception).

You should be able to achieve any fraction of a year using a combination of freq and interval, though.

**Comment by stuaxo** [comment]
Thanks, I didn't know where the rules in rrule came from - (though it's obvious now, looking at the docs).
