### ISSUE TITLE
CI/CD Pipeline Status

### ISSUE THREAD

**Issue by ffe4** [dateutil/dateutil#1019]
I have been wondering if there are still plans to switch to Azure pipelines. The Azure badge says that the project was never built, but there are quite a few issues referencing Azure. In addition, GitHub actions has become an alternative for CI on Windows and OSX.

I was thinking about trying out GitHub Actions and Azure pipelines, and the Travis hiccup on #1017 made me think that now might be as good a time as any. I might as well use this repo for my tests on one of these platforms and maybe see if I can close some related issues at the same time (e.g. #873, #888, #889, #396).

My question would be whether there are already any plans or preferences, or whether there are other issues that might influence decisions on the pipeline.

**Comment by pganssle** [comment]
We had Azure pipelines working for a while, but apparently Microsoft randomly decided that I was a bot or something and refused to allow me access to the account associated with `dateutil` without verifying my identity with a phone number or something, so I dropped Azure pipelines.

I've been using Github Actions for [zoneinfo](https://github.com/pganssle/zoneinfo) and I'm *somewhat* happy with it, but I'm not sure I'd be amazingly happy with it for our entire test matrix on dateutil for the following reasons:

1. It creates an annoying number of status hooks.
2. There is no option to re-run individual jobs - you can re-run *all* jobs or one job.
3. There's no way to re-run jobs that have passed, which means that if a job failed to upload to codecov or something, you have to make an actual *change to the PR* to get it to run again.

I'll note that I've seen problems as bad as the current Travis problems with GHA or AP, so I don't think it would be a cure-all. These CI providers just have random glitches sometimes, and I haven't found one to be amazingly more reliable than another.

I'm not sure if any of these things are major deal-breakers, though. Maybe we can start by moving the PyPy jobs over to GHA?

**Comment by ffe4** [comment]
I would still expect quirks, but the situation right now, with three pipelines defined in the project just did not seem optimal. I think GHA might also be faster than Travis since jobs run in parallel.

If you don't really like the idea of running the entire test matrix on GHA, is there a platform that you think might be better suited for the project? I'd be somewhat hesitant about just adding yet another pipeline to the project. Or would you rather stick with Travis?

**Comment by pganssle** [comment]
> I would still expect quirks, but the situation right now, with three pipelines defined in the project just did not seem optimal. I think GHA might also be faster than Travis since jobs run in parallel.

Travis jobs also run in parallel, it's just a different number of them running in parallel. I would not be terribly surprised if GHA were faster, though, that's true.

> If you don't really like the idea of running the entire test matrix on GHA, is there a platform that you think might be better suited for the project? I'd be somewhat hesitant about just adding yet another pipeline to the project. Or would you rather stick with Travis?

Right now, Travis and Appveyor cover different parts of the matrix -- Travis does Linux and Appveyor does Windows. I think if we set up GHA we can move the PyPy jobs off of Travis, and GHA can cover PyPy (all platforms). If Travis remains flaky or if GHA dramatically improves, we can migrate everything to GHA, but I don't see a huge benefit in consolidating to one CI provider, particularly since they each run in parallel from one another.

I do think that Appveyor only runs one job at a time, but that *might* be a problem with the account configuration.

**Comment by ffe4** [comment]
If we want to change or improve the pipeline (e.g. pinned tox version), only having to deal with one CI provider and config is definitely a benefit. We'd also be able to remove the tox environments that are supposed to be run only on the CI. But since I am hopeful that #873, #888 and #889 will be closed soon, the next changes might be CD related anyway, so I agree that there's not a lot of benefit right now.

As for (semi-)CD, is that still a concern? #396 and #596 are quite old, so I'm not sure how much has changes since then. I'm somewhat interested in doing some CD, but I've never released anything on PyPI. Since releases seem to have slowed down, I'm not sure whether that's still high on the list.

**Comment by pganssle** [comment]
> If we want to change or improve the pipeline (e.g. pinned tox version), only having to deal with one CI provider and config is definitely a benefit.

I would rather just centralize our CI scripts to be mostly provider-independent than centralize on a CI provider. That's one of the reasons we have `tox` environments that are run only on CI - they are very portable.

> As for (semi-)CD, is that still a concern? #396 and #596 are quite old, so I'm not sure how much has changes since then.

Yeah, the main blocker here has been that I've been stubbornly sticking to the idea that I should sign all releases with my GPG key, and there's no way to do that with CD.

I think we can probably give up on the GPG key signing thing. Another option would be to check the public keys of anyone authorized to do releases into the repository and have the CI triggered by signed *tags*, but I don't know that that's worth it.

**Comment by ffe4** [comment]
It seems the problem Travis was having with reporting its status is now persistent and has somehow spread to Appveyor. Travis webhooks seem to work fine on [my fork](https://github.com/ffe4/dateutil/pull/4), so I'm not sure if it is maybe set up in a deprecated configuration or something for this repo.

Regarding CD, will pulling the latest zonefile (#396 checklist) still be necessary after the PEP? Otherwise it seems that most steps on the checklist, except for the changelog and GitHub operations is mostly automated already. GHA also has some free storage which I think we could use to store a build artifact if you want to sign it manually.

**Comment by mariocj89** [comment]
I think this is good to close after the latest changes in the CI, isn't it?
