### ISSUE TITLE
Why does the source code license say "all rights reserved" when you don't reserve all rights?

### ISSUE THREAD

**Issue by jeremiah** [dateutil/dateutil#1035]
In the license file it reads;
```
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
```
At first, all rights are reserved, then you grant usage rights, modification rights, and distribution rights. This is confusing. In addition, "All rights reserved" has no legal meaning and is a deprecated term which likely should be removed to reduce licensing ambiguity.

**Comment by pganssle** [comment]
@jeremiah That is part of the text of the [BSD 3-clause license](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)). I didn't write it and we don't have any option to change it. If were up to me we'd have relicensed the whole project under Apache 2.0 only, but we have contributors who have not agreed to relicense.

**Comment by jeremiah** [comment]
Okay understood.
