### ISSUE TITLE
setup.py requires setuptools.command.test which may be not available

### ISSUE THREAD

**Issue by eldruin** [dateutil/dateutil#1043]
On macOS the `test` package may not always be available (at least it happens in our case).
This is only used to give a hint about not running `python setup.py test`, which is not supported.
It should be possible to use the `setuptools.Command` class instead, which should always be available.
I'll submit a PR about this in a moment.

**Comment by pganssle** [comment]
I'm not opposed to the idea, but in what situation would `setuptools.command.test` not be available?

**Comment by eldruin** [comment]
We have an older setuptools version (40.8.0, Feb 2019) where the `test` package was not yet available. It turns out macOS was the only platform doing real dogfooding with python on our side so I first noticed it there.

**Comment by pganssle** [comment]
Hm, we don't really support *any* direct invocation of `setup.py`, so it shouldn't matter what version of `setuptools` you have installed. Failing with an error about `setuptools.command.test` not existing doesn't seem like a huge problem *but* I suppose it's better to have a nice error message than not.

**Comment by eldruin** [comment]
Importing `setuptools.command.test` in `setup.py` is a problem for us during our build, where we install `dateutil` via `pip`. When `pip` calls `setup.py` it fails due to the import error.

**Comment by pganssle** [comment]
> Importing `setuptools.command.test` in `setup.py` is a problem for us during our build, where we install `dateutil` via `pip`. When `pip` calls `setup.py` it fails due to the import error.

If you are using the standard `pip install` you should get a wheel, no? In that case, you wouldn't execute `setup.py` at all.

Regardless of why you are installing from source, the bigger issue is that you are apparently using an old version of `pip`. You should update `pip` first before installing `python-dateutil`. `dateutil` really only supports installation via PEP 517/518 (i.e. `pip >= 19.0` or using one of the distributed wheels or one built with a PEP 517 front-end). If you are using PEP 517/518, the build will occur in an isolated development environment with a recent version of `setuptools`.

**Comment by eldruin** [comment]
I see. Yes we are building from source using `pip` 9.0.3 on python 3.6.4. I tried updating `pip` in the past but that is the highest compatible version for that python version IIRC.
I will close this then and see when I can find some time for a whole python update on our side.
Thanks!
