### ISSUE TITLE
Parsing fails with type error when given weird input

### ISSUE THREAD

**Issue by QuentinNativel** [dateutil/dateutil#1054]
**Description**
When given an input that is not a date, the parser returns a TypeError: unsupported operand type(s) for +: 'int' and 'str'.

**Versions**
**Python 3.7.7**
**dateutil 2.8.1**
 
**Code**

`from dateutil import parser

parser.parse('8400 Erlose 19% USt', fuzzy=True)`

**Expected behavior**
The parser should raise a ValueError

Stacktrace:
![image](https://user-images.githubusercontent.com/26868810/84884152-a4367400-b091-11ea-8e1e-e26d579ba80b.png)

**Comment by ffe4** [comment]
Thank you for the report, but this issue has been raised in #981 fixed on master via #987.
