### ISSUE TITLE
Parser fails to parse YYYY:MM:DD

### ISSUE THREAD

**Issue by mbrijun** [dateutil/dateutil#1062]
Hi, for some reason the parser cannot handle colon (":") symbol and returns the current time. When the colon is replaced with a hyphen ("-"), the parser works correctly.

```
>>> from dateutil.parser import parse
>>> parse('2011:01:08 23:44:36')

datetime.datetime(2020, 6, 27, 23, 44, 36)

>>> parse('2011-01-08 23:44:36')

datetime.datetime(2011, 1, 8, 23, 44, 36)
```

**Comment by ffe4** [comment]
What happens here is that the parser assumes a colon to always indicate a `HH:MM` time format. It first parses the first half to a time with an hour of 2011, which would usually raise an error as in #1061, but the time gets overwritten when the parser encounters the the next (this time valid) `HH:MM` format before the sanity check.

This is probably not trivial to fix but implementing a sanity check before setting the hour might solve more than just this issue. Your date format seems very unusual, however. Where did you encounter it?

**Comment by mbrijun** [comment]
I am creating a database of EXIF timestamps. The example I gave was from a photo taken with a Nikon D50 DSLR. I use [wand module](http://docs.wand-py.org/en/0.6.1/) which in turn uses [ImageMagick](https://imagemagick.org/). I am not sure whether this is an EXIF-specific format, or a Nikon specific one. I suspect the former, as I can see the same by looking at photos taken with a Samsung smartphone. Several EXIF tools (I have tried ImageMagick, Exiftool and digiKam) all seem to be returning colon separated dates.

**Comment by ffe4** [comment]
Yes, this does indeed seem to be the EXIF standard and I just noticed that we already have an open issue for this #271 . As mentioned in that issue, while this format should be in the scope of the dateutil parser and hopefully implemented at some point, it would make sense to use `datetime.strptime` in this case.

I will close this issue as a duplicate.
