### ISSUE TITLE
开始日期是30号或者31号时，计算月份差有问题

### ISSUE THREAD

**Issue by wl9724** [dateutil/dateutil#1065]
from dateutil import rrule
import datetime
months = rrule.rrule(freq=rrule.MONTHLY, dtstart=datetime.datetime.strptime('2020-01-31', '%Y-%m-%d'),
                                     until=(datetime.datetime.strptime('2020-12-31', '%Y-%m-%d') + datetime.timedelta(days=1))).count() - 1
print(months)

**Comment by mariocj89** [comment]
Sorry this issue does not contain steps to identify what is the issue you are reporting. 

Please open a new issue and indicate what is the actual and expected output.
