### ISSUE TITLE
Yearly events are interpreted as monthly events when BYMONTHDAY is used

### ISSUE THREAD

**Issue by alexgit2k** [dateutil/dateutil#1072]
If not only "FREQ=YEARLY" is set for yearly events, but also the parameter "BYMONTHDAY=..." - like the Windows 10 calendar app is doing - then `rrulestr` interprets them wrongly as monthly events.

Correct with `FREQ=YEARLY`only, one event per year:
```
>>> from dateutil.rrule import rrulestr
>>> list(rrulestr("""DTSTART;VALUE=DATE:20200716\nRRULE:FREQ=YEARLY;COUNT=3\n"""))
[datetime.datetime(2020, 7, 16, 0, 0), datetime.datetime(2021, 7, 16, 0, 0), datetime.datetime(2022, 7, 16, 0, 0)]
```

Correct with `FREQ=YEARLY;WKST=MO;INTERVAL=1`, one event per year:
```
>>> from dateutil.rrule import rrulestr
>>> list(rrulestr("""DTSTART;VALUE=DATE:20200716\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;COUNT=3\n"""))
[datetime.datetime(2020, 7, 16, 0, 0), datetime.datetime(2021, 7, 16, 0, 0), datetime.datetime(2022, 7, 16, 0, 0)]
```

Wrong with `FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTHDAY=16`, one event per month:
```
>>> from dateutil.rrule import rrulestr
>>> list(rrulestr("""DTSTART;VALUE=DATE:20200716\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTHDAY=16;COUNT=3\n"""))
[datetime.datetime(2020, 7, 16, 0, 0), datetime.datetime(2020, 8, 16, 0, 0), datetime.datetime(2020, 9, 16, 0, 0)]
```

**Comment by pganssle** [comment]
I believe this is just how RRULE works. The BY rules act as a filter when they are for an interval larger than the rule's frequency, and a multiplier when they are smaller than the frequency. With BYMONTHDAY specified in a YEARLY rule you would expect recurrences for every month that contains that day of month.

One section of [this tutorial](https://ganssle.io/talks/#dealing-with-datetimes-tutorial) goes into detail about how RRULEs work.

What are you trying to generate? What do you expect this to do?

**Comment by pganssle** [comment]
I think if you want "annually, on a given month and day" (like a birthday), you need both BYMONTH and BYMONTHDAY.

**Comment by alexgit2k** [comment]
@pganssle Yeah, I want to create a yearly Birthday-Event in the default calendar app of Windows 10.

Thanks, you are right. https://tools.ietf.org/html/rfc5545 says that "BYxxx rule parts for a period of time less than the frequency generally increase or expand the number of occurrences of the recurrence." As `BYMONTH` is less than `YEARLY` dateutil correctly expands it.

The calendar app of windows 10 does only add `BYMONTHDAY` for yearly events, but not `BYMONTH`, so its an error in the calendar app.  I am reporting it at Microsoft and closing this issue here.
