### ISSUE TITLE
parser.parse doesn't handle tzinfo passed in as tzinfos object

### ISSUE THREAD

**Issue by Kylotan** [dateutil/dateutil#110]
This code here in parser.parse appears to be wrong:

        if not ignoretz:
            if (isinstance(tzinfos, collections.Callable) or
                    tzinfos and res.tzname in tzinfos):

If tzinfos is just a datetime.tzinfo object, this will raise an error like this:
`TypeError: argument of type 'Europe/London' is not iterable`
This is because the 'in' operator doesn't work on tzinfo objects. But the type check here doesn't prevent that.

**Comment by pganssle** [comment]
Tzinfos should actually be a map or function mapping strings to time zone objects, e.g. `{"UTC": tz.UTC}`.

**Comment by pganssle** [comment]
See also #80. The documentation should more accurately reflect the situation on the ground now that #103 has been merged.

**Comment by Kylotan** [comment]
Any chance this will get pushed to PyPi then? The docstring in the current version on PyPi still says "This can be either a subclass of `tzinfo`, a time zone string or an integer offset."

**Comment by pganssle** [comment]
Yes, it's in master, so it will be in the next release, which I'm hoping we'll be able to finish up soon.
