### ISSUE TITLE
date converting error

### ISSUE THREAD

**Issue by Zee98** [dateutil/dateutil#1103]
in my project, have the date format 02/03/2021 and 16/02/2021 (dd/mm/yy). I have installed dateutil 2.8.1. I used parser.parse which converted the first date format to 2021-02-03 (yy-mm-dd) which is should output something like this(2021-02-03). the second example is ok as the day is larger then the month. So, Please try this too and see the result. maybe its my system only!

**Comment by ffe4** [comment]
This is a known issue (#1011), if I understand you correctly. There is no way for `dateutil` to know which order months and dates are specified in. By default it chooses the mm/dd format.

There is a `dayfirst` option that makes the parser interpret ambiguous strings as dd/mm:

```python
>>> from dateutil.parser import parse
>>> parse("02/03/2021")
datetime.datetime(2021, 2, 3, 0, 0)
>>> parse("02/03/2021", dayfirst=True)
datetime.datetime(2021, 3, 2, 0, 0)
```

I will close this issue for now, but feel free to ask if you have further questions.
