### ISSUE TITLE
Default date inconsistency with strptime

### ISSUE THREAD

**Issue by Dr-Irv** [dateutil/dateutil#1112]
If you don't specify a date when parsing, the default date with `dateutil.parser` is today's date.  But with the standard library `strptime`, it is January 1, 1900.  Shouldn't this be consistent?
```python
>>> from datetime import datetime as dt
>>> from dateutil import parser
>>> dt.strptime('02:12:11', '%H:%M:%S')
datetime.datetime(1900, 1, 1, 2, 12, 11)
>>> parser.parse('02:12:11')
datetime.datetime(2021, 3, 18, 2, 12, 11)
```

**Comment by mariocj89** [comment]
Indeed, it's inconsistent and as raised in other issues it is an unfortunate decision that was taken back in the day to make "today" the default. This will be impossible to fix without potentially breaking too many people.

You can use the default argument to change that:

```
>>> parser.parse('02:12:11', default=dt(1900,1,1))
datetime.datetime(1900, 1, 1, 2, 12, 11)
```
