### ISSUE TITLE
tz and py34 tests are failing 

### ISSUE THREAD

**Issue by gururajrkatti** [dateutil/dateutil#1116]
two jobs from CI are failing.

pyt34 is failing with the below error

SyntaxError: invalid syntax
ERROR: FAIL could not package project - v = InvocationError('/home/travis/virtualenv/python3.4.8/bin/python /home/travis/build/dateutil/dateutil/setup.py sdist --formats=zip --dist-dir /home/travis/build/dateutil/dateutil/.tox/dist (see /home/travis/build/dateutil/dateutil/.tox/log/tox-0.log)', 1)

tz is failing with the below error

KeyError: "filename 'pacificnew' not found"
Cleaning up.
ERROR: InvocationError for command '/home/travis/build/dateutil/dateutil/ci_tools/run_tz_master_env.sh /home/travis/build/dateutil/dateutil/.tox/tz/tmp /home/travis/build/dateutil/dateutil' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   tz: commands failed

Pl. refer https://travis-ci.org/github/dateutil/dateutil/builds/766399120

**Comment by mariocj89** [comment]
CI is now passing. Thanks for reporting.
