### ISSUE TITLE
CI needs migration to GHA

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#1121]
Anyone following this issue tracker has probably noticed that it's been languishing quite a bit lately. This is due to a number of factors and I don't foresee being able to devote a _huge_ amount of time to this project for at least a few months, unfortunately.

The biggest problem right now is that even small and trivial PRs that I could merge easily are being blocked because of problems with the CI, and I never have enough uninterrupted FOSS time to put together an update to the CI pipeline for `dateutil`.

If anyone wants to get the work started to hopefully reduce the "activation" energy required to restart PRs on `dateutil`, I think what I'd like to do is migrate the rest of the CI over to using Github Actions and away from using Travis. the [zoneinfo backport](https://github.com/pganssle/zoneinfo) and [tzdata repo](https://github.com/python/tzdata) both are good examples for how I like to set up CI on a project these days.

I think the trickiest part of setting up / fixing the CI will be getting the older Pythons (e.g. 3.3, 3.4 and 3.5) tested. It might be easiest to use a docker container for those, or possibly something using the `deadsnakes` PPA on Ubunut / Debian. It's probably best to freeze / lock _everything_ on EOL distributions, since they are subject to the greatest bitrot of everything in the CI pipeline.

Yes, I would like to drop support for `<=3.6` but I'd like at least one version of `python-dateutil` that supports 2.7 and also fixes #701 and #590. Once those are done, I will be much more comfortable dropping "support" for EOL versions (since the code itself will mostly just work even with newer versions of the tz data).

I don't think anyone is really using 3.3 and 3.4 or whatever, but other than the difficulty in actually running _tests_ for them, there's nothing special we need to do to support them as long as we are supporting 2.7.

**Comment by mariocj89** [comment]
Closing as Appveyor and Travis are being used to run EOL Python interpreters. Once we cut a new release, we can drop support for those and remove Travis and Appveyor altogether.
