### ISSUE TITLE
rrule MONTHLY when dstart date is 31 increment month by 2+ months

### ISSUE THREAD

**Issue by marselbeqiri** [dateutil/dateutil#1136]
Hi, 
I was using rrule class to create a list of **MONTHLY** dates and found out that rrule when the date is 31 it skip one month, like below:
```
start_date = '2020-05-31T06:07:00Z #I have converted this in date
end_date = datetime.now()

```

```
list(rrule(MONTHLY, dtstart=start_date, until=end_date))
```

Output
> [datetime.datetime(2020, 5, 31, 6, 7), datetime.datetime(2020, 7, 31, 6, 7), datetime.datetime(2020, 8, 31, 6, 7), datetime.datetime(2020, 10, 31, 6, 7), datetime.datetime(2020, 12, 31, 6, 7), datetime.datetime(2021, 1, 31, 6, 7), datetime.datetime(2021, 3, 31, 6, 7), datetime.datetime(2021, 5, 31, 6, 7)]

**Comment by mariocj89** [comment]
That is indeed expected behaviour, see https://dateutil.readthedocs.io/en/stable/rrule.html#dateutil.rrule.rrule.

Per [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545):


> Recurrence rules may generate recurrence instances with an invalid
      date (e.g., February 30) or nonexistent local time (e.g., 1:30 AM
      on a day where the local time is moved forward by an hour at 1:00
      AM).  Such recurrence instances MUST be ignored and MUST NOT be
      counted as part of the recurrence set.

**Comment by marselbeqiri** [comment]
i fixed it by using bymonthday: 
``` 
rrule(MONTHLY, dtstart=start_date, until=end_date,  bymonthday=-1)
```

**Comment by mariocj89** [comment]
Indeed, that will generate the last day of the month for every occurrence, adapting to the number of days each month has.

**Comment by marselbeqiri** [comment]
I can check if it is the last day of month for dstart, using calendar module.

```
import calendar 

last_day_of_month = calendar.monthrange(2021,5)
```

An if condition and it will work!
