### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by finete** [dateutil/dateutil#1139]
There hasn't been a new release to pypi since Nov 3, 2019.
Is the project not maintained?

Any news on when can expect an new release?

**Comment by mariocj89** [comment]
We are indeed working on getting a new release cut really soon. We just updated the tzdata and are planning some changes to offer the last release with Python 2 support. We are meeting this Friday to discuss details, I'll update this issue on the weekend.

**Comment by jadchaar** [comment]
Great to hear :)! Over at https://github.com/arrow-py/arrow we are anxiously awaiting a new release :D!

**Comment by mariocj89** [comment]
Apologies, We actually have the catchup next Friday, I think we should be good to cut a release ASAP (within next week) though. We can cut 2.8.2 including the update to the tzdata.

**Comment by mariocj89** [comment]
As soon as we automate releases we will cut 2.8.2: https://github.com/dateutil/dateutil/pull/1141

**Comment by mariocj89** [comment]
We just released 2.8.2 to test.pypi.org. I'll upload to pypi.org tomorrow morning.

**Comment by mariocj89** [comment]
3.8.2 was just released: https://pypi.org/project/python-dateutil/2.8.2/
