### ISSUE TITLE
Parser unable to parse 2 mode: day and year

### ISSUE THREAD

**Issue by GraphGrail** [dateutil/dateutil#114]
http://stackoverflow.com/questions/32192226/trouble-in-parsing-date-using-dateutil-day-and-year/32192501?noredirect=1#comment52270661_32192501

Unable to parse: '19        2015'
It identify that 19 is month.
repl 	{'month': 19, 'year': 2015}

When i add 08 - >  '19        2015 08' it think it's 2008 year, but i need August
repl 	{'day': 19, 'month': 2015, 'year': 2008}

default not working in these cases

**Comment by pganssle** [comment]
@GraphGrail I can look into whether this is easy to do, but where are you getting these dates that just have a day and a year? In what situation do you not need to specify the month, but you *do* need to specify the year? I've never seen a date formatted like that before.

**Comment by pganssle** [comment]
I'm going to close this as wontfix. If @GraphGrail comes up with some compelling reason to incorporate this into the library, I'll re-open. @jarondl Feel free to re-open if you think this should be within scope.

**Comment by GraphGrail** [comment]
Ok: when i try to parse dates from various sources (and languages) in internet they come with wrong coding, for example: 19 xd480 &x490 2015 - wrong characters is the abbreviation of month in bad encoding.
Now i use my own function to remove these characters - i do that because dateutil will recognize "xd480" as 480, so this will wrong once more.
I understand that this may be not dateutil problem but scrapping or encoding - but there should be more common way to deal with.
