### ISSUE TITLE
day is out of range for month: February 29,2016 - Leap year issue

### ISSUE THREAD

**Issue by parmkaur** [dateutil/dateutil#1155]
Code:
`from dateutil.parser import parse
dates = parse('February 29,2016').strftime("%Y-%m-%d")
print(dates)
`

Error:

day is out of range for month: February 29,2016 

It seems like leap year is not considered here. Can anyone help me detect 29 February 2016 in the format of 2016-02-29

library versions: python-dateutil - 2.8.2

**Comment by mariocj89** [comment]
Thanks @parmkaur this seems to be an issue indeed, I've opened #1156 with some additional details from an initial investigation.
