### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil' with python-dateutil==2.8.2

### ISSUE THREAD

**Issue by Ameausoone** [dateutil/dateutil#1162]
I had an issue with the latest version of python-dateutil. 

No matter what I did, I always had this error `ModuleNotFoundError: No module named 'dateutil'`. 

```
pip3 --version
pip 21.1.3
python3 --version
Python 3.8.9
uname -a                       
Darwin FRL-C02DT1AJML7L 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
macOs BigSur v11.4
```

I tried to install it alone, with requirements.txt (`python-dateutil==2.8.2`),  before or after requirements.txt, I always had this issue. 

I saw that this issue #1146 was merged in version 2.8.2, so I try with version 2.8.1, and it worked directly. 

I think there is an issue with the directories.

**Comment by Pretzel-Solution** [comment]
I could reproduce the **same error** and its solution with version 2.8.1 under **Windows**

**Comment by mariocj89** [comment]
Thanks for reporting this but it looks like an issue installing it. Can you please provide full steps on how you install and test it?

**Comment by Ameausoone** [comment]
Sure :
```
python3 -m venv .venv 
source .venv/bin/activate
pip install pip==21.1.3
pip install -r requirements.txt
pip install python-dateutil==2.8.2
```

requirements.txt
```
Jinja2==3.0.1
MarkupSafe==2.0.1
dataclasses==0.6
google-api-python-client==2.0.2
google-auth==1.27.1
google-cloud-secret-manager==2.2.0
# I removed python-dateutil==2.8.2 just for testing
```

... 
OK, I didn't get it, I tried this ten times one week ago, and today it works... Sorry

**Comment by Ameausoone** [comment]
Thks for your response
