### ISSUE TITLE
last day of the month is wrong??

### ISSUE THREAD

**Issue by hawkEye-01** [dateutil/dateutil#1167]
From documentation, it seems to correctly get last day of the month..
**How does it handle months with different numbers of days? Notice that adding one month will never cross the month boundary.**

```
>>> date(2003,1,27)+relativedelta(months=+1)
datetime.date(2003, 2, 27)
>>> date(2003,1,31)+relativedelta(months=+1)
datetime.date(2003, 2, 28)
>>> date(2003,1,31)+relativedelta(months=+2)
datetime.date(2003, 3, 31)
```
I tried, 
```
from datetime import date
print(date(2021, 6, 30) + relativedelta(months=-1))
```
which gives 2021-05-30. i should have been 2021-05-31.

**Comment by Mifrill** [comment]
Good catch! It's interesting, seems like `plus` working fine, the point in `minus`:
```python
>>> date(2021, 5, 31) + relativedelta(months=+1)
datetime.date(2021, 6, 30)
>>> date(2021, 6, 30) + relativedelta(months=-1)
datetime.date(2021, 5, 30)
```
also:
```python
>>> date(2021, 6, 30) - relativedelta(months=1)
datetime.date(2021, 5, 30
```

**Comment by Mifrill** [comment]
hm... probably not only for minus, because of this:
```python
>>> date(2021, 4, 30) + relativedelta(months=1)
datetime.date(2021, 5, 30)
```
should be `datetime.date(2021, 5, 31)` I guess
