### ISSUE TITLE
Support date math like ElasticSearch?

### ISSUE THREAD

**Issue by lambdaq** [dateutil/dateutil#1177]
ES had this awesome [date math](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math) support. For example

Assuming `now` is 2001-01-01 12:00:00
- `now+1h` now in milliseconds plus one hour. Resolves to: 2001-01-01 13:00:00
- `now-1h/d` now in milliseconds minus one hour, rounded down to UTC 00:00. Resolves to: 2001-01-01 00:00:00

It would be awesome if `dateutil` can implement something similar, like `dateutil.parser.math("now-1h/d")` It would be way easier than manipulating `datetime` object.

**Comment by mariocj89** [comment]
Thanks a lot for the proposal @lambdaq, I think this is a nice feature but probably not for dateutil itself. I'd really encourage you to create a parser for that kind of syntax, which can use dateutil relativedelta underneath it.
