### ISSUE TITLE
French locale MONTH abbreviation

### ISSUE THREAD

**Issue by RGosselin3197** [dateutil/dateutil#1193]
In french, July (juillet) abbreviation is : juill. (with 2 l)
In dateutil the abbreviation is juil. (only 1 l ) 

Please make correction

**Comment by dschenck** [comment]
Do you have an example where you use `juil` ?

**Comment by RGosselin3197** [comment]
Bonjour,
You can take a look at these : 
http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3619
https://reflex.sne.fr/abreviations-mois
https://fr.wikipedia.org/wiki/Mois

juil. is commonly accepted but it's not the legal abbreviation.
Personally, I had this issue with data from Hydro-Québec.
I resolved it by adding it to fr_CAParserInfo.

Thanks
Robert

**Comment by dschenck** [comment]
Bonjour :) 

I agree the French abbreviation for July is 'juill'.

However, my question is, do you have an example of dateutil natively parsing 'juil' and not 'juill'? I dont think dateutil natively handles French (or non-English) inputs?

**Comment by RGosselin3197** [comment]
Hi !
Your right !
In fact, I first modified parserinfo using info from locale. 
But the locale does not contain juill. 
After  inserting it in parserinfo, dateutil worked correctly, 

That is not the case for other date functions who are using the locale.
So, the problem is not with dateutil but with the locale module.

Sorry it's my error.
