### ISSUE TITLE
remove python2

### ISSUE THREAD

**Issue by xiaoge1001** [dateutil/dateutil#1202]
The python2 life cycle has ended and we can drop supporting python2.

**Comment by jvoisin** [comment]
In 2008, it [was announced]( https://www.python.org/doc/sunset-python-2/ ) that python2 would be deprecated in 2015, a deadline that was then moved to 2020.

> As of January 1st, 2020 no new bug reports, fixes, or changes will be made to Python 2, and Python 2 is no longer supported.

We are 3 years later, nobody should be running python2 in production anymore.

**Comment by jvoisin** [comment]
I don't see anything about removing python2/six support in the [changelog](https://github.com/dateutil/dateutil/commit/edd3fd4565616f7c92567c1daa957ee52df221a40), did I miss something?

**Comment by sevdog** [comment]
In `setupo.py` python 2.7 is still present, also `six` module is still in use:

https://github.com/dateutil/dateutil/blob/1ae807774053c071acc9e7d3d27778fba0a7773e/setup.cfg#L42C1-L45

Why was this issue closed?
