### ISSUE TITLE
Going from winter- to summertime by adding a timedelta

### ISSUE THREAD

**Issue by frip** [dateutil/dateutil#1204]
Something seems to be wrong here:
```python
>>> from dateutil import tz
>>> str(datetime(2022, 3, 27, 1, 45, tzinfo=tz.gettz("Europe/Vienna")))
'2022-03-27 01:45:00+01:00'
>>> str(datetime(2022, 3, 27, 1, 45, tzinfo=tz.gettz("Europe/Vienna")) + timedelta(minutes=20))
'2022-03-27 02:05:00+02:00'
```
The problem becomes clearer if we convert the results to UTC:
```python
>>> str(datetime(2022, 3, 27, 1, 45, tzinfo=tz.gettz("Europe/Vienna")).astimezone(tz.UTC))
'2022-03-27 00:45:00+00:00'
>>> str((datetime(2022, 3, 27, 1, 45, tzinfo=tz.gettz("Europe/Vienna")) + timedelta(minutes=20)).astimezone(tz.UTC))
'2022-03-27 00:05:00+00:00'
```
In other words: By adding 20 minutes we go 40 minutes into the past.

I don't know if this is a problem of the timezone returned by `tz.gettz("Europe/Vienna")`, or the +-operator of `timedelta`, or my expectations when using timezones, but it is confusing, to say the least.

**Comment by pganssle** [comment]
These are the expected [semantics of datetime arithmetic in Python](https://blog.ganssle.io/articles/2018/02/aware-datetime-arithmetic.html). Yes, it is counter-intuitive to almost everyone and ideally we would design `datetime` along different abstraction boundaries to avoid this ambiguity if we could start from scratch.

**Comment by jbrockmendel** [comment]
This surprised me enough to go look up the implementation https://github.com/python/cpython/blob/main/Modules/_datetimemodule.c#L5598.  FWIW pd.Timestamp addition works the way the OP would expect, effectively converting to UTC, adding, then converting back from UTC.

I don't expect the stdlib to ever change this, but if they did, I'd suggest a separate timedelta-like object that preserves time of day across DST transitions.  Would only be integer number of days without sub-day components.
