### ISSUE TITLE
How is "1" a valid datetime string? Can we turn off this 'intelligence'?

### ISSUE THREAD

**Issue by RamiAwar** [dateutil/dateutil#1223]
This library is doing too much. By trying to be very intelligent, it becomes simply unusable in production. Hundreds of stackoverflow comments validate my opinion.

Can we conditionally turn on this inference? Or keep it on by default for backwards compatibility, but please add a toggle to turn it off! It's a shame this library can't be used for datetime validation, it already does all that is required. But doing a lot more than is required is the problem.

**Comment by weatherfrog** [comment]
+1, this is really bad.

**Comment by pganssle** [comment]
The assumption that the parser makes is that you have passed it a valid datetime string. It's fundamentally built into the algorithm and not something that can be turned off, unfortunately. 😕

**Comment by RamiAwar** [comment]
I'm using other parsing libraries like https://pendulum.eustace.io/ that don't have this downside for anyone that's interested  @weatherfrog 

Their standard parser supports common formats and actually makes sense https://pendulum.eustace.io/docs/#parsing

And they support less strict parsing if specified.
