### ISSUE TITLE
time period (week) interpreted as non-sensical time zone.

### ISSUE THREAD

**Issue by joooeey** [dateutil/dateutil#1229]
In Pandas I can create a period like
```
>>> import pandas as pd
>>> period = str(pd.Period("2017-01-25", freq="W"))
>>> period
'2017-01-23/2017-01-29'
```
Parsing this with dateutil gives:
```
>>> dateutil.parser.parse(period)
datetime.datetime(2017, 1, 23, 20, 17, tzinfo=tzoffset(None, -104400))
```
What happens seems to be:
* The year 2017 is taken as is.
* A hyphen in the customary place is ignored.
* The month of January is taken as is.
* A hyphen in the customary place is ignored.
* The day 23rd is taken as is.
* A slash is ignored although it's uncommon to have one between date and time.
* The year 2017 becomes 20 hours and 17 minutes
* A hyphen is ignored.
* The month of January is ignored.
* A hyphen and the day 29 somehow becomes a timezone offset of -29 hours or -104400 seconds.

Perhaps this parser is a bit too lenient? I would rather see an error raised with an input that doesn't look much like a date, time or datetime.

I found this in the pytests of Pandas.

**Comment by mariocj89** [comment]
The parser is indeed too lenient in many cases, sadly we have decided to not try to evolve it more, as any change usually backfires in a different direction. Trying to reject that kind of datetimes will probably result in some exoteric usecase being affected.

We will release the chainparser, review usecases and see if we need to support some more strict kinds of parsers after the next release.

**Comment by jbrockmendel** [comment]
> sadly we have decided to not try to evolve it more, as any change usually backfires in a different direction. Trying to reject that kind of datetimes will probably result in some exoteric usecase being affected.

is this discussion archived somewhere?  ive been inactive here for a while, but in principle have been meaning to get around to improving some of these behaviors

**Comment by mariocj89** [comment]
👋 That's great! IIRC it was online with @pganssle , but he might be able to add more context.
