### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil'

### ISSUE THREAD

**Issue by Muthvel** [dateutil/dateutil#1230]
After installing the python-dateutil, i encounter this error message repeatedly
ModuleNotFoundError: No module named 'dateutil'
I have tried almost all the solution available in google.

Operating system : Windows 11 Home Insider Preview Single Language
command I used to install the dateutil
`pip install python-dateutil`

**Comment by mariocj89** [comment]
Quite likely you installed the pacakge in a different python version, please try the following:

```
python3.10 -m pip install python-dateutil
python3.10 -c "import dateutil"
```
Feel free to change 3.10 by any version that you prefer.

**Comment by Muthvel** [comment]
![Screenshot 2022-08-15 212631](https://user-images.githubusercontent.com/87491163/184670427-ada52da9-25a5-4373-93f1-e0ce118e2ea7.jpg)
It does not seem to work. I will explore more. Thank you

**Comment by brian-pond** [comment]
Just wanted to mention I encountered this exact error today, and was able to workaround it.

### My Environment
1. Debian 11 "Bullseye"
1. I created a new Python Virtual Environment (Python 3.12.2)
    ```bash
    python3.12 -m venv env
    ```
1. I activated my virtual environment:
    ```bash
    source env/bin/activate
    ```
1. I _successfully_ installed dateutil:  `pip install python-dateutil`.  There were no errors yet.

### Error
I tried installing another package (one of my own) in editable mode.  My package's code makes use of dateutil.
When I tried to install:  `pip install -e .`, it failed, and I got the same error seen on many Issues here.

No module named 'dateutil'`

I verified that 'dateutil' was actually installed.  I destroyed and rebuilt my virtual environment.  Identical results every time.

### Solution/Workaround
My package was configured with setuptools using the old method:  a `setup.py` file and `requirements.txt'
On a whim, I removed those files, and replaced with a very simple `pyproject.toml` file.

My package installation then succeeded immediately.  :man_shrugging:
