### ISSUE TITLE
Incorrect relativedelta(months) calculate

### ISSUE THREAD

**Issue by enlike** [dateutil/dateutil#1232]
Hey!

I've faced issue with incorrect months calculate with `relativedelta`

Python example:
```python
from datetime import date
from dateutil.relativedelta import relativedelta


aug30 = date(2022, 8, 30)
aug31 = date(2022, 8, 31)

# adding 3 months to these days
aug30plus3m = aug30 + relativedelta(months=3)
>>> datetime.date(2022, 11, 30)  # correct
aug31plus3m = aug31 + relativedelta(months=3)
>>> datetime.date(2022, 11, 30)  # incorrect. should be (2022, 12, 1)
```
As you see it doesn't add plus 1 day (31.08.2022 looks like it parses to 30.08.2022)

Also I've tried this example with JavaScript and it works well as you can see below.
JS example:

```javascript
aug30 = new Date(2022, 7, 30)
// Tue Aug 30 2022 00:00:00 GMT+0300
aug31 = new Date(2022, 7, 31)
// Wed Aug 31 2022 00:00:00 GMT+0300

// adding 3 months to these days
aug30plus3m = new Date(aug30.setMonth(aug30.getMonth() + 3))
// Wed Nov 30 2022 00:00:00 GMT+0300
aug31plus3m = new Date(aug31.setMonth(aug31.getMonth() + 3))
// Thu Dec 01 2022 00:00:00 GMT+0300
```

**Comment by pganssle** [comment]
"3 months" is not a well-defined period of time, and you are running up against one of the edge cases here.

For the purposes of `relativedelta`, adding N months gives you the same day of the month on the month that is N months later. If that day of month doesn't exist in the new month, it always falls back to the end of the month.

If you want it to fall back to the first day of the following month instead, do something like this:

```python
def add_n_months(start, n):
    end = start + relativedelta(months=n)
    if end.day != start.day:
        return end + timedelta(days=1)
    else:
        return end
```

Or adjust this function as desired to get different fallback behavior.
