### ISSUE TITLE
Officially support Python 3.10, 3.11 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [dateutil/dateutil#1233]

**Comment by mariocj89** [comment]
This is already done, see https://github.com/dateutil/dateutil/blob/master/setup.cfg#L34. I think we are just missing a release.

**Comment by pritamrungta** [comment]
@mariocj89 
is there any timeline for the next release?

**Comment by mariocj89** [comment]
We are late for a release indeed. We should also be updating tzdata. @pganssle do you have some time to go through things for the release this/next week? I pinged you in whatsapp/signal

**Comment by Vico999** [comment]
> This is already done, see https://github.com/dateutil/dateutil/blob/master/setup.cfg#L34. I think we are just missing a release.
In addition, please add Python 3.11

**Comment by pritamrungta** [comment]
- #1211

**Comment by karthich** [comment]
Is there an update on the release? Happy to help. With 3.7 going to EOL we are looking at upgrading to 3.10 for our systems.

**Comment by uri-rodberg** [comment]
You can also end support for Python <= 3.6.

**Comment by rolexsanches** [comment]
You are missing to change collections.Callable to collections.abc.Callable on parse.py

**Comment by westfarn** [comment]
Any chance a new release is coming? Trying to push a few projects to 3.10.

**Comment by TonisPiip** [comment]
+1 waiting for release.
