### ISSUE TITLE
Calling for dateutils involvement in PyData NYC 2022 Sprint

### ISSUE THREAD

**Issue by michael-a-green** [dateutil/dateutil#1235]
Hello dateutil Contributors,

Like every year, we will be running sprints during [PyData NYC 2022](https://pydata.org/nyc2022/), and we were wondering if you would be interested in running a dateutil mini-sprint? We think this is a great opportunity to help our attendees get more comfortable with dateutils and enable them to give back to the project!

This year’s sprints are running alongside tutorials during the conference’s third day, on November 8, 2022. We are calling them mini-sprints as they run in either the morning from 9am-12pm EDT or in the afternoon 1:15pm-4:15pm EDT slots. So far, we have confirmed participation from pandas, HoloViz (holoviews, datashaders, etc.) and AstroPy.

If you are interested, please let us know by Monday Oct. 17, 2022 5pm EDT at the latest. In case you are not available, we would also love to hear suggestions on other dateutils contributors who might be interested.

Thank you,

Michael Green
[malexgreen@gmail.com](mailto:malexgreen@gmail.com)
PyData NYC 2022 Sprint Volunteer Organizer

Cc: Lauren Oldja, PyData NYC 2022 Chair, [loldja@gmail.com](loldja@gmail.com)

**Comment by pganssle** [comment]
Hm. I guess I missed this message. Considering that it's 18 months later, I'm going to say this project was not in "sprint-ready" condition anyway 😛
