### ISSUE TITLE
Compile issues with dateutil in Yocto build (Sumo) on Ubuntu 16.04.07 LTS

### ISSUE THREAD

**Issue by trmong** [dateutil/dateutil#1244]
I am getting some weird compile errors when I try to include dateutil package in my python build.  This is Yocto (Sumo) build from meta-openembedded on  an Ubuntu 16.04.07 LTS build environment.  Says syntax errors.  If I remove just the dateutil package it completes the build fine with all the other python and python3 packages.  It fails the same in both builds (python and python3).  I have tried 2.7.1, 2.7.5, and 2.8.2 all with the same failure.

Any suggestions would be appreciated.

Initialising tasks: 100% |#########################################################################################################################################| Time: 0:00:04
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: python-dateutil-2.7.2-r0 do_compile: python setup.py build execution failed.
ERROR: python-dateutil-2.7.2-r0 do_compile: Function failed: do_compile (log file is located at /home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/temp/log.do_compile.11322)
ERROR: Logfile of failure stored in: /home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/temp/log.do_compile.11322
Log data follows:
| DEBUG: Executing shell function do_compile
| Traceback (most recent call last):
|   File "setup.py", line 86, in <module>
|     "test": Unsupported
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
|     _install_setup_requires(attrs)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
|     dist.fetch_build_eggs(dist.setup_requires)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/dist.py", line 506, in fetch_build_eggs
|     replace_conflicting=True,
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
|     replace_conflicting=replace_conflicting
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
|     return self.obtain(req, installer)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
|     return installer(requirement)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/dist.py", line 573, in fetch_build_egg
|     return cmd.easy_install(req)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
|     return self.install_item(spec, dist.location, tmpdir, deps)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
|     dists = self.install_eggs(spec, download, tmpdir)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
|     return self.build_and_install(setup_script, setup_base)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
|     self.run_setup(setup_script, setup_base, args)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
|     run_setup(setup_script, args)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
|     raise
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/contextlib.py", line 35, in __exit__
|     self.gen.throw(type, value, traceback)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
|     yield
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/contextlib.py", line 35, in __exit__
|     self.gen.throw(type, value, traceback)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
|     saved_exc.resume()
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
|     six.reraise(type, exc, self._tb)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
|     yield saved
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
|     yield
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
|     _execfile(setup_script, ns)
|   File "/home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 44, in _execfile
|     code = compile(script, filename, 'exec')
|   File "/tmp/easy_install-9yiumC/setuptools_scm-7.0.5/setup.py", line 20
|     def scm_version() -> str:
|                       ^
| SyntaxError: invalid syntax
| ERROR: python setup.py build execution failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/207001271/rpi-tmp/tmp/work/aarch64-poky-linux/python-dateutil/2.7.2-r0/temp/log.do_compile.11322)
ERROR: Task (/home/MCA_RDP_SRV/207001271/poky-pi-tmp/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil_2.7.2.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3656 tasks of which 3650 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/MCA_RDP_SRV/207001271/poky-pi-tmp/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil_2.7.2.bb:do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
207001271@mcasvga2:~/poky-pi-tmp/build$

**Comment by trmong** [comment]
I thought it may be the release of Ubuntu.  I have now tried to compile on Ubuntu 18.04.6 LTS with the same result

**Comment by pganssle** [comment]
This seems to be related to how they packaged `dateutil`. Presumably it's pulling in a version of `setuptools_scm` that doesn't work on Python 2.
