### ISSUE TITLE
timezone.now() - relativedelta(month=1) returns wrong date

### ISSUE THREAD

**Issue by JestemStefan** [dateutil/dateutil#1251]
On 2023-01-02 

`timezone.now() - relativedelta(month=1)`

returns

`2023-01-02 11:48:34.561105+00:00`

**Comment by pganssle** [comment]
This is correct. You want `months=1`. It's not a great design. See the section on the arguments here: https://dateutil.readthedocs.io/en/stable/relativedelta.html#dateutil.relativedelta.relativedelta
