### ISSUE TITLE
New smart defaults feature breaks python 3.0 - 3.4

### ISSUE THREAD

**Issue by Ramblurr** [dateutil/dateutil#126]
See https://github.com/dateutil/dateutil/commit/1652d81f0d982f9f73aea4082c15584b22bacf36#diff-ed798069162e7ab7db9a45da6c4a076fR488

`iteritems` doesn't work in python 3.0 - 3.4, see [PEP 0469](http://legacy.python.org/dev/peps/pep-0469). It might work again in 3.5, but as it stands now it breaks in 3.4.

**Comment by pganssle** [comment]
Good catch. This is evidently a failure of code coverage. Should be trivial to fix. Hopefully we're nearing a 2.5.0 release, so we should get out the bug and add a test either then or in a 2.4.3 release if it takes too long.
