### ISSUE TITLE
BUG(?): `"1p9"` parsed as a datetime

### ISSUE THREAD

**Issue by mroeschke** [dateutil/dateutil#1269]
```
In [14]: import dateutil

In [15]: dateutil.__version__
Out[15]: '2.8.2'

In [16]: import dateutil.parser

In [17]: dateutil.parser.parse("1p9")
Out[17]: datetime.datetime(2023, 3, 9, 13, 0)
```

I am not sure how `1p9` translates to the resulting date, but it seems this should be disallowed

**Comment by pganssle** [comment]
This sort of thing is basically not supported. You are supposed to pass the parser a string representing a datetime, and if you pass it something else the behavior is essentially undefined.  We could be more explicit about this in the docs (and I thought that we were, honestly). I've opened #1270 to track adding a more explicit warning to the documentation.
