### ISSUE TITLE
America/Mexico_City no longer correct

### ISSUE THREAD

**Issue by larryprice** [dateutil/dateutil#1278]
dateutil 2.8.2  
python 3.9.16

Parts of the Central Zone in Mexico (including Mexico City) were recently changed to no longer use daylight savings time; they should always be -06.

To reproduce this bug:
```
import datetime
import dateutil.zoneinfo

mc_tz = dateutil.zoneinfo.get_zonefile_instance().get('America/Mexico_City')

print(
    datetime.datetime(2023, 4, 2).astimezone(mc_tz).isoformat()
)
# '2023-04-02T00:00:00-06:00'

print(
    datetime.datetime(2023, 4, 3).astimezone(mc_tz).isoformat()
)
# '2023-04-03T01:00:00-05:00'
# Should be 00:00:00-06
```

Sources:
* https://en.wikipedia.org/wiki/Time_in_Mexico
* https://www.timeanddate.com/time/zone/mexico/mexico-city

**Comment by pganssle** [comment]
I would recommend against using `dateutil.zoneinfo` in general. In the next release it will be a thin wrapper around the PyPI package `tzdata` anyway.

It's also probably best to switch over to using the [`zoneinfo`](https://docs.python.org/3/library/zoneinfo.html) module anyway.

**Comment by larryprice** [comment]
@pganssle Thanks for the advice! We've been using `dateutil` for this for a few years and only upgraded to python 3.9 a few months ago. Using `zoneinfo` fixes my problem.
