### ISSUE TITLE
DeprecationWarning: datetime.utcfromtimestamp() is deprecated

### ISSUE THREAD

**Issue by hugovk** [dateutil/dateutil#1284]
With a self-built version of Python 3.12 that includes https://github.com/python/cpython/issues/103857:

```pycon
Python 3.12.0a7+ (heads/main-dirty:c527eb1c2a, May 15 2023, 10:39:28) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil.tz
/private/tmp/dateutil/src/dateutil/tz/tz.py:37: DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
  EPOCH = datetime.datetime.utcfromtimestamp(0)
>>>
```

That warning again:

> DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).

This is from:

https://github.com/dateutil/dateutil/blob/b04edc08aa3559063b3b097f437941d8c4b84aba/src/dateutil/tz/tz.py#L37

**Comment by jaraco** [comment]
I'm still seeing this warning. Are there plans to cut a release with it (and save me the trouble of suppressing the warning)?

**Comment by EwoutH** [comment]
@mariocj89 @pganssle @graingert Could a stable release be tagged and uploaded to PyPI as soon as possible? Python 3.12 releases in a week, and there is a whole chain of dependencies causing errors because of the deprecated utcfromtimestamp().

**Comment by graingert** [comment]
@EwoutH sorry I don't have permissions to cut a release

**Comment by mariocj89** [comment]
@pganssle is indeed the only person able to upload to pypi.org.

**Comment by haukex** [comment]
Bump, Python 3.12 is now out

**Comment by pydsigner** [comment]
> @pganssle is indeed the only person able to upload to pypi.org.

So none of the other members of the dateutil project can create releases on GitHub? That should be all that's necessary for PyPI uploads, right?
