### ISSUE TITLE
pytz.utc and 

### ISSUE THREAD

**Issue by scls19fr** [dateutil/dateutil#131]
Hello,

I noticed that dateutil timezone is different from pytz

    import pytz
    import datetime
    import dateutil.parser
    dt = datetime.datetime.now(pytz.utc)
    print(dt)
    s_dt = dt.isoformat()
    print(s_dt)
    dt2 = dateutil.parser.parse(s_dt)
    print(dt2)

    assert dt.tzinfo == dt2.tzinfo

raises an error

but 

    assert dt==dt2

is ok

I wonder if that's an issue or a misunderstanding from my side.

Kind regards

**Comment by pganssle** [comment]
@scls19fr The reason that a dateutil timezone and a pytz timezone representing the same time zone don't resolve as equal is that the concept of equality between timezone objects is not well-defined, and so the `__eq__` method is not defined on either object. By default `__eq__` just checks if two objects are the same object:

```python
>>> class MyClass(object):
>>>     pass
>>> a = MyClass()
>>> b = MyClass()
>>> a == b
False
>>> c = a
>>> a == c
True
```

I think the reason the two datetimes compare equal is that datetimes are considered to be equal if they represent the same actual time (e.g. if you convert them both to UTC and they represent the same moment, they are the same thing, even if their representations are in two different time zones):

```python
>>> from dateutil import tz
>>> from datetime import datetime
>>> dt1 = datetime(2015, 11, 1, 9, 45, tzinfo=tz.gettz('America/New_York'))
>>> dt2 = dt1.astimezone(tz.utc())
>>> dt1
datetime.datetime(2015, 11, 1, 9, 45, tzinfo=tzfile('/usr/share/zoneinfo/America/New_York'))
>>> dt2
datetime.datetime(2015, 11, 1, 14, 45, tzinfo=tzutc())
>>> dt1 == dt2
True
```

I think both equality behaviors are sane and reasonable and so I don't think anything needs to change here.

**Comment by scls19fr** [comment]
Thanks for this clarification.
