### ISSUE TITLE
python-dateutil seems to pull Firefox into our build pipeline artifact

### ISSUE THREAD

**Issue by rootVIII** [dateutil/dateutil#1313]
I seem to be encountering an issue with python-dateutil dependencies in my build pipeline. We use boto3 but python-dateutil seems to be a dependency of boto3.  I am sorry that I cannot provide screenshots as they are on the work computer.

We have a vulnerability scanner/service that will block our deployments for even minor violations. For some reason Mozilla Firefox 118.0b4 is being pulled into our application's build artifact. The vulnerability scanner is highlighting this because there are some vulnerabilities related to that FF version.

I am opening an issue here because I cannot figure out why python-dateutil is even pulling FireFox in to being with?

It's showing a directory path of  ```dateutil/zoneinfo/dateutil-zoneinfo``` .  And inside of this there are quite a few timezone directories, two of which named ```Africa/``` and ```Atlantic/``` are getting picked up as security vulnerabilities.

I do not see these timezone folders in your repo, although I do see the path ```dateutil/zoneinfo``` and a tar package ```ZONEFILENAME = "dateutil-zoneinfo.tar.gz"```. https://github.com/dateutil/dateutil/blob/master/src/dateutil/zoneinfo/__init__.py#L13C1-L13C42

Could that tar file be causing this? Do you have any suggestions or know why Firefox would be a dependency of python-dateutil?

Sorry if this is not related to your library and/or out of scope. Thank you!

EDIT: ```pip3 freeze``` and ```pipdeptree``` are showing that we have the latest python-dateutil version 2.8.2.
EDIT 2: Is this tarball from ftp.iana.org/tz? Just looked through your code a bit more but I am not 100%

**Comment by pganssle** [comment]
That tarball is something that is bundled with our wheel files and source distributions. We do not have any kind of dependency on firefox, hopefully you figured it out.
