### ISSUE TITLE
Release with Python 3.12 support without a DeprecationWarning

### ISSUE THREAD

**Issue by m-aciek** [dateutil/dateutil#1314]
Would it be possible to publish a new release of dateutil from master which supports 3.12 without [the DeprecationWarning](https://github.com/dateutil/dateutil/pull/1285)? Thank you!

**Comment by bersbersbers** [comment]
fyi, https://github.com/dateutil/dateutil/issues/1284#issuecomment-1735325677

**Comment by tschaub** [comment]
Does the library work with Python 3.12?

I think this results in `ModuleNotFoundError: No module named 'six.moves'`:
https://github.com/dateutil/dateutil/blob/296d419fe6bf3b22897f8f210735ac9c4e1cb796/src/dateutil/tz/tz.py#L21

**Comment by hugovk** [comment]
@tschaub Yes, this library works with 3.12, see https://github.com/dateutil/dateutil/pull/1300 for passing CI on 3.12. Please open a new issue with details if something isn't working for you.

**Comment by WarrenWeckesser** [comment]
FYI: The deprecation warning that was fixed in https://github.com/dateutil/dateutil/pull/1285 (which is not in a release yet) is currently causing a failure in the SciPy tests in code that uses `matplotlib`, because `matplotlib` uses `dateutil` (see https://github.com/scipy/scipy/issues/19619).  You'll probably get more questions about the deprecation warning as more folks start to use 3.12.

**Comment by dlm6693** [comment]
Hi maintainer for boto3 here. Could we please get this fix released to PyPI soon? We are working on removing the deprecation warnings in the SDK by removing all of our `utcnow` calls, but will still emit one for all customers on python 3.12 so long as this isn't shipped.

Is there anything blocking this being released? It's been nearly 2.5 years since the last version bump.

**Comment by sigma67** [comment]
Hi @pganssle , could you please consider releasing the fixes for 3.12 which are already merged :)

**Comment by mbaak** [comment]
Hi maintainer, what's the status of this, when can we expect a new patch release solving this issue? Thanks!

**Comment by m-aciek** [comment]
It looks like the release automation is [a pre-requirement](https://github.com/dateutil/dateutil/pull/1130#issuecomment-1808635487) for the 2.8.3 release. If someone has experience and time to do it, a PR would be very welcome, I suppose.

**Comment by Jackenmen** [comment]
> It looks like the release automation is [a pre-requirement](https://github.com/dateutil/dateutil/pull/1130#issuecomment-1808635487) for the 2.8.3 release

That seems to already be a thing though?: https://github.com/dateutil/dateutil/blob/master/.github/workflows/publish.yml

[Committed 2 years ago.](https://github.com/dateutil/dateutil/commit/6b337ea412d399fb48771c544b1a6880763b46c6)

**Comment by sigma67** [comment]
@Jackenmen not certain that still works since there have been changes to the project and PyPI in the meantime. Setting up trusted publishing would be the way to go.

**Comment by hugovk** [comment]
I also recommend trusted publishing, but API-token uploading should still work, and I don't think the 2.8.3 release should be delayed any further.

**Comment by Jackenmen** [comment]
I agree with the trusted publishing thing but if the current setup actually works, it's less work from the maintainer to use that than to review a PR adding trusted publishing, update the project on PyPI to work with it, and possibly also having to learn how the new workflow works. So yeah, I'm just wondering if it's an actual blocker or if there are some other chores that would be more important to get done here.

**Comment by sigma67** [comment]
Yeah sure, definitely try with the current workflow -- can always retry if the upload fails

**Comment by sigma67** [comment]
@pganssle is it possible to create a release? it seem it is in high demand

**Comment by kostyaten** [comment]
What's the status of the release?

**Comment by bmos** [comment]
> What's the status of the release?

https://github.com/dateutil/dateutil/pull/1130#issuecomment-1808635487
