### ISSUE TITLE
Support xsd:date format, specifically with timezones

### ISSUE THREAD

**Issue by odscjames** [dateutil/dateutil#1320]
This format is defined at https://www.w3.org/TR/xmlschema-2/#date and isn't currently fully supported - either crashing or returning the wrong value when time zones are used.

```
>>> import dateutil.parser
>>> print(dateutil.parser.parse('2002-09-24Z'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 2002-09-24Z
>>> print(dateutil.parser.parse('2002-09-24-06:00'))
2002-09-24 06:00:00
>>> print(dateutil.parser.parse('2006-04-23+09:00'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 2006-04-23+09:00

```

I realise it may be difficult to tell what is intended in the middle case, so maybe this needs to be a special optional parser that people can opt-in to, or something?

Thanks!

**Comment by pganssle** [comment]
Yeah to be honest the parser in general is too automagical and I generally don't like to touch it. The format you describe here is very ambiguous, and we don't have a good way of specifying configuration to the parser without an options explosion, so I think we're going to have to pass on this one, sorry.

**Comment by odscjames** [comment]
> we don't have a good way of specifying configuration to the parser without an options explosion

I was thinking a new special parser that is not included in dateparser.settings.default_parsers but could be specially added by users to the existing PARSERS setting if they wanted would do it.

I have first pass code at this with tests that I can pass if interested - I'll maybe comment soon with it anyway, just so anyone else who finds this issue has some pointers.

**Comment by pganssle** [comment]
I think adding new special parsers is out of scope for this package at the moment.

To be clear, `dateparser` is a different library - maybe they would be more amenable to adding this feature?
