### ISSUE TITLE
Better support for (sane) dateformats

### ISSUE THREAD

**Issue by GitPeterJ** [dateutil/dateutil#1333]
The problem is that we had multiple times where the logic in dateutil broke because the most common formats are DD-MM-YYYY and YYYY-MM-DD. Unfortunately, the dayfirst parameter fixes one and breaks the other. When dayfirst=True it prefers YYYY-DD-MM over YYYY-MM-DD. Seriously, who would want that?

Is it known when this ever will be fixed? When I read through the issues this was already a [problem](https://github.com/dateutil/dateutil/issues/402) more than 6 years ago!

This repository looks abandoned (while still commonly used), that would be a shame because this library works well for all other parts, but for almost all people outside of the USA this will always be a problem.

**Comment by GitPeterJ** [comment]
@pganssle It's a breaking bug, making the "auto-magic" unusable for when the combination of DD-MM-YYYY and YYYY-MM-DD are the most common (like most parts of the world). Dayfirst parameter is broken now where it will be broken one way or another...

What would be an alternative option is to be able to decide the preferred format order.

**Comment by mcarans** [comment]
@GitPeterJ This has been brought up a few times before. In the end, you'll either have to find an alternative library or as I did, make your own slightly modified parser that fixes the issue.
