### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by ve2tmq** [dateutil/dateutil#1338]
Hi, I would like to commit new feature (new branch): rrule.to_text() to write as human readable rule.

I'm trying to connect on project with my ssh key, I have access denied.

**Comment by meshantz** [comment]
You need to fork the repo, then make a branch and push it to your own repo, and then open a pull request.

Details here:  
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
