### ISSUE TITLE
Version 2.9.0 is not compatible with python 2

### ISSUE THREAD

**Issue by fervand1** [dateutil/dateutil#1344]
Package version 2.9.0 wrongly mentions that it is compatible with python 2.7, But imports are broken

```
    from dateutil import parser
/usr/local/lib/python2.7/site-packages/dateutil/__init__.py:5: in <module>
    from ._version import version as __version__
E     File "/usr/local/lib/python2.7/site-packages/dateutil/_version.py", line 10
E       version: str
E              ^
E   SyntaxError: invalid syntax
```

Update: This version should not be installable on python 2. Metadata needs update

**Comment by matthax** [comment]
Running into a similar issue, boto3 has a dependency on dateutil and it's pulling this version in and bombing out.

**Comment by zifban** [comment]
Same issue but with Python 3.5 and using pandas and matplotlib.

**Comment by AhmadMadi** [comment]
Same issue here, adding `python-dateutil==2.8.2` into the requirements.txt specified the version for boto3 and it worked.

**Comment by molinav** [comment]
Ideally, version 2.9.0 should also be yanked in PyPI, since the metadata are not correct.

**Comment by tinchoram** [comment]
Same issue with:


Versions:

- aws-cli/1.18.223 
- Python/3.5.2 
- botocore/1.19.63

`aws --version`

```
File "/usr/local/lib/python3.5/dist-packages/dateutil/_version.py", line 10
    version: str
           ^
SyntaxError: invalid syntax
```


Workaround: downgrade

`pip3 install -U python-dateutil==2.8.0`

```
aws --version
aws-cli/1.18.223 Python/3.5.2 Linux/5.15.49-linuxkit botocore/1.19.63
```

**Comment by pganssle** [comment]
Ah, this is because `setuptools_scm` at some point decided to start getting a lot fancier with the generated version file. I will pin to an older version of `setuptools_scm` and make a post release.

There should be no need to yank 2.9.0, since the metadata won't change and the only people who would get 2.9.0 would be people who pinned to 2.9.0 exactly (in which case yanking would do nothing).
