### ISSUE TITLE
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439

### ISSUE THREAD

**Issue by labrys** [dateutil/dateutil#135]
Trying:
`datetime.datetime.now(tzwin.tzwinlocal()).utcoffset()`
on Windows raises:
`ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439`

This is after fixing the issue in #133 with `tzwin.py` not importing.
Found while troubleshooting SiCKRAGETV/SickRage-issues#3450

**Comment by labrys** [comment]
Confirmed this in the current version as well with 
`Python27\python -c "import datetime, dateutil.tzwin; print datetime.datetime.now(tzwin.tzwinlocal()).utcoffset()"`
and 
`Python34\python -c "import datetime, dateutil.tzwin; print(datetime.datetime.now(dateutil.tzwin.tzwinlocal()).utcoffset())"`

**Comment by pganssle** [comment]
This one I can confirm:

```python
>>> from dateutil.tzwin import tzwinlocal
>>> twl = tzwinlocal()
>>> print(twl._stdoffset)
-300
>>> print(twl._dstoffset)
-4294967536L
```
Shouldn't be too hard to figure out why that's happening.

**Comment by pganssle** [comment]
I think that this is some funky thing having to do with the way the data is represented. Note:

```python
>>> iv = 4294967236
>>> print(~int(bin(((2 << 32) - 1) & ~iv), 2))
-60
```
I think it's a signed 32-bit integer being represented as an unsigned 32-bit integer for whatever reason.

I'll make the relevant changes tonight.

**Comment by labrys** [comment]
Sounds good.

**Comment by labrys** [comment]
Oh and thanks for all the hard work you've put in.  I don't mean to be a pain in the butt :grinning:

**Comment by pganssle** [comment]
No problem, I appreciate the feedback about what needs fixing and your help in pinpointing the bugs!

**Comment by miigotu** [comment]
ping me if any fixes for this are merged please, so I can update it in SR.

**Comment by labrys** [comment]
Will do.

**Comment by pganssle** [comment]
@labrys @miigotu Proposed fix at #142 if you guys want to take a look and see if it works for you.

**Comment by labrys** [comment]
With this fix `utcoffset` does not throw errors.  

I assume the values are correct since per the python standard library documentation, the value returned must be a `datetime.timedelta` object specifying a whole number of minutes east of utc(west is negative).   
US Eastern Standard Time is UTC-5.  
So:
```python
print datetime.timedelta(minutes=-300)  # -5 * 60 
-1 day, 20:00:00
```
which is the same as `tzwin` and `tzwinlocal`'s `utcoffset()` however, time zones do not properly reflect DST as referenced in #143

**Comment by pganssle** [comment]
Fixed in #141.

**Comment by labrys** [comment]
Confirmed working in Windows with various python versions.

**Comment by Davidhw** [comment]
I observe the same problem on Ubuntu with version 2.4.2.

Replication Steps:
ipython
from dateutil import parser

date = parser.parse("2016-02-17-13-30")
(at this point date is  datetime.datetime(2016, 2, 17, 13, 0, tzinfo=tzoffset(None, -108000)))
print date 
(ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439)

date2 = parser.parse("2016-02-17-14-00")
(date2 is datetime.datetime(2016, 2, 17, 14, 0, tzinfo=tzutc()))
print date2
2016-02-17 14:00:00+00:00

**Comment by pganssle** [comment]
@STANAPI For the future, I recommend that you read [Craft Minimal Bug Reports](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports), as that will help you get your problem solved more easily.

I do not know what the problem with your application is. I notice in the example that you are using `pytz`. You can [read here why I think this is a bad idea](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html).

As to your problem, I don't know what's going on there. I can only guess that it is unrelated to this closed issue and that you you are parsing a datetime that either has an offset outside of +/- 24h, or a format where a too-large offset is being inferred. You should take a look at the format of the datetime you are parsing and work out what the time zone offset it is inferring is.
