### ISSUE TITLE
Consider dropping `six` again now that Python 3.13 alphas are coming out

### ISSUE THREAD

**Issue by simonw** [dateutil/dateutil#1352]
*Original title: `six.moves` is incompatible with the Python 3.13 alphas, so `dateutil` does not currently work with Python 3.13* - but then on further investigation I could not replicate the reported error.

This was reported on one of my projects here:
- https://github.com/simonw/llm/issues/436

The reported error was:
```
...
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/Users/senthilx/cpython/virtualenvs/python313/lib/python3.13/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'
```
Dropping `six` was previously discussed here, but that was over a year ago long before the Python 3.13 alphas came out:
- https://github.com/dateutil/dateutil/issues/1258

https://pypi.org/project/six/#history has not had a release since May 2021. It's not yet clear from the `six` issue tracker if they plan to release a version for Python 3.13: https://github.com/benjaminp/six/issues

**Comment by simonw** [comment]
... this may not be a problem with `dateutil` after all. I wasn't able to replicate it against my own fresh installation of Python 3.13 alpha, from `pyenv`:
```bash
pyenv install 3.13.0a3
```
Then:
```bash
~/.pyenv/versions/3.13.0a3/bin/python -m venv /tmp/3.13.0a3
/tmp/3.13.0a3/bin/pip install python-dateutil
```
And:
```bash
/tmp/3.13.0a3/bin/python -c 'import dateutil; print(dateutil.parser.parse("10 june"))'
```
Outputs:
```
2024-06-10 00:00:00
```

**Comment by hugovk** [comment]
Tests were passing for 3.13 two months ago: https://github.com/dateutil/dateutil/pull/1337

**Comment by simonw** [comment]
I'm going to close this. It looks like `dateutil` remains committed to Python 2.7 support, so `six` needs to stay: https://github.com/dateutil/dateutil/blob/1ae807774053c071acc9e7d3d27778fba0a7773e/.github/workflows/validate.yml#L16

I do think it would be reasonable for `dateutil` to drop Python 2.7 support in future versions, since people on Python 2.7 who ran `pip install python-dateutil` would continue to get a working 2.9.0 version forever even though future releases didn't support them.

**Comment by jvoisin** [comment]
Python 2.7 is unmaintained [since 2019](https://devguide.python.org/versions/), 5 years ago. Nobody should be running it anymore, it's a maintenance/security nightmare. Can we _please_ drop it already, instead of having a pile of gross hacks (`six`) included in dateutil? If only so that people packaging python for Linux distribution can stop having headaches?
