### ISSUE TITLE
Surprising behaviour with stand alone month names

### ISSUE THREAD

**Issue by noamcelery** [dateutil/dateutil#1354]
When parsing a stand alone month names the behavior is surprising and unintuitive.

It returns a date with the current year, the month in question and the current day in the month (example was taken on March 24, 2024)
from dateutil.parser import parse
parse('April')
datetime.datetime(2024, 4, 24, 0, 0)
parse('June')
datetime.datetime(2024, 6, 24, 0, 0)

What would even happen if I use it was the 31th and called parse('February')? I cant even guess. Go back to 28? fail parsing? 
This level of uncertainty for me is a clear sign of bad behavior.

I would think that the most intuitive behavior would be to always fail parsing stand alone month names. If for some reason this is undesirable than at least use the first of the month.

**Comment by pganssle** [comment]
Yes, there are many surprising or unintuitive things about the behavior of the parser, and I tend to recommend against using it if you can.

That said, this has been the documented behavior for the entire lifetime of the parser, and many people are likely relying on it, so I don't foresee changing it.
