### ISSUE TITLE
Unknown pytest marks

### ISSUE THREAD

**Issue by juliangilbey** [dateutil/dateutil#1356]
Running pytest on the test suite gives lots of `PytestUnknownMarkWarning` warnings; here are the unregistered marks:
```
pytest.mark.gettz
pytest.mark.import_star
pytest.mark.isoparser
pytest.mark.parserinfo
pytest.mark.rrule
pytest.mark.rruleset
pytest.mark.rrulestr
pytest.mark.smoke
pytest.mark.tzfile
pytest.mark.tzlocal
pytest.mark.tzoffset
pytest.mark.tz_resolve_imaginary
pytest.mark.tzstr
```
For example:
```
tests/test_tz.py:2098: PytestUnknownMarkWarning: Unknown pytest.mark.tzfile - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
```
I'm also unclear why these tests are marked in this way; is it even needed?

**Comment by pganssle** [comment]
These are all listed in the `setup.cfg`, which is where you register custom marks. Perhaps you are running pytest in some unexpected configuration?

**Comment by juliangilbey** [comment]
Ah, that would be it; it's being run in a CI environment which probably didn't copy the `setup.cfg` file.  Sorry for the noise.

**Comment by juliangilbey** [comment]
Although this should perhaps be moved to `pyproject.toml` instead, which appears to be the new default location of this sort of configuration.
