### ISSUE TITLE
Drop six from dateutil's requirements

### ISSUE THREAD

**Issue by uri-rodberg** [dateutil/dateutil#1361]
Hi,

Since Python 2.7 isn't supported for about 4 years now, isn't it time to drop `six` from `dateutil`'s requirements? Or at least require `six` for only older versions of Python.

Thanks,
Uri.

**Comment by P1ng-W1n** [comment]
I have the same view as @uri-rodberg . 
I don't see the reason why dateutil would need to support a Python version that's not supported for years now.
One could argue that old enterprise distributions (RHEL, SUSE, Oracle Linux) might still need that, but from I can tell those did drop Python2 support too.
Even if there's an LTS distro that still supports Python2, I don't see a reason why they couldn't use an older version of this package (installing most packages on Python2 does require version locking anyway, as a lot of packages did remove support for that already)

I can see that this issue has been closed, but I don't see any justification of why. 
@pganssle - Could you elaborate on the reasoning (or potential plans for the future in that regard) please?
