### ISSUE TITLE
Restrict parsing the date without required data.

### ISSUE THREAD

**Issue by bwala-eightfold** [dateutil/dateutil#1362]
Here are some examples I am referring to
parse(10) => datetime(yearToday, monthToday, 10)
parse(10-10) => datetime(yearToday, 10, 10)
etc.

So in these examples, some parameters out of 3 (month, year or day) are missing.

I want to restrict parse to not parse the date if any one of them looks like missing

How can I achieve this?

**Comment by bwala-eightfold** [comment]
@zamanehsani Do you have any idea?

**Comment by pganssle** [comment]
I agree that this should be possible, but it would be a huge backwards-compatibility breaking change, and it would be a quite complicated interface to design.
