### ISSUE TITLE
RFE: drop use `six` and python 2.x support

### ISSUE THREAD

**Issue by kloczek** [dateutil/dateutil#1367]
Last not EOSed python version is 3.8.

**Comment by kloczek** [comment]
Just found that some work in about this kind of changes has been done in https://github.com/dateutil/dateutil/pull/1349

Is it any reason why this PR has not been merged? 🤔

**Comment by hugovk** [comment]
You've been told why several times before.

See your own previous issues:

* https://github.com/dateutil/dateutil/issues/1206
* https://github.com/dateutil/dateutil/issues/1220
* https://github.com/dateutil/dateutil/issues/1258

And your PR, where you were asked to check the tracker before opening yet more issues:

* https://github.com/dateutil/dateutil/pull/1350
