### ISSUE TITLE
parser.parse(..., fuzzy_with_tokens=True) results in TypeError

### ISSUE THREAD

**Issue by Michael-E-Rose** [dateutil/dateutil#138]
I tried to replicate the example from http://dateutil.readthedocs.org/en/latest/parser.html#dateutil.parser.parse:

    from dateutil.parser import parse
    parse("Today is January 1, 2047 at 8:21:00AM", fuzzy_with_tokens=True)

I expect `(datetime.datetime(2011, 1, 1, 8, 21), (u'Today is ', u' ', u'at '))`, as in the example shown, but I get

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/dateutil/parser.py", line 697, in parse
        return DEFAULTPARSER.parse(timestr, **kwargs)
      File "/usr/lib/python2.7/dist-packages/dateutil/parser.py", line 301, in parse
        res = self._parse(timestr, **kwargs)
    TypeError: _parse() got an unexpected keyword argument 'fuzzy_with_tokens'

Is there something wrong with the docs, or the code, or both?

**Comment by pganssle** [comment]
@Michael-E-Rose This works fine for me. What version of dateutil are you using? You can find  ut using the command: `python -c 'import dateutil; print(dateutil.__version__)'`

Here's what I get with dateutil 2.2:
```python
>>> from dateutil.parser import parse
>>> parse("Today is January 1, 2047 at 8:21:00AM", fuzzy_with_tokens=True)
(datetime.datetime(2047, 1, 1, 8, 21), (u'Today is ', u' ', u' ', u'at '))
```
Same result with dateutil 2.4.2

**Comment by Michael-E-Rose** [comment]
For some reason I am on version 1.5... My old version seems to be the problem. Going to upgrade it. Sorry for the confusion.
