### ISSUE TITLE
Unexpected extra result using "between" across DST exit

### ISSUE THREAD

**Issue by randlet-rf** [dateutil/dateutil#1401]
When running the following script:

```python

import datetime

import pytz
import recurrence

tz = pytz.timezone("US/Eastern")
dtstart = tz.localize(datetime.datetime(2024, 11, 1, 0, 0, 0))
dtend = tz.localize(datetime.datetime(2024, 11, 30, 23, 59, 59, 999))

rule = recurrence.Rule(recurrence.MONTHLY, bymonthday=[1, 15])
rec = recurrence.Recurrence(rrules=[rule])
occurrences = rec.between(dtstart, dtend, dtstart=dtstart, inc=True)
print(dtstart)
print(dtend)
for o in occurrences:
    print(o)
```

The result is:

```
2024-11-01 00:00:00-04:00
2024-11-30 23:59:59.000999-05:00
2024-11-01 00:00:00-04:00
2024-11-15 00:00:00-04:00
2024-12-01 00:00:00-04:00
````

which seems unexpected due to the inclusion of Dec 1st.

**Comment by pganssle** [comment]
What is `dtend` here, and also can you make an MWE that doesn't use `recurrence`?

**Comment by pganssle** [comment]
Oh wait, this might be more a problem with the fact that you are using `pytz`.

I don't think that this would happen with `zoneinfo`, though there are other problems that might come up. 

I recommend using rrule on naïve datetimes and attaching the time zone afterwards.

**Comment by randlet-rf** [comment]
> Oh wait, this might be more a problem with the fact that you are using `pytz`.
> 
> I don't think that this would happen with `zoneinfo`, though there are other problems that might come up.
> 
> I recommend using rrule on naïve datetimes and attaching the time zone afterwards.

Hi Paul,

You are right, it doesn't happen with zoneinfo! We are stuck with pytz for a minute, but working with naive datetimes is a good workaround for this. Thanks for your help, I appreciate your time.
