### ISSUE TITLE
tzwinlocal's repr is incorrect

### ISSUE THREAD

**Issue by labrys** [dateutil/dateutil#148]
The representation of tzwinlocal is inconsistent with tzwin and tzlocal.
````python
import dateutil.tz as tz

print(tz.tzlocal())  # tzlocal()
print(tz.tzwin('Eastern Standard Time'))  # tzwin('Eastern Standard Time'
print(tz.tzwinlocal())  # <dateutil.tzwin.tzwinlocal object at 0x024C7D50>
```
Also inconsistent after proposed fix #142

**Comment by pganssle** [comment]
Reopening per comments on #184 to address the single quotes issue.

**Comment by pganssle** [comment]
More or less resolved based on discussion on #184.

**Comment by labrys** [comment]
Still inconsistent between `tzwin` and `tzwinlocal`
````python
import dateutil.tz as tz

print(tz.tzwinlocal())               # tzwinlocal(u'Eastern Standard Time')
print(tz.tzwin('Eastern Standard Time'))  # tzwin('Eastern Standard Time')
print(tzstr('Eastern Standard Time'))     # tzstr('Eastern Standard Time')
```
`u'Eastern Standard Time'` vs `'Eastern Standard Time'` for the strings

**Comment by pganssle** [comment]
@labrys That's not the `repr`, that's the `str`, I guess?

Still, that's very odd that the behavior is different between `tzwin` and `tzwinlocal`. Compare [the tzwinlocal code](https://github.com/dateutil/dateutil/blob/a3834ae59b057db76a5ec38c5c7d3549248d37e3/dateutil/tz/win.py#L273) to [the tzwin](https://github.com/dateutil/dateutil/blob/a3834ae59b057db76a5ec38c5c7d3549248d37e3/dateutil/tz/win.py#L220) code.

Are you using Python 2 or Python 3? Maybe what's happening is that the Windows registry key stores the time zone names as unicode, so `tzwinlocal()._stdname` is actually `u'Eastern Standard Time'` while, at least in Python 2 or with `from __future__ import unicode_literals`, `tzwin('Eastern Standard Time')` is `b'Eastern Standard Time'`.

I think this is a slightly different issue from the original one, do you want to open a new issue?

**Comment by labrys** [comment]
Sure I'll open a new issue.  I mistakenly assumed you didn't write a separate `str` methods since `repr` get returned when `str` isn't defined.  This test was with Python 2.7.10 and without `unicode_literals`.  And your assertion that `tzwin` is getting a `b''` is exactly the situation here.
