### ISSUE TITLE
Parse failure for a date string with redundant timezone specification

### ISSUE THREAD

**Issue by kcarnold** [dateutil/dateutil#157]
I found some dates in email headers that look like:

```
Thu, 5 Aug 2010 10:38:28 -0400 (GMT-04:00)
Wed, 28 Jul 2010 10:38:18 -0400 (GMT-04:00)
Mon, 26 Jul 2010 10:38:20 -0400 (GMT-04:00)
```

`dateutil.parser.parse` raises `ValueError("Unknown string format")` on them.

All the examples I can find end like the above in `-0400 (GMT-04:00)`, so for them the part in parentheses is redundant. I don't know if that's safe to assume in general, though.

**Comment by pganssle** [comment]
@kcarnold Is using `fuzzy=True` an acceptable solution to this?

```python
>>> from dateutil import parser
>>> parser.parse('Wed, 28 Jul 2010 10:38:18 -0400 (GMT-04:00)', fuzzy=True)
datetime.datetime(2010, 7, 28, 10, 38, 18, tzinfo=tzoffset(None, -14400))
```

I think that given that the idea of `fuzzy` is to indicate that some parts of the string are unnecessary for specifying the date, ignoring the redundancy is a proper use of the  keyword.

**Comment by kcarnold** [comment]
I vaguely recall there being some reason I didn't use `fuzzy`, but I can't recall it now, so let's say that's an acceptable solution. Thanks!

**Comment by pganssle** [comment]
OK, let me know if there's a specific reason this can't work.
