### ISSUE TITLE
parse("Wed, Feb 03 2016. 01 37 PM", fuzzy = True) is failing : hour must be in 0..23

### ISSUE THREAD

**Issue by ishansharma29** [dateutil/dateutil#175]
Hello,

I am using python dateutlil library while parsing some data. While we are extracting out the last updation time, dateutil is failing due to the above mentioned issue (Though it should return a correct time, i.e. 2016, 2, 3, 13, 37 ) . Please let me know if this is expected, or an enhancement coming in upcoming releases? 

Thanks,
Ishan

**Comment by pganssle** [comment]
I believe this bug may have already been reported in #31 and addressed in #32. The fix should be in the next release, which I'm working on now.

**Comment by pganssle** [comment]
Closing as duplicate.
