### ISSUE TITLE
Provide extended strftime support

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#18]
In Python 2.x, [`strftime()` is limited to years > 1900](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior). In Python 3.3, it's limited to years > 1000. My understanding is that at least in the 2.x branch, this behavior is a [WONTFIX](http://bugs.python.org/issue1777412). Is it worth it to provide an alternative version of strftime that works for older versions?

(I bring this up because I've been working on matplotlib's [date-handling module](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/dates.py) and this is one of the things where it's actually doing date calculations that aren't outsourced to library calls.)

**Comment by jarondl** [comment]
@pganssle , sorry for ignoring this for so long.
Yes, we can add this functionality to dateutil if you want.

**Comment by pganssle** [comment]
OK, I can look into the best way to do that. Matplotlib has some way to do it by shifting the date, but I'm a bit worried about the generality of that approach. I don't see a good fit for it in the current set of modules, but I don't know if really deserves to be in its own module. Should it be mapped to a top-level function in the dateutil module itself, or should it be part of a module that might expand later?

**Comment by mariocj89** [comment]
Python3.9 seems to work with any year:

```
>>> datetime.datetime(1,2,3).strftime("%Y/%m/%d")
'1/02/03'
```

Closing given this issue has been open since 2014 and there is not support in Cpython.
