### ISSUE TITLE
documentation: setup.py test does not work

### ISSUE THREAD

**Issue by hjoukl** [dateutil/dateutil#222]
Contrary to what README.rst says, python setup.py test from the project root does  not work for me with:

`AttributeError: 'module' object has no attribute 'test_parser'`

Looks like this stems from 
```
$ PYTHONPATH=./dateutil/test/ python -c 'import test_parser'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/dateutil-master/dateutil/dateutil/test/test_parser.py", line 3, in <module>
    from ._common import unittest
ValueError: Attempted relative import in non-package
```

I can run the tests succesfully though with
`
python3 -m unittest discover -s dateutil/test/ -t .
`

**Comment by pganssle** [comment]
@hjoukl `python setup.py test` does work on most systems, consider that in the CI, [`coverage setup.py test`](https://travis-ci.org/dateutil/dateutil/jobs/116490995#L186) is equivalent to `python setup.py test`. I wonder if this is either some sort of versioning issue on your end.

If you make a clean clone of the current master branch and run `python setup.py test` from the base directory, do you get the same error?

The error you're seeing about 'Attempted relative import in a non-package' is probably an artifact of the way you tried to run `test_parser`.

**Comment by hjoukl** [comment]
You're right. Clean checkout of master worked, on another system. I haven't yet tried it on the machine where I had the problem but looks like an issue on my end. Sorry for the noise.
