### ISSUE TITLE
Error parsing unambiguous dates

### ISSUE THREAD

**Issue by gazpachoking** [dateutil/dateutil#233]
It seems in version 2.5.2, there started being problems parsing unambiguous dates that don't follow the specified dayfirst option:
```python
>>> import dateutil
>>> dateutil.__version__
'2.5.2'
>>> dateutil.parser.parse('2010 09 25', dayfirst=True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Chase\projects\flexget\py27\lib\site-packages\dateutil\parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Chase\projects\flexget\py27\lib\site-packages\dateutil\parser.py", line 577, in parse
    ret = default.replace(**repl)
ValueError: month must be in 1..12
```
In previous versions it would produce a valid date.
```python
>>> import dateutil
>>> dateutil.__version__
'2.5.1'
>>> from dateutil import parser
>>> parser.parse('2010 09 25', dayfirst=True)
datetime.datetime(2010, 9, 25, 0, 0)
```
Was this an intended change?

**Comment by pganssle** [comment]
This was most certainly not an ambiguous change, and probably can be patched in a bugfix release. The 2.5.2 release doesn't have much in it (mainly it was just released to update the `tzdata` update), so I suggest using the 2.5.1 release if possible until we can get out a fix.

**Comment by pganssle** [comment]
Note - if anyone goes to fix this before I get around to it, please work off the `2.5.x` branch, not the the `master` branch.

**Comment by rupert** [comment]
The fix in #234 only works when the day part of `YYYY-MM-DD` is `<= 12`. I suppose you might want to support `YYYY-DD-MM` (!) - SQL Sever uses this format for some languages.

In 2.5.1:

```python
>>> import dateutil
>>> print dateutil.__version__
2.5.1
>>> from dateutil.parser import parse
>>> parse('2015-01-02')
datetime.datetime(2015, 1, 2, 0, 0)
>>> parse('2015-01-02', dayfirst=True)
datetime.datetime(2015, 1, 2, 0, 0)
>>> parse('2015-01-13', dayfirst=True)
datetime.datetime(2015, 1, 13, 0, 0)
```

In 2.5.3:

```python
>>> import dateutil
>>> print dateutil.__version__
2.5.3
>>> from dateutil.parser import parse
>>> parse('2015-01-02')
datetime.datetime(2015, 1, 2, 0, 0)
>>> parse('2015-01-02', dayfirst=True)
datetime.datetime(2015, 2, 1, 0, 0)
>>> parse('2015-01-13', dayfirst=True)
datetime.datetime(2015, 1, 13, 0, 0)
```

Delorean bug: https://github.com/myusuf3/delorean/issues/87

**Comment by pganssle** [comment]
@rupert I'm not sure I understand the issue. `2015-01-13` is unambiguously YYYY-DD-MM. No other interpretation of those values constructs a valid date. The fundamental assumption of the parser is that you gave it a valid date, and it will be as charitable as possible in interpreting that date.

See my comments on #214 if you want `dayfirst` or `yearfirst` to be strict.

**Comment by rupert** [comment]
Yes `2015-01-13` is handled correctly, the issue is with `2015-01-02` being parsed as `YYYY-DD-MM` instead of `YYYY-MM-DD`.

```python
>>> parse('2015-01-02', dayfirst=True)
datetime.datetime(2015, 2, 1, 0, 0)
```

**Comment by rupert** [comment]
To be honest this is more a problem with [delorean](https://github.com/myusuf3/delorean) defaulting `dayfirst` to `True`: https://github.com/myusuf3/delorean/blob/064bc8d0716e06838f11ac38fbf3e56ec63c4e76/delorean/interface.py#L15

**Comment by pganssle** [comment]
Just set it to `False`?

That is the intended behavior change for dateutil version 2.5.2 - the combination of `dayfirst` and `yearfirst` are used to disambiguate between `ymd`, `ydm`, `dmy`, `mdy` as the "default" order for ambiguous triplets. See #81 and #238 for more details on how these work. At some point relatively soon, I will update the documentation with the chart in #238.

**Comment by rupert** [comment]
Yes setting it to `False` works. Originally I wasn't sure if this was an intended change. Thanks for clarifiying, I'm actually now using `dateutil` directly.

`delorean` has some [documentation](http://delorean.readthedocs.io/en/latest/quickstart.html#ambiguous-cases) for `dayfirst` and `yearfirst` which needs updating. I'll add a comment to the other issue. Thanks.
