### ISSUE TITLE
yearfirst should take precedence over dayfirst since it was the default

### ISSUE THREAD

**Issue by alan-unravel** [dateutil/dateutil#238]
#229 fixed an issue with dayfirst but didn't address yearfirst nor collisions between the two, which should either raise a warning or resolve to yearfirst since it was the default

**Comment by pganssle** [comment]
@alan-unravel I don't think there's a real conflict here. For ambiguous dates like `010203`, there are 6 different possible interpretations:

1. YYMMDD
2. YYDDMM
3. MMDDYY
4. DDMMYY
5. MMYYDD
6. DDYYMM

5 and 6, with year in the middle, is *not* a standard way of writing dates and so dateutil doesn't make that guess, so we're left with 4 possible options and 2 flags to specify them.  Per #81, the mapping goes:

```
yearfirst | dayfirst | Format
------------------------------
   False  |   False  |  MMDDYY 
   False  |   True   |  DDMMYY
   True   |   False  |  YYMMDD
   True   |   True   |  YYDDMM
```

As you can see, the operation of `yearfirst` is to move the interpretation of "year" in front of the Month/Day combination, and the operation of `dayfirst` is to move the interpretation of "day" in front of "month".

**Comment by pganssle** [comment]
That said, I mentioned in #232 that I think that as part of an overhaul of `parser`, we may want to reconsider the way this is specified. I'm thinking there's probably some room for specifying a preference ordering based on the `parserinfo` object that might be a bit more flexible (i.e. allowing for MMYYDD or whatever) and that extends to ambiguous 2-element dates like `10/11` (Is that October 2011 or October 11th?)
