### ISSUE TITLE
annotate functions to add types informations 

### ISSUE THREAD

**Issue by jukebox** [dateutil/dateutil#250]
https://github.com/python/typeshed/issues/126

**Comment by pganssle** [comment]
@jukebox I'm not sure I understand what action is requested here. Do you want us to add type annotation directly into the `dateutil` library? I don't think we can do that without breaking Python 2.x compatibility.

Or do  you want us to provide some `.pyi` stubs for the functions in our libraries? That's probably doable, though I'd probably need more information about how `.pyi` stubs work.

**Comment by Naruto0** [comment]
I don't know if i can answer for him, but you definitely don't have to add type annotation directly to dateutil library. That would indeed break compatibility.

He either needs you to provide information on types of your module, so he can generate stubs himself, or he encourages you to make the stub yourself. This is even unclear to me :smile:

Stub is simply skeleton of module which provides bare information of types included in it. See [this](http://mypy.readthedocs.org/en/latest/basics.html#typeshed).

**Comment by pganssle** [comment]
@Naruto0 Yes, thanks. I poked around and I think that they probably wanted consent for python/typeshed#133 (which I gave). I'm going to go ahead and close this, and I'll keep an eye on the typeshed repo.
