### ISSUE TITLE
Provide version of Olson's database as a constant

### ISSUE THREAD

**Issue by skontar** [dateutil/dateutil#27]
The documentation claims that:

> Internal up-to-date world timezone information based on Olson's database. 

However, the current used version of the database cannot be found from installed package. Please provide constant with stored version of used database.

**Comment by pganssle** [comment]
@skontar Have you run the updatetzinfo.py?

> To get (and update) the database, run the updatezinfo.py script.

I believe this is done because it is likely better to allow users to update the timezone database independent of updates to the library itself.

**Comment by skontar** [comment]
@pganssle I am not really interested in updating the database myself. I would just like to know version number (e.g. 2014j) of the already included database which was used when the library was built. Something similar to `pytz.OLSEN_VERSION`.

**Comment by pganssle** [comment]
@skontar Oh, sorry, I completely misunderstood what you were asking. I thought you were looking for the *current version* (i.e. most recent) of the *database*, not the version *number* that the library is currently using. I agree that providing the version number is a good idea.
