### ISSUE TITLE
TZPATHS missing Solaris path

### ISSUE THREAD

**Issue by dhduvall** [dateutil/dateutil#276]
In `dateutil/tz/tz.py`, TZPATHS is set to a list of paths where zoneinfo files might be found.  The path on Solaris is none of them, but `/usr/share/lib/zoneinfo` instead.  For delivery on Solaris, we're patching that path to the front of the list, but perhaps adding that path would be nice for folks getting dateutil to work on Solaris direct from source.

**Comment by pganssle** [comment]
@dhduvall If you want to make a PR I'll accept it. Otherwise, I can fix this myself. I would recommend putting it at the end of the list, not the beginning, just because Solaris systems are rare compared to the others.

**Comment by dhduvall** [comment]
Seems overly process-y for a PR, and I don't need credit.  I was unsure about the ordering, anyway, since the Ubuntu systems I have use `/usr/share/zoneinfo`,  and the last two elements of the list might not be in use anywhere anymore (does anyone really deliver the database in `/etc` anymore?).
