### ISSUE TITLE
datetime.timedelta cannot be added to relativedelta

### ISSUE THREAD

**Issue by justanr** [dateutil/dateutil#282]
```python
from dateutil import relativedelta
import datetime

relativedelta.relativedelta(years=1) + datetime.timedelta(days=1)
```

Results in a `TypeError: unsupported type for add operation`, despite both being time offsets.

However, it is perfectly possible to add a `relativedelta` to another `relativedelta`:

```python

relativedelta.relativedelta(years=1) + relativedelta.relativedelta(years=1)
# relativedelta(years=+2)
```

I'm happy to submit a PR if there is interest (beyond myself) in this.

**Comment by pganssle** [comment]
Hm.. I think this is a reasonable enhancement, considering that for unambiguous relative units (`day` and below), I believe `relativedelta` acts exactly like a `timedelta`, and `timedelta` doesn't *accept* unambiguous units. It's worth looking into for incompatibilities, though.

**Comment by justanr** [comment]
Alright, I'll start putting together a PR.
