### ISSUE TITLE
Please add full key fingerprint to the README file

### ISSUE THREAD

**Issue by valholl** [dateutil/dateutil#287]
In the README.rst file there is a reference to the long-id of the gpg key used to sign the releases which is incorrectly identified as a "fingerprint".

While long id collisions aren't currently as trivial as short id ones, good practice is to use the full fingerprint for key verification, so it would be useful to have it in the readme.

At the very least, an `s/Signing key fingerprint/Signing key ID/` would be required to make the README formally correct.

Thanks in advance

**Comment by pganssle** [comment]
Good point.

FWIW, here's the long id:

```
6B49 ACBA DCF6 BD1C A206 67AB CD54 FCE3 D964 BEFB
```

**Comment by pganssle** [comment]
Implemented in #304.
