### ISSUE TITLE
Support of RFC 7529

### ISSUE THREAD

**Issue by JCavallo** [dateutil/dateutil#315]
I came across the [RFC 7529](https://tools.ietf.org/html/rfc7529#section-4) while trying to investigate a case where a monthly rrule would skip over February with a dtstart on the 30 / 31 of a previous month.

I understand the expected behavior of rrule under the current implementation is to ignore values which are invalid dates, but I was wondering if support for RFC 7529 was planned or would be accepted if properly implemented in a PR.

Thanks for the work on dateutil anyway, this module is a lifesaver !

**Comment by pganssle** [comment]
This is a duplicate of #285, and is currently planned for the 2.7.0 release, hopefully. A PR would most certainly be welcome.
