### ISSUE TITLE
dateutil 2.6 gives segfault in pandas tests (related to timezones)

### ISSUE THREAD

**Issue by jorisvandenbossche** [dateutil/dateutil#317]
I didn't yet looked into more detail, but a small reproducible example is:

```
import pandas as pd
import datetime

dt = datetime.datetime(2011, 1, 1, 9, 0)
offset = pd.offsets.Day()
pd.Timestamp(dt, tz='dateutil/Asia/Tokyo')
pd.Timestamp(dt, tz='dateutil/Asia/Tokyo') + offset
offset2 = pd.offsets.Day(normalize=True)
pd.Timestamp(dt, tz='dateutil/Asia/Tokyo') + offset2
```

gives

```
>>> import pandas as pd
>>> import datetime
>>> 
>>> dt = datetime.datetime(2011, 1, 1, 9, 0)
>>> offset = pd.offsets.Day()
>>> pd.Timestamp(dt, tz='dateutil/Asia/Tokyo')
Timestamp('2011-01-01 09:00:00+0900', tz='dateutil//usr/share/zoneinfo/Asia/Tokyo')
>>> pd.Timestamp(dt, tz='dateutil/Asia/Tokyo') + offset
Timestamp('2011-01-02 09:00:00+0900', tz='dateutil//usr/share/zoneinfo/Asia/Tokyo')
>>> offset2 = pd.offsets.Day(normalize=True)
>>> pd.Timestamp(dt, tz='dateutil/Asia/Tokyo') + offset2
Segmentation fault (core dumped)
```

This started occurring with dateutil 2.6

Related issue on the pandas tracker: https://github.com/pandas-dev/pandas/issues/14621

**Comment by pganssle** [comment]
Very strange. I can't imagine how dateutil could cause a segmentation fault in pandas. Also, Asia/Tokyo has been a fixed offset zone since before 1970. Things that have changed in `tzfile` are the addition of fold support and I switched over the transition-finding algorithm to use `bisect` instead of some slow for loop. Pretty sure `pytz` does the same thing, though.

**Comment by jorisvandenbossche** [comment]
Posting from the issue on pandas, more trimmed down example:

```
In [1]: dt = pd.Timestamp('2016-01-01 09:00:00', tz='dateutil/Asia/Tokyo')

In [2]: dtpy = dt.to_pydatetime()

In [3]: dtpy
Out[3]: datetime.datetime(2016, 1, 1, 9, 0, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Tokyo'))

In [4]: dtpy.replace(hour=0)
Out[4]: datetime.datetime(2016, 1, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Tokyo'))

In [5]: dt.replace(hour=0)
Segmentation fault (core dumped)
```

**Comment by jorisvandenbossche** [comment]
Not sure if it is necessarily a bug in dateutil, but it's in any case a change in dateutil that triggered it to surface (as only downgrading dateutil keeping all other libraries the same solves it)

**Comment by pganssle** [comment]
@jorisvandenbossche I'm not sure exactly what's going on here. One thing that may have changed is that there are some edge cases where `datetime.astimzone()` will generate a `_DatetimeWithFold(datetime)` object instead of a `datetime` object. That doesn't seem to be the case here, though.

**Comment by pganssle** [comment]
@jorisvandenbossche This is very odd. I tried to find the issue with `git bisect`, but I'm getting this issue even in quite old commits, but never in the tagged releases. I have no idea why that is.

**Comment by jorisvandenbossche** [comment]
@pganssle so also in commits from *before* a previous release?

**Comment by pganssle** [comment]
@jorisvandenbossche So it would seem:

```
[(c778dd1...)|BISECTING@/home/.../dateutil/dateutil]$ git checkout 13404cd
Previous HEAD position was c778dd1... Prepare 2.5.2 release.
HEAD is now at 13404cd... Refactor epoch timestamp conversions.
[(13404cd...)|BISECTING@/home/.../dateutil/dateutil]$ python -c "import dateutil; print(dateutil.__version__); import pandas as pd; dt = pd.Timestamp('2016-01-01 09:00:00', tz='dateutil/Asia/Tokyo'); dt.replace(hour=0)"
2.5.1
Segmentation fault (core dumped)
```

**Comment by pganssle** [comment]
Oh, I see what's happening, I was developing the 2.6.0 branch on master and basing tagged releases on a 2.5.x branch. I think the non-linear history may be throwing things off.

**Comment by jorisvandenbossche** [comment]
In any case, I just cloned dateutil and installed it from source, and I am not seeing the segfault anymore.

**Comment by pganssle** [comment]
Allegedly the commit that broke things is this one: [13404cd824c52c92dfd4ea13](https://github.com/dateutil/dateutil/commit/13404cd). Not sure why exactly that would be.

**Comment by pganssle** [comment]
@jorisvandenbossche Is this the expected behavior:

'''python
>>> import pandas as pd
>>> from datetime import datetime
>>> dt = pd.Timestamp('2016-01-01 09:00:00')
>>> datetime.replace(dt, hour=0)
Segmentation fault (core dumped)
'''

I would have expected this to work based on [this line](https://github.com/pandas-dev/pandas/blob/cebc70cc277462176edea73bb71eaad9f83e9f47/pandas/tslib.pyx#L662) in the implementation.

**Comment by jorisvandenbossche** [comment]
Nope, that should certainly work in principle. And I can confirm that this one does not depend on the dateutil version.

**Comment by pganssle** [comment]
OK, this looks like it was a bug upstream and has been fixed.
