### ISSUE TITLE
parser: default day is the 25th

### ISSUE THREAD

**Issue by bpietropaoli** [dateutil/dateutil#325]
```
>>>import dateutil.parser
>>>dateutil.parser.parse("2014-01")
datetime.datetime(2014, 1, 25, 0, 0)
>>>dateutil.parser.parse("2016-11")
datetime.datetime(2016, 11, 25, 0, 0)
```

I had the same issue with both Python 2 and 3. The issue is observed with python-dateutil 2.6.0.
Strangely, I remember having a similar behaviour in a previous version but with like the 8th instead of the 25th.

Maybe it's just me but this behaviour seems rather odd. If I would create a date/datetime given this format (acceptable ISO8601), I would expect it to get the 1st of the month at midnight, not a random day.

**Comment by pganssle** [comment]
@bpietropaoli By default, the current day at midnight is used. I personally don't love this convention, but that's how the API works currently. I'm hoping to get an overhaul of the parser behavior in an upcoming release, and there should be a way to specify smarter defaults as part of that, but for now just change the `default` parameter to whatever you want, e.g:

```python
import dateutil.parser
from datetime import datetime
dateutil.parser.parse("2014-02", default=datetime(2016, 1, 1, 0, 0))
# datetime.datetime(2014, 2, 1, 0, 0)
```

**Comment by bpietropaoli** [comment]
Just realised that the 25th was today. :D
Sorry for bothering you with that then. Thanks for pointing to the default parameter, I'll have a look at that.

**Comment by mdruiter** [comment]
I also find the indeterminate behavior surprising. At least there should be a simple way to disable it, like being able to say `default=False` for instance.
