### ISSUE TITLE
dst() incorrectly handles Pacific/Apia day leap

### ISSUE THREAD

**Issue by sirdodger** [dateutil/dateutil#331]
It seems like dateutil is incorrectly handling the day leap for the Pacific/Apia timezone.  This same bug occurred in pytz, but was fixed years ago.  Here is the reference bug for pytz.
https://bugs.launchpad.net/pytz/+bug/885163

```
>>> import datetime
>>> import dateutil.zoneinfo
>>> tz = dateutil.zoneinfo.gettz('Pacific/Apia')
>>> d = datetime.datetime(2012,1,1,tzinfo=tz)
>>> d.dst()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: tzinfo.dst() returned 1440; must be in -1439 .. 1439
```

**Comment by pganssle** [comment]
@sirdodger Sorry for not looking at this earlier.

For starters, don't use `dateutil.zoneinfo`, as a general rule. `dateutil.tz.gettz()` falls back to `zoneinfo.gettz()` *after* checking the machine's time zone information, and as such should be preferred.

Additionally, what version of `dateutil` are you using? This appears to work just fine in `dateutil 2.6.0`:

```python
>>> import dateutil
>>> print(dateutil.__version__)
'2.6.0'

>>> from dateutil.zoneinfo import gettz as gettz_zi
>>> from dateutil import tz
>>> APIA_ZI = gettz_zi('Pacific/Apia')
>>> APIA = tz.gettz('Pacific/Apia')

>>> d = datetime(2012, 1, 1, tzinfo=APIA_ZI)
>>> d.dst()
datetime.timedelta(0, 3600)

>>> d = datetime(2012, 1, 1, tzinfo=APIA)
>>> d.dst()
datetime.timedelta(0, 3600)
```

**Comment by sirdodger** [comment]
I was using 2.4.2, sorry for the already-fixed bug report.  (Both versions of gettz exhibited the same behavior in that version, though.)

Thanks for the information about gettz.  In this case, I am running a web service that is loading timezone information for clients around the world, so I don't see why checking the machine's timezone first would be beneficial.

**Comment by pganssle** [comment]
@sirdodger No problem about the already-fixed report. Better to err on the side of too many reports than too few (within reason I suppose).

Regarding `gettz`, if you are going to manually manage the zoneinfo files by generating them yourself when upstream changes take place, but the system we have in place right now, I don't always make a python-dateutil release when tzdata gets updated - I haven't yet decided if it's better to spin out the tzdata as its own package or if it's better to just provide a `dateutil update-zoneinfo` function that pulls updated zoneinfo data independent of package updates.

Even if I were spawning a new version of dateutil for every `tzdata` release (they happen about 14-16 times per year), consider that you are using version 2.4.2, which was released in *March 2015*. You probably don't want to be exclusively relying on the time zone data shipped with the `python-dateutil` package if you update it once every 18 months. ;)
