### ISSUE TITLE
Indentation typo in _parse?

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#333]
parser.py, lines 794-802:

    if idx == 1:
        res.minute = int(value)

        if value % 1:
            res.second = int(60*(value % 1))
        elif idx == 2:
            res.second, res.microsecond = \
                                    _parsems(value_repr)
            i += 1

The "idx == 2" branch will never be reached.  I'm pretty sure this is supposed to be:

    if idx == 1:
        res.minute = int(value)

        if value % 1:
            res.second = int(60*(value % 1))
    elif idx == 2:
        res.second, res.microsecond = \
                                _parsems(value_repr)
        i += 1

Maybe the "i+=1" is supposed to be applied in both branches?

**Comment by pganssle** [comment]
Yes, this definitely seems wrong, I'll have to look into it to understand what this code does...

**Comment by pganssle** [comment]
OK, the `elif` branch definitely is supposed to be on the level of `if idx == 1`. Working on a test to show that this actually causes a bug. (I think it will fail to parse, e.g. `14 m 30` incorrectly)

Still not sure what the `i += 1` is supposed to do, though. It might be redundant, or it might be to handle some situation we're not testing for.
