### ISSUE TITLE
Parser.weekday does not support short days with less than 3 chars

### ISSUE THREAD

**Issue by arcanefoam** [dateutil/dateutil#343]
In German, the short day versions only have 2 letters. So even if I supply my own WEEKDAYS dict with the correct locale, parser.weekday does not work (it tests if the name passed has len >= 3).

**Comment by pganssle** [comment]
I think this should be fixed by #382. Thanks @jonemo!

**Comment by arcanefoam** [comment]
Great! Thanks @jonemo for the patch.
