### ISSUE TITLE
Return relativedelta in microseconds only

### ISSUE THREAD

**Issue by JaniKarh** [dateutil/dateutil#352]
Feature request: I am using `relativedelta` to count the difference between two timestamps. I would like to get the `dateutil.relativedelta.relativedelta` object's value in microseconds only, in addition to current options. Now I need to count this (mins + seconds + microseconds, etc.) myself every time or make my own package.

**Comment by pganssle** [comment]
@JaniKarh Why not just write a convenience function for this, similar to [this one](https://github.com/dateutil/dateutil/blob/master/dateutil/tz/_common.py#L375)? I am not sure why you want to use `relativedelta` for this purpose, though - if you want an absolute difference in times (like a number of seconds), it seems like a `datetime.timedelta` would be the more appropriate data type for this purpose. `relativedelta` is used for situations where the absolute amount of time that passes (in seconds elapsed) between two dates changes depending on the date - e.g. "1 month" or "1 year".

**Comment by JaniKarh** [comment]
Thanks for your feedback. At the moment I have a convenience function in place just like that. Datetime.timedelta might actually be a better fit for this, thanks for you proposal.
