### ISSUE TITLE
There are no exception during parse wrong year in datetime string

### ISSUE THREAD

**Issue by heappro** [dateutil/dateutil#353]
Parser will not raise exceptions If you specify wrong year "201A".
Sample code:
```
from dateutil import parser

origin = "201A-01-01T23:58:39.239769+03:00"
parsed = parser.parse(origin)
print("origin={}".format(origin))
print("parsed={}".format(parsed.isoformat()))
```
Output:
origin=201A-01-01T23:58:39.239769+03:00
parsed=2017-03-22T23:58:39.239769+03:00

I use python3.5 on Mac.
dateutil version="2.6.0"

**Comment by pganssle** [comment]
Possibly related to #326 and #360 (though maybe completely different).

**Comment by jbrockmendel** [comment]
The problem here is that in the `i=0` step of the parsing, `info.ampm(l[i + 1]) is not None` and so we do two incorrect things: 1) set `res.hour = 201`, and 2) later overwrite that without checking if an hour already exists.
