### ISSUE TITLE
dateutil.parser: GMT != UTC

### ISSUE THREAD

**Issue by MA3STR0** [dateutil/dateutil#356]
Hi,
I found strange behavior when UTC string is not parsed the same way as GMT:

```
print parser.parse('2017-03-29T00:00:00 UTC')
2017-03-29 00:00:00+00:00 
print parser.parse('2017-03-29T00:00:00 GMT')
2017-03-29 00:00:00+01:00
```

Could it be because of my local CEST zone? I think it was different during winter time.
Thanks!

**Comment by pganssle** [comment]
Duplicate of #349.

**Comment by pganssle** [comment]
Actually, see #370, not #349.
