### ISSUE TITLE
Parser fails to parse 'DDmonYYYY'

### ISSUE THREAD

**Issue by asishm** [dateutil/dateutil#360]
```python
>>> dateutil.parser.parse('13NOV2017', fuzzy=True)
datetime.datetime(2017, 4, 13, 0, 0)  # --- today's date

>>> dateutil.parser.parse('13NOV2017', fuzzy=True, dayfirst=True)
datetime.datetime(2017, 4, 13, 0, 0)  # --- today's date
```
Without fuzzy, it raises an error.

These should parse to the proper dates. I am not sure how the tokenization is done, but a possible solution could be to use an alphabet character (in addition to what I think is used - any non-alphanum character)

**Comment by pganssle** [comment]
@asishm With `fuzzy` it is basically ignoring `NOV` (though, interestingly, `NOV` is not showing up as a token). I think #326 is related.

`13 NOV 2017` works, if you have any control over the format of the string to parse.

**Comment by jamesnunn** [comment]
I encountered this issue today also. It would be more manageable if the returned value doesn't default to todays date because at least then we know that something failed and to try something else.
