### ISSUE TITLE
Parsing isoformat sometimes gets confused between single digit years and months

### ISSUE THREAD

**Issue by DRMacIver** [dateutil/dateutil#387]
The date and time "0005-01-01T00:00:05" (which is output from the standard library's isoformat method) gets parsed incorrectly:

```pycon
>>> from dateutil.parser import parse
>>> parse('0005-01-01T00:00:05').isoformat()
'0001-05-01T00:00:05
```
The month and the year have been swapped here, despite the year being in an unambiguous four digit form.

Curiously, the trailing 5 seconds are *not* an accidental detail and are required to reproduce the bug. If it is changed to zero seconds then the problem goes away:

```pycon
>>> parse('0005-01-01T00:00:00').isoformat()
'0005-01-01T00:00:00'
```

**Comment by pganssle** [comment]
I believe this is fixed in #510.

```python
>>> parser.parse('0005-01-01T00:00:05').isoformat()
'0005-01-01T00:00:05'
```
