### ISSUE TITLE
default date indicator

### ISSUE THREAD

**Issue by asishm** [dateutil/dateutil#403]
I was looking at the parser object that accepts a `default` parameter which is the default datetime object.

Is it possible to return an indicator variable along with the parsed date that indicates which part(s) of the default date were used when parsing?

My current use-case is: If it parsed an exact date, then it's good to go. If it parsed a date which had a missing year and used the default datetime's year, then I want it to be flagged to see if I can populate it via other means.

**Comment by pganssle** [comment]
This will be fixed when #125 is implemented. No timeline on that at the moment, unfortunately. For now a way to hack it might be to pass in a `default` date that has some absurd year like 1044 and detect that?

If you want to be more certain, you can parse the same date twice using different default values and detect which ones change between parses. Example:

```python
from dateutil import parser
from datetime import datetime
import warnings

def double_parse(dt_str):
    dflt_1 = datetime(1, 1, 1)
    dflt_2 = datetime(2, 2, 2)

    dt1 = parser.parse(dt_str, default=dflt_1)
    dt2 = parser.parse(dt_str, default=dflt_2)

    if dt2.year != dt1.year:
        warnings.warn('Year is missing!', RuntimeWarning)
        return dt1.replace(year=datetime.now().year)

    return dt1

if __name__ == "__main__":
    print(double_parse('2017-04-05'))
    # 2017-04-05 00:00:00

    print(double_parse('03:45 EST'))
    # stderr: RuntimeWarning: Year is missing!
    # 2017-01-01 03:45:00-05:00
```
