### ISSUE TITLE
Add isoparse() function.

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#424]
There is currently no inverse to the `isoformat()` function. If you *know* you've got an iso8601 date, the logic is actually *much* simpler than the current parser logic, but because `isoformat()` outputs a format not compatible with even Python 3.6's `strptime()` (shamefully), it's some pretty low hanging fruit.

**Comment by jbrockmendel** [comment]
One solution here would be to adapt the numpy/pandas iso8601 parser.  I think there are a couple corner cases we would want to fix up, but it's generally in pretty good shape.

The down-side is that it is in a C extension.  My impression is that for this format in particular, people are going to want that performance bump.  But dateutil being pure-python is really pleasant, so I'm ambivalent on this one.

**Comment by pganssle** [comment]
@jbrockmendel Yeah, I've been very hesitant to do anything with C extensions because it can add deployment headaches downstream. I have an idea of how to do the iso8601 parser, that I believe will be quite fast (for pure python, anyway). I believe that most if not all of the iso8601 formats have a fixed length, so it may be possible to just look up the format string by the length of the input, with some corner cases handled.

**Comment by wagner-certat** [comment]
A c extension could be optional, so downstream can enable/use it voluntarily.

**Comment by pganssle** [comment]
Done in #489.
