### ISSUE TITLE
Doesn't parse XM times correctly

### ISSUE THREAD

**Issue by brookcub** [dateutil/dateutil#426]
The dateutil parser currently parses XM as PM, when it should be parsed as AM.

XM is sometimes used instead of AM/PM on TV spot logs to note that a time is between midnight and 6:00 AM. I've attached an image of an example spot log for reference.

![sample spot log xm](https://user-images.githubusercontent.com/22346091/28537131-de9bf5e6-7077-11e7-8aa9-1c44328849e4.PNG)

**Comment by jbrockmendel** [comment]
The `parserinfo` class allows you to customize what gets recognized as an AM/PM token:

```
from dateutil.parser import parse, parserinfo
parserinfo.AMPM[0] = (u'am', u'xm', u'a')
parse('12:06:58 XM', parserinfo=parserinfo())
# datetime.datetime(2017, 7, 24, 0, 6, 58)
```

or a more sledge-hammer approach:

```
dateutil.parser.DEFAULTPARSER.info._ampm[u'xm'] = 0
parse('12:08:07 XM')
# datetime.datetime(2017, 7, 24, 0, 8, 7)
```

**Comment by pganssle** [comment]
@jbrockmendel I think the more proper way would be to instantiate a `parserinfo` object and set its attribute that way.

```python
from dateutil.parser import parse, parserinfo
xm_parserinfo = parserinfo()
xm_parserinfo.AMPM[0] = (u'am', u'xm', u'a')
parse('12:06:58 XM', parserinfo=xm_parserinfo)
```

That said, if this has an unambiguous meaning as a subset of AM, I think we can probably include it in the default parser.
