### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by ClaymanTwinkle** [dateutil/dateutil#433]
```python
import datetime

from dateutil import rrule

print str(rrule.rrule(rrule.MONTHLY, dtstart=datetime.datetime(2017, 3, 31, 0, 0),
                      until=datetime.datetime(2017, 8, 1, 0, 0)).count())

```

> the result is 3! It's so crazy!

**Comment by ClaymanTwinkle** [comment]
the right answer is 5

**Comment by pganssle** [comment]
See #149. This is (interestingly) the proper behavior of RRULE per the spec as implemented. I believe there are extensions to the spec that handle this - see #285. When those are implemented there will be a better way to handle this.
