### ISSUE TITLE
Examples in documentation should be broken up by module

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#443]
Currently the documentation has a huge monolithic ["examples" page](https://dateutil.readthedocs.io/en/latest/examples.html) that covers how a bunch of the classes and functions are used. I think it would be much easier to stumble on if these examples were moved into the base page for their respective modules (e.g. the module docstring, for the most part - though maybe we want to duplicate *some* of the examples in the class/function docstrings).

If this is done, to avoid breaking old links, the "examples" page should be replace with links to the examples anchor on each of the respective module pages.

**Comment by colfax23** [comment]
I'll take this one

**Comment by pganssle** [comment]
After seeing the results of a lot of the moves here, I am thinking this is not as good an idea as I had originally thought.
