### ISSUE TITLE
pandas bug

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#445]
Just noticed this in pandas._libs.tslib.pyx, parking it here to follow up on later.
```
if '.tar.gz' in tz._filename:
                raise ValueError(
                    'Bad tz filename. Dateutil on python 3 on windows has a '
                    'bug which causes tzfile._filename to be the same for all '
                    'timezone files. Please construct dateutil timezones '
                    'implicitly by passing a string like "dateutil/Europe'
                    '/London" when you construct your pandas objects instead '
                    'of passing a timezone object. See '
                    'https://github.com/pandas-dev/pandas/pull/7362')
```

**Comment by pganssle** [comment]
I'm not entirely sure what this is referring to, but I doubt it's a real bug. The only difference between Windows and *nix with respect to zone files is that *Nix will generally have system time zones and Windows won't, so Windows is likely to be using our `zoneinfo` tarball.

In any case, `_filename` is not part of the public API and we can set it to anything we want.

They reference [this bug](https://bugs.launchpad.net/dateutil/+bug/1010050) which is fixed now at one point in the very long conversation at pandas-dev/pandas#7362. Is it possible that this refers to the now-defunct #5?
