### ISSUE TITLE
Please roll a new release

### ISSUE THREAD

**Issue by agx** [dateutil/dateutil#452]
Hi,
the current set of dtstart fixes is very useful and it woud be great to have this on pypi. Can you roll a new release?

**Comment by pganssle** [comment]
@agx Unfortunately, we're not really in a "continuous deployment" development mode at the moment (though I'd certainly like to move towards that), and I'm not super comfortable with cutting a feature release at the moment.

I'll look into maybe backporting some of the bug fixes that are currently in the pipeline for the 2.7.0 release and cutting a 2.6.2 release.

**Comment by agx** [comment]
@pganssle Thanks! I came across this when checking why calypso won' t accept certain events and it turned out it was due to a DTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20170903T110000 field which parses fine with current git master. If these parts could go into a 2.6.2 that would be awesome (so I can upload a new version to Debian).
