### ISSUE TITLE
parse does not allow tzlocal in tsinfos

### ISSUE THREAD

**Issue by cornelinux** [dateutil/dateutil#456]
I noticed an incompatibility between verion 2.4.2, 2.5.0 and above.

I need to parse a timestamp string, that has no tz information to a datetime object with timezone.

In version 2.4.2 I was able to do:

    from dateutil.parser import parse
    from dateutil.tz import tzlocal
    ts = "01/04/17 10:00"
    d = parse(ts, tzinfos=tzlocal, dayfirst=True)

Which resulted in 

    datetime.datetime(2017, 4, 1, 10, 0, tzinfo=tzlocal())

Starting with version 2.5.0 I get an exception. I debugged into the parser module, but I can not get my head around it and do not see why it is breaking...

Obviously the __init__method of your tzlocal class has changed. In 2.4.2 the __init__ of tzlocal was inherited by ``tzinfo`` whose init looked like this:

    def __init__(self, *args, **kwargs): # real signature unknown
        pass

Can I consider this a bug?
Since you are allowing calling parse with a tzinfos set to a ``collections.Callable`` which has an incompatible init method?

How am I supposed to achieve the expected behaviour with version 2.5.0 and higher?

**Comment by pganssle** [comment]
@cornelinux That is not what `tzinfos` is supposed to do.

Consider that if you just want to attach a time zone to the date, you can just do this:

```python
dt = parse(dt_str).replace(tzinfo=tzlocal())
```

What `tzinfos` is supposed to do is take a dictionary mapping time zone strings to time zones (e.g. `tzinfos={'EST': tzoffset(timedelta=hours-5'), 'CST': tzoffset(timedelta(hours=-6))}`) or a callable that takes time zone strings and generates `tzinfo` objects. It was just a random mistake that `tzlocal` was ignoring erroneous arguments thus causing this confusion for you.

One other thing to note is that (at least in Python 3, I don't know about Python 2) `datetime.astimezone()` considers naive dates to be in local time, so if you want to assume that naive times are in local time, you can just convert the dates directly to any time zone you want, even if they have an attached time zone (e.g. `parse(dt_str).astimezone(tz.tzutc())` will just give you the time in UTC assuming naive times are local).

**Comment by cornelinux** [comment]
Hi @pganssle 
thanks a lot for this great explanation. So sorry for bothering you with this pebkac problem...
