### ISSUE TITLE
inconsistant behaviour of parse parameter dayfirst

### ISSUE THREAD

**Issue by cornelinux** [dateutil/dateutil#457]
I realized a change from version 2.5.1 to 2.5.2 in regards to ``parse`` and the parameter ``datefirst``.

In my application I have crappy legacy dates in the format:

  * 2017/04/01
  * 01/04/2017

Both meaning April 1st, 2017.

I am using this code:

<pre>
from dateutil.parser import parse

ts = "01/04/2017"
d = parse(ts, dayfirst=True)
print("{0!r}".format(d))

ts = "2017/04/01"
d = parse(ts, dayfirst=True)
print("{0!r}".format(d))
</pre>

From 2.4.2 to 2.5.1 this code will produce April 1st in both cases.
Starting with 2.5.2 it will create January 4th in the second case.

It looks like, the parameter ``dayfirst`` was ignored in version <=2.5.1 when parsing an American style date "2017/04/01" but is applied in newer version >=2.5.2.

Is this the intended behaviour? 
Is there a recommendation for dealing with this change from version 2.5.1 to 2.5.2?

**Comment by pganssle** [comment]
See #258 for the explanation of the current behavior. It did change and I didn't realize so many people were counting on the old (undocumented) behavior, but a broader change to how the parser handles things is needed.

See also #402 for the same issue, and #214 for a similar issue.

**Comment by cornelinux** [comment]
Thanks a lot.

As my years are 4 digits, I can know, that in case of "01/04/2017" or "01.04.2017" I have ``dayfirst`` but in case of "2017/04/01" I need ``dayfirst=False``.

A regular expression works for me:

    parse(ts, dayfirst=re.match("^\d\d[/\.]",ts))
