### ISSUE TITLE
rrule issue: 3rd thursday in month

### ISSUE THREAD

**Issue by nickos556** [dateutil/dateutil#46]
When I run the following code in dateutil 1.5, I get a different answer to dateutil 2.4:

In [1]: from dateutil.rrule import rrule, MONTHLY, TH
In [2]: from datetime import date, datetime
In [3]: r=rrule(MONTHLY, byweekday=TH(3), bymonth=(3,6,9,12), dtstart=datetime(2009,3,19))
In [4]: r.after(datetime(2015,3,1,12))

dateutil 1.5 gives: datetime.datetime(2015, 3, 19, 0, 0)
dateutil 2.4 gives: datetime.datetime(2015, 3, 5, 0, 0)

datetime(2015,3,5) is not the 3rd Thursday in March. datetime(2015,3,19) IS the third thursday. Any ideas what is going on?

**Comment by pganssle** [comment]
@nickos556 This issue was reported in Issue #34, which was fixed by PR #35. The fix is in the current stable branch, and will be included in a forthcoming 2.4.1 release (See PR #42)

**Comment by pganssle** [comment]
Duplicate.
