### ISSUE TITLE
License Mismatch with PyPi and Git Repo

### ISSUE THREAD

**Issue by anx-ckreuzberger** [dateutil/dateutil#464]
Hi there,

I was wondering what license this project is using, as the information is contradicting.

On PyPi it says
License: Simplified BSD (which would be the 2-clause BSD license)

The LICENSE file in your git repository suggests that it is a 3-clause BSD license.

Could you fix your setup.py such that it contains the correct license information?

**Comment by pganssle** [comment]
Good catch, @anx-ckreuzberger

I would assume that the LICENSE file is correct.
