### ISSUE TITLE
All years in the past

### ISSUE THREAD

**Issue by llostris** [dateutil/dateutil#465]
Currently the parser will parse two-digit year as being either in the 20th or 21st century
i.e. 
'17 Sept 23' - parsed as 2023-09-17 
'17 Sept 67' - parsed as 1967-09-17

Is there any way to  specify that I want all my 2-digit years to be in the past (so, at the beginning of our era)?

**Comment by pganssle** [comment]
See #84.

**Comment by pganssle** [comment]
(Note that that is closed as "wontfix" but the real solution is that we're trying to make the parser more configurable over time, which will make it easier to create such a toggle)
