### ISSUE TITLE
Author is wrong in setup.py

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#477]
Seems that for some time we've been listing the maintainer in the `author` field of setup.py, but there's a separate `maintainer` field for that.

Current author metadata should be moved to `maintainer`, and `author` should be restored to their original values ([here](https://github.com/dateutil/dateutil/commit/40996e01996096f252ef9d7754edf054e691900d#diff-2eeaed663bd0d25b7e608891384b7298L22)).

This is mostly a reminder to myself to do this, was thinking I'd do that and add a CONTRIBUTORS file as well, since the LICENSE should probably cover the contributors.

@niemeyer I'm assuming no objections to restoring your proper place in the metadata?

**Comment by hugovk** [comment]
It'd be good to add `url` so the homepage is easy to find from the PyPI page.

https://docs.python.org/2/distutils/setupscript.html#additional-meta-data

**Comment by pganssle** [comment]
@hugovk `url` is already there... [setup.py#L19](https://github.com/dateutil/dateutil/blob/410a534d8ce88d82ccf890d4dcd7faeccc167ade/setup.py#L19)

**Comment by hugovk** [comment]
And so it is! Sorry for the noise!

**Comment by jbrockmendel** [comment]
Related: are we actually still supporting 3.2 and 3.3?

**Comment by pganssle** [comment]
@jbrockmendel Yeah, it's in all the CI builds so it definitely works. I don't think there's a ton of impetus to move away from those versions at the moment, though I think there may be a few places here and there where we're doing something for Python 3.2 compatibility reasons.

**Comment by jbrockmendel** [comment]
OK.  I think in a recent PR I changed a `collections.callable(tzinfos)` to just `callable(tzinfos)`, which would break on some of the early 3.Xs.  I'll keep an eye out fo rthat.
