### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Skeen** [dateutil/dateutil#479]
Hello,

According to the METADATA information on the package;

    Metadata-Version: 2.0
    Name: python-dateutil
    Version: 2.6.1
    ...
    License: Simplified BSD

This software is released under the Simplified BSD license, also known as the '2-clause' BSD license.

However the [License file](https://github.com/dateutil/dateutil/blob/master/LICENSE) is the '3-clause' or 'Modified BSD License'.

Which license is the correct one?

**Comment by pganssle** [comment]
Already fixed in #466. I think generally I'd side with LICENSE in the future.

**Comment by pganssle** [comment]
Duplicate of #464.
