### ISSUE TITLE
Switch license to Apache 2.0 for all new work, add AUTHORS and CONTRIBUTING files

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#496]
I think that the Apache 2.0 license has some significant advantages over the BSD license, namely that patents are explicitly dealt with and clause 5 makes it explicit that contributions to the main repo will be licensed under Apache 2.0 *unless otherwise specified*. We still need to keep BSD license around for anyone who has not agreed to relicense, but since Apache and BSD are compatible, it's not a problem for all work going forward to be under the Apache 2.0 license.

As part of this, I think we should also add an `AUTHORS` file, so that the copyright notice is more accurate. I'll compile an `AUTHORS` file and it will be explicit who has their contributions licensed under the old BSD license and who has their contributions licensed under Apache 2.0, and any author on the list can make a PR to add themselves to the Apache 2.0 relicense file. If we get to 100%, we'll drop the old BSD file.

**Comment by pganssle** [comment]
I'm thinking possibly for the license switch, we're best off if the `LICENSE` file contains just the Apache 2.0 license, and we include a `licenses/` folder with the BSD license. I think we can treat all work subsequent to the license change as a derivative work of the old version that is licensed under Apache 2.0. Hopefully it won't be terribly confusing, and we can explain the license situation in the `README`.

The one thing I'm slightly concerned about is if this will cause headaches down the line as people may have to include multiple copyright notices just for incorporating `dateutil` into their product. It's *probably* fine, but there isn't a *huge* advantage to switching to Apache 2.0, particularly if we add a notice under `CONTRIBUTING.md` that explicitly says that all contributions will be assumed to be licensed under BSD.

A third option is to add a `Contributing.md` that says all contributions going forward will be assumed to be dual-licensed under BSD and Apache 2.0. We'll leave the main license of the project under BSD 3-clause because that's the most straightforward. If everyone on the AUTHORS list agrees to relicense under Apache 2.0, we can switch Apache 2.0 to the main license in the LICENSE file.

**Comment by jbrockmendel** [comment]
I'm way out of my depth on this one.  Wasn't there recently a license change PR?

**Comment by pganssle** [comment]
No, most certainly not. There was recently a change to the metadata to accurately reflect the existing license, but a proper license change can be quite complicated.

**Comment by jbrockmendel** [comment]
Got it, OK.  I'm going to default to staying out of this one; let me know if I can be helpful.

**Comment by pganssle** [comment]
Starting this out in #533. Will do the AUTHORS and LICENSE part soon.

**Comment by pganssle** [comment]
@jbrockmendel @jdufresne @mariocj89 @jarondl Are you guys willing to re-license your old contributions under a dual license between Apache 2.0 and the original BSD license? I'd like to have an initial list of relicensed contributors in the new `AUTHORS` file.

**Comment by jdufresne** [comment]
Yes. No problem here.

**Comment by mariocj89** [comment]
sure

**Comment by jbrockmendel** [comment]
OK

**Comment by pganssle** [comment]
This is more or less done.
