### ISSUE TITLE
pandas claim we broke the API

### ISSUE THREAD

**Issue by jarondl** [dateutil/dateutil#5]
Pandas claim we broke the API in 2.3,
see:  pydata/pandas#8639 pydata/pandas#9021 pydata/pandas#9036 pydata/pandas#9047
and: https://travis-ci.org/jreback/pandas/jobs/43281972
1. We should understand exactly what's broken. I am still not sure.
2. We should fix in the next release.
3. We should write specific tests to avoid this in the future

/CC @jreback @jlec @jorisvandenbossche

**Comment by pganssle** [comment]
@jarondl @jreback Is this fixed now somehow?

Linux:
```
[master@/home/.../dateutil/dateutil]$ python3.4 dateutil_test.py 
2.5.0
tzfile('/usr/share/zoneinfo/US/Eastern')
tzfile('America/New_York')
[master@/home/.../dateutil/dateutil]$ python2.7 dateutil_test.py 
2.5.0
tzfile('/usr/share/zoneinfo/US/Eastern')
tzfile('America/New_York')
[master@/home/.../dateutil/dateutil]$ 
```

Windows:
```
> python dateutil_test.py
2.5.0
tzfile('America/New_York')
tzfile('America/New_York')

>C:\Python27\python.exe dateutil_test.py
2.5.0
tzfile('America/New_York')
tzfile('America/New_York')
```

**Comment by jreback** [comment]
lgtm. I tried on 2.4.2.
