### ISSUE TITLE
Request the parser to stick to ISO 8601

### ISSUE THREAD

**Issue by konstantinmiller** [dateutil/dateutil#503]
Is it possible to request the parser to stick to ISO 8601 and throw an exception otherwise? That is, I would like to avoid guessing in case the input is ambiguous. I haven't found such a feature in the documentation.

**Comment by pganssle** [comment]
This is a feature under current development, targeted for the 2.7.0 release.

See PR #489, which fixes #424.

Feel free to pull that branch and start testing it yourself, I'm very interested in feedback from people who have this use case.
