### ISSUE TITLE
BLD: would be helpful to have a dev version number

### ISSUE THREAD

**Issue by jreback** [dateutil/dateutil#511]
e.g. current master is fixed at 2.6.1 (hard coded). maybe use https://github.com/warner/python-versioneer

IOW I was to have in tests ``LooseVersion(dateutil.__version__) > '2.6.1'`` but this is False (both on master and the released version), should be True on master.

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/issues/18141

**Comment by pganssle** [comment]
Agreed. Been meaning to set up some sort of automatic versioning for a while anyway. I'll take a look at versioneer when I get a moment.

**Comment by pganssle** [comment]
@jreback Partially solved by #518.

I'll leave this open because versioneer or something like it would be nice to have.
