### ISSUE TITLE
Appveyor (Windows) coverage not uploaded to codecov

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#520]
It seems that it is a known issue that codecov is not updated from Appveyor (which explains why we have pathetic coverage for the `tzwin` module and anything windows-related). See codecov/support#402. There seems to be some solution available, but the latest version of `codecov-python` does not have the fix.

Looks like in twisted/twisted#831 they pin to `codecov == 2.0.5`, though in the codecov issue a `codecov-exe` is mentioned. Shouldn't be terribly difficult to get it fixed, and that should give us a better idea of what needs to be done to get to 100% coverage.

**Comment by pganssle** [comment]
This may actually be done?

**Comment by pganssle** [comment]
For sprinters: The first item on the list is figuring out if this is actually done from the [codecov](https://codecov.io/gh/pganssle/dateutil). If it is we can close this issue.

**Comment by anthrotype** [comment]
it looks like the coverage reports _are_ being uploaded to codecov.io successfully.

See appveyor's log on the latest build from master (this is just py27, but the others are the same):
https://ci.appveyor.com/project/dateutil/dateutil/build/2.3.1406/job/otf53sc4o06a8tu4#L730

And in the codecov Uploads log page, the Appveyor builds seems to be all listed:
https://codecov.io/gh/dateutil/dateutil/commit/5e6f011c6d490ffc8842a2ea5363741b84766539/build

I think this can be closed.

**Comment by pganssle** [comment]
Thanks @anthrotype!
