### ISSUE TITLE
Recent python-dev mailing list discussions

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#530]
Not sure if any of these require action, but they may be worth noting somewhere:

https://mail.python.org/pipermail/python-dev/2017-October/149854.html
PEP 564: Add new time functions with nanosecond resolution
(i think this pep has been accepted, no idea what the implementation status is)

https://mail.python.org/pipermail/python-dev/2017-October/149983.html
iso8601 parsing

**Comment by pganssle** [comment]
The first one is just a `time` function, I don't think it has any immediate applicability here.

The second one also probably doesn't have much applicability. It's not a bad idea for them to have an inverse of `isoformat` in the standard library - that asymmetry is a huge annoyance. @mariocj89 has already ameliorated that problem somewhat by getting `strptime` to handle time zone offsets of the form `+HH:MM`, though I think the fact that `dateutil.isoparse` will infer any iso format automatically and will be backwards-compatible will probably make it useful even with a similar standard library function going forward.
