### ISSUE TITLE
Switch builds over to using tox

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#532]
The way I've got the builds in travis and appveyor set up is messing with the coverage metrics (see #528).

Given that we're already maintaining a `tox.ini` (which is not actually automatically tested, mind you!), it's probably a good idea to switch over the builds to use `tox`.

Rather than just have a single build that runs `tox`, it's probably best to use `tox -e <environment>` in the `script`. Once we're using tox, we can also add a `changedir` directive in the tox environments so that the tests are run against the installed version.

**Comment by gaborbernat** [comment]
Resolved by #549.
