### ISSUE TITLE
Add python_requires to setup.py

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#537]
Right now we're just using the trove classifiers, so I think people may end up doing some complicated pinning, which is less than ideal (see #536 and #526). What we need is the `Requires-Python:` metadata in pip. I think this is added through `setup.py`. Here are some examples of people using it:

- [pytest](https://github.com/pytest-dev/pytest/blob/master/setup.py#L86)
- [ipython](https://github.com/ipython/ipython/blob/master/setup.py#L235)

@carreau gave [this talk at PyBay](https://youtu.be/3i6n1RwqQCo?t=660) (link goes to the relevant time - 11 minutes in) where he discusses the `python_requires` option ([slides are here](https://speakerdeck.com/pybay/2017-building-bridges-stopping-python-2-without-damages)), probably best to listen to what he's talking about and avoid or document the pitfalls here.

**Comment by Carreau** [comment]
The python3statement's [practicalities](http://www.python3statement.org/practicalities/) page has a lot of useful informations in a more redable form; Including the case where Python-Requires fail and how to avoid issues. Let me know if the informations in this page are not clear enough.
