### ISSUE TITLE
Drop support for YYYYMM in isoparser 

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#546]
According to Wikipedia [YYYYMM](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates) is explicitly *not* supported in ISO-8601, so we should drop support for it. Hopefully this does not add undue complication into the algorithm.

See #489 for initial isoparse implementation.

**Comment by kirit93** [comment]
@pganssle has this issue been assigned or can I take a crack at it?

**Comment by pganssle** [comment]
@kirit93 During the sprint, @yoney said he was going to take a look at it this weekend, but I talked to him and he said you can go for it. Just mention it here if you end up not doing it.
