### ISSUE TITLE
Incorrect timezone during PDT -> PST Switch

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#57]
Migrated from launchpad issue [#1390262](https://bugs.launchpad.net/dateutil/+bug/1390262):

Quoting [Yupeng](https://launchpad.net/~liaoyupeng) on 2014-11-07:

    root@yupeng-desktop:~# date
    Sun Nov 2 01:43:42 PDT 2014
    root@yupeng-desktop:~# python
    Python 2.7.3 (default, Apr 10 2013, 06:20:15)
    [GCC 4.6.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from datetime import *
    >>> from dateutil.tz import *
    >>> datetime.now(tzlocal()).tzname()
    'PST'

**Comment by pganssle** [comment]
I've looked into this and tracked it down to the [tz.tzlocal.__isdst](https://github.com/dateutil/dateutil/blob/master/dateutil/tz.py#L128) function, and as far as I can tell, there is no good solution. The time "November 2, 2014, 1:00 AM Pacific" is an ambiguous representation and apparently defaults to the PST side.

I think that the best thing to do, moving forward, is to get a good sense of where the ambiguity can be alleviated and either document the right way to deal with it or provide additional methods/functions that can help with that. For example, if you just want to know the *current* local time zone, `utcnow()` should be able to pretty unambiguously tell you what the current time it is, and you can localize based on that. The problem is that `__isdst` operates on any datetime, and datetime objects without time zones are inherently ambiguous around DST transitions.

**Comment by zed** [comment]
@pganssle : there is no ambiguity here. `.now(tz)` uses `tz.fromutc()` and `utcnow()` (or equivalent) already e.g., [`datetime.now(pytz_timezone)` always works](http://stackoverflow.com/q/31886808/4279).

**Comment by pganssle** [comment]
@zed It is certainly true that "November 2, 2014, 1:00 AM Pacific" is an ambiguous time:

```python
>>> pytz.timezone("America/Los_Angeles").utcoffset(datetime.datetime(2014, 11, 2, 1, 0))

pytz\tzinfo.pyc in utcoffset(self, dt, is_dst)
    406             return None
    407         elif dt.tzinfo is not self:
--> 408             dt = self.localize(dt, is_dst)
    409             return dt.tzinfo._utcoffset
    410         else:

pytz\tzinfo.pyc in localize(self, dt, is_dst)
    347         # ambiguous case
    348         if is_dst is None:
--> 349             raise AmbiguousTimeError(dt)
    350
    351         # Filter out the possiblilities that don't match the requested

AmbiguousTimeError: 2014-11-02 01:00:00
```
The reason that `.utcnow()` works is because it retrieves the *current* time in UTC. The issue is that `tzlocal()` doesn't know that the time you're trying to parse is the current time - even if it happens to match the current time's signature, the current time's signature, without a time zone, is ambiguous during the DST transition.

That said, we may well be able to do this better by overloading `fromutc()`, but `pytz` has no way of knowing what your local time zone is, and figuring out what your *actual* local time zone is (as opposed to inferring the current time zone from the values returned by `time` - which is what causes the ambiguity) is actually a bit more complicated than what we're doing here. It's worth looking into, but I am convinced that it's not trivial to fix.

**Comment by zed** [comment]
I don't see what `tz.utcoffset(fixed_naive_dt)` has to do with `datetime.now(tzlocal())`. 

**It is always possible to get the current time as an aware datetime object**: even during DST transitions. `pytz` demonstrates that.

> but pytz has no way of knowing what your local time zone is

`tzlocal.get_localzone()` returns the local timezone as `pytz` tzinfo object.

**Comment by pganssle** [comment]
@zed Yes, tzlocal is a different module from pytz, though, and what it does is figure out what time zone your system is in, then takes the current UTC time and gives you the time in the system time zone. This is a little different from what `tz.tzlocal()` does.

Arguably, we should be duplicating the functionality of the `tzlocal` module, but if you actually take a look at `tzlocal`, you'll see it's not exactly a trivial undertaking (as I said above).

Of course, apparently per #112, we're not even getting it right even when we *know* the time zone we're in, but I suspect that if we fix #112, it still won't fix this issue.

**Comment by abalkin** [comment]
I would like to mention a [mini-project](https://github.com/abalkin/tz) that I started to implement a simple PEP 495 compliant timezone library.  Since PEP 495 implementation has not been merged yet, I wrote my code in a way that it works with Python 3.5.

As you can see below, my implementation does not suffer from this issue's bug:

```
>>> from datetime import *
>>> import tz
>>> hour = timedelta(hours=1)
>>> LA = tz.ZoneInfo.fromname('US/Pacific')
>>> t = datetime(2014, 11, 2, 1, tzinfo=LA)
>>> u = t.astimezone(timezone.utc)
>>> print(t)
2014-11-02 01:00:00-07:00
>>> print((u + hour).astimezone(LA))
2014-11-02 01:00:00-08:00
```

The disambiguation between 2014-11-02 01:00:00 PDT and 2014-11-02 01:00:00 PST is achieved by returning an instance of an auxiliary datetime subclass for the times in a fold:

```
>>> s = (u + hour).astimezone(LA)
>>> s
_DatetimeWithFold(2014, 11, 2, 1, 0, tzinfo=<tz.ZoneInfo object at 0x1046b5748>)
```
Such instances have the fold attribute which is set to 1: 
```
>>> s.fold
1
```

Starting with Python 3.6, the additional class will not be necessary and my code is written to automatically switch to using plain datetime type once it grows the fold attribute.

If you agree that this is the right approach, I can prepare a patch for distutil similar to #127 but compatible with pre-PEP 495 Python versions.

**Comment by pganssle** [comment]
@abalkin That's clever. I'll have to think about it. It's probably the Right thing to Do (TM), but I think most people are not expecting `astimezone()` to return anything but a `datetime` object. I'm having trouble imagining a situation where it would be a major issue, but I'm still a bit uneasy about violating that assumption.

I haven't looked into it much, but what about implementing PEP-495 `datetime` objects as a backport under the `backports` module? I think we could discontinue support for Python 2.6 and recommend using `backports.datetime` to represent ambiguous times if we got a backport for 2.7 and 3.3+.

**Comment by pganssle** [comment]
Oh, also, this issue was closed by #264.

**Comment by abalkin** [comment]
I was hoping that you would reconsider #264.  The problem with that solution is that it violates the fundamental invariant:  t.astimezone(tz) is tz:
```python
>>> dateutil.__version__
'2.6.0a0'
>>> LA = dateutil.tz.gettz('US/Pacific')
>>> u = datetime.now(timezone.utc)
>>> u.astimezone(LA).tzinfo is LA
False
```
Furthermore, it is incompatible with PEP 495 which treats repeated times as equal 

```python
>>> u = datetime(2014, 11, 2, 8, tzinfo=timezone.utc)
>>> t0 = u.astimezone(LA)
>>> t1 = (u + timedelta(hours=1)).astimezone(LA)
>>> t0 == t1
False
```
One may think the #264 behavior is better than PEP 495, but it is really not.  Consider, for example
```
>>> t0 + timedelta(hours=1) == t1
False
```

It seems to me that your solution is somewhere in between of the pytz and PEP 495 approaches.  It would be really unfortunate to have three slightly incompatible solutions to the same problem going forward.

With respect to  PEP-495 datetime objects as a backport, this is a possibility, but I think it is an overkill for the purposes of just fixing this dateutil bug.  I think most people would prefer using dateutil with the official datetime module.

In any case, assuming a backport of PEP 495 or Python 3.6 datetime module is available, how should dateutil use it?  Would you really want to change program behavior depending on whether  PEP 495 implementation is available?

**Comment by pganssle** [comment]
@abalkin I haven't in any way foreclosed the idea of reconsidering #264. The need to compromise in this way is unfortunate.

In the end, my plan is to have the `tzinfo` object fall back to the `datetime`'s `fold` attribute whenever possible. I don't think the current implementation does that quite correctly, but given that there is no final PEP-495 implementation yet I figured I would re-assess the situation when I had something stable to build against.

Regarding 
```python
>>> t0 + timedelta(hours=1) == t1
False
```
I don't understand what you're trying to say with this. From my understanding of datetime arithmetic, this is the *expected* behavior - datetimes are a 7-handed clock and timedeltas are intended to move the hands of the clock around. 2 AM is a different time than second-1AM.

>In any case, assuming a backport of PEP 495 or Python 3.6 datetime module is available, how should dateutil use it? Would you really want to change program behavior depending on whether PEP 495 implementation is available?

My philosophy on this is that it's OK for the behavior to be a little weird when using a non-PEP 495 `datetime` as long as it works as expected when PEP 495 is implemented. The whole point of PEP 495 is to fix these sorts of ambiguities, so it's not unreasonable to say that if you're not using a version with PEP-495 implemented, you're going to have ambiguous behavior. The reason I'd like a `datetime` backport is that I could then assume all users have the *option* to use the consistent behavior if they care about it. I'm willing to be convinced otherwise, though.

A `datetime` backport would also solve another issue that I've been grappling with, which is that even post- #264, there's no simple way to construct an ambiguous `datetime` other than by converting it from another timezone-aware datetime. `pytz` has a distinct advantage here because you can specify the dst behavior in the `localize` function.

It seems to me that there are three ways to get around this:

1. expose the "dst preference" on the `tzinfo` object,
2. use a localizer-function like `pytz` is doing or
3. use a `datetime` that has the `fold` attribute. If I knew a backport of `datetime` were available, I could say to end users, "If you want consistent behavior around DST, and if you want to be able to construct ambiguous datetimes, use 3.6 or use the backport", then `dateutil` doesn't have to muck around with some hacked-together interface for generating ambiguous datetimes.

**Comment by abalkin** [comment]
>  given that there is no final PEP-495 implementation yet

There is: http://bugs.python.org/issue24773

I've been waiting for more reviews, but will probably commit this patch today.

**Comment by pganssle** [comment]
Oh, also, I think it's a simple matter to adjust the `tzinfo` objects so that `_fold` is ignored when making comparisons, but two times representing two different timestamps comparing equal sounds like it's going to cause a lot of confusion in the future. Still, for the sake of consistency that seems OK to me.

**Comment by abalkin** [comment]
@pganssle - I would appreciate if you could take a look at [abalkin/tz](https://github.com/abalkin/tz) and try to come up with use cases where the code using my `tz.ZoneInfo` would behave differently in Python 3.5 and 3.6.

Note that `_DatetimeWithFold` returned by `fromutc()` is simply

```
    class _DatetimeWithFold(datetime):
        __slots__ = ()

        @property
        def fold(self):
            return 1
```

The only issue I can think of so far is the need to override the a few methods such as `replace` that currently return the subclass, but should return the basic datetime.

Other than that, it looks like with my approach it is fairly easy to write fully backward compatible code: just use `getattr(t, 'fold', 0)` instead of `t.fold` and `tz.enfold(t, x)` instead of `t.replace(fold=x)`.

> two times representing two different timestamps comparing equal sounds like it's going to cause a lot of confusion in the future.

This and several related issues were extensively discussed when PEP 495 was developed.  We struck a careful balance between intuitiveness and backward compatibility.  Time will tell whether  we fully succeeded, but now, almost a year after the PEP was accepted and less than two months before Python 3.6 beta, it is too late to make any changes to the PEP.

**Comment by pganssle** [comment]
@abalkin I have been meaning to download your PEP495 implementation fork, I'll try to get to that this week. Here's one where I suspect there might be a difference between Python 3.5 and Python 3.6:

```python
from datetime import datetime, timedelta, timezone
from tz import ZoneInfo

LA = ZoneInfo.fromname('US/Pacific')
t = datetime(2014, 11, 2, 1, tzinfo=LA)
s = (t.astimezone(timezone.utc) + timedelta(hours=1)).astimezone(LA)

print(s)
# 2014-11-02 01:00:00-08:00

print(s + timedelta(minutes=30))
# 2014-11-02 01:30:00-07:00
```

Also, I think I was a bit confused about which side was the "fold". This causes some minor problems with `dateutil` because we've *always* resolved folds in favor of the *second* date. I did not realize that `fold` logic is inverted from this. My idea of the metaphor was that if you fold over a piece of paper, the part on the *inside* is "in the fold" and the part on the outside is not. Obviously, like the equality thing, it's a bit late to change this now, but it's possible that making `dateutil` PEP495-compatible across versions might be a breaking change.

FYI, this `timedelta` behavior seems to work OK with `dateutil` version `2.6.0a`:

```python
from datetime import datetime, timedelta, timezone
from dateutil.tz import gettz

def absolutedelta(dt, td):
    tzinfo = dt.tzinfo
    if tzinfo is None:
        return dt + td
    else:
        dt = (dt.astimezone(timezone.utc) + timedelta(hours=1))
        return dt.astimezone(tzinfo)

LA = gettz('US/Pacific')
t = absolutedelta(datetime(2014, 11, 2, 0, tzinfo=LA), timedelta(hours=1))
s = absolutedelta(t, timedelta(hours=1))

print(s)
# 2014-11-02 01:00:00-08:00

print(s + timedelta(minutes=30))
# 2014-11-02 01:30:00-08:00
```

**Comment by abalkin** [comment]
@pganssle - PEP 495 implementation has been merged in the default 3.6 branch.  You can start testing against it by adding "nightely" to the python versions list in your .travis.yml.

**Comment by abalkin** [comment]
> Here's one where I suspect there might be a difference between Python 3.5 and Python 3.6

@pganssle - I ran your code under Python 3.5.2 and 3.6.0a3+ (default:a290f992e69a+).  The later includes the PEP 495 patch.  The results were identical but different from what you indicated in your comments:

```
2014-11-02 01:00:00-08:00
2014-11-02 01:30:00-07:00
```

(note the TZ offset in the second line)

**Comment by pganssle** [comment]
@abalkin  Hmm.. this part of PEP495 will, I'm sure, generate bug reports:

> The value of fold will also be ignored whenever a timedelta is added to or subtracted from a datetime instance which may be either aware or naive. The result of addition (subtraction) of a timedelta to (from) a datetime will always have fold set to 0 even if the original datetime instance had `fold=1`.

I suppose I was worried about counter-intuitive behavior with your implementation, but I guess all that counter-intuitive behavior is *part of the spec*. I do wish I had understood these issues better when they were being discussed. I've only had time to read the first 10-15 posts in the datetime-SIG threads that decided this.

Anyway, I'm coming around to your way of thinking on this matter. If you want to make a PR to adjust the `_fold` behavior of `_tzinfo` to return a `_Datetimewithfold`, I'll accept it. That said, I do have the sense of `_fold` inverted, so I'll have to go through and fix that in all the `tzinfo` classes. It may be better to just have me do it.

That said, I'm still in favor of a backport of `datetime` with the `fold` attribute. This would greatly simplify the construction of ambiguous datetimes.
