### ISSUE TITLE
Options Object

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#576]
I've got mixed thoughts on this, want to put it out there for discussion.

There are a bunch of GH issues regarding parsing that don't appear to have a clear "fix the parser" solution, require some type of user option.  A small amount of **kwarg proliferation is inevitable.  The suggestion here is to put these all into a `ParseOptions` class (or possibly private internal version thereof).  Three reasons:

1) Persistence.  Specify all your kwargs once and then pass the `opt = ParseOptions(...)` object on subsequent calls to `parse`.
1a) Possibly check for environment variables in case users want to do the "separation of code and config" thing.

2) Validation.  If there is kwarg proliferation, there are likely to be `if dayfirst and yearfirst: raise` type validations to be done.  This dove-tails into 1) if any of these are at all costly, doing them once instead of on each call to `parse` would be nice.

3) One object to pass around to internal methods.  Just a matter of convenience, if any of these kwargs become needed in `_parse` or `_could_be_tzname` or ... it'd be nice to have a single arg instead of a whole mess of them.

**Comment by jbrockmendel** [comment]
Then again, 3) could be addressed by just lumping things into a dict if that really becomes an issue.

**Comment by pganssle** [comment]
How is this different from `parserinfo`, which is basically an options class?

Either way, I think it's putting the cart before the horse. I don't foresee any significant kwarg proliferation because any future API changes we introduce to the parser will be well thought-out. An options object is not particularly out of the question, but I'm not interested in creating some pandas-like monstrosity of interacting keyword arguments.

**Comment by jbrockmendel** [comment]
> How is this different from parserinfo, which is basically an options class?

AFAICT the point of parserinfo is for subclassing to override e.g [Monday, Tuesday...].  That's distinct from being a container for runtime arguments.  It could serve both roles I guess.  But I think the more pertinent point is ...

> think it's putting the cart before the horse.

Fair enough.  Closing.
