### ISSUE TITLE
Add changelog management

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#592]
Possibly we should use [towncrier](https://pypi.python.org/pypi/towncrier) for this?

Manually updating all the changelogs and such is kind of a pain at the end of each release cycle. This could make things much easier.

**Comment by wagner-certat** [comment]
> Possibly we should use towncrier for this?

As far as I understood the readme correctly, it creates a news-file (for users) from an existing changelog (for developers), where the changelog needs to have a very special format. Not sure, if this really helps you.

**Comment by pganssle** [comment]
> As far as I understood the readme correctly, it creates a news-file (for users) from an existing changelog (for developers), where the changelog needs to have a very special format. Not sure, if this really helps you.

The way it would help is that each PR would require a news entry (which I could detect in the CI), and when I do a release it would be a matter of executing `towncrier` rather than manually going through all the old PRs and issues and seeing who reported them and who fixed them, etc. Just having the work done "as you go" is helpful.

The value of doing it with `towncrier` or some equivalent software is to avoid merge conflicts on the single `NEWS` file.

**Comment by wagner-certat** [comment]
I saw the same approach in https://github.com/xonsh/xonsh though they use their own script to merge the single files in the directory. towncrier also handles different classes of changes, that's for sure a plus.
