### ISSUE TITLE
setup.py should require six at least version 1.5 

### ISSUE THREAD

**Issue by ccanepa** [dateutil/dateutil#6]
after installation with python setup.py install , in python 2.7, tests failed to run with message related to _thread

dateutil.rrule does 
from six.moves import _thread

but six version needs to be at least 1.5 for that 

Defect seen in dateutil v2.3 and master b2615c76fec from Tue Dec 9 21:42:17 2014 +0200

EDIT: I was at six vs 1.2 before, updated to latest in pypi, vs 1.8  ATM. 
I don't tested versions in ´´´1.5 <= vs < 1.8´´´ so it is possible that other features need a higher version than 1.5; 1.5 is the minimal to solve the _thread traceback.

**Comment by jdufresne** [comment]
Thanks for the fix.

Any chance there could be a point release with this included?

**Comment by hanbeibei** [comment]
Hi
I'm using thest command: 
sudo pip install --upgrade dateutils

and get related log as follow:
Requirement already up-to-date: dateutils in /Library/Python/2.7/site-packages
Requirement already up-to-date: argparse in /Library/Python/2.7/site-packages (from dateutils)
Requirement already up-to-date: python-dateutil in /Library/Python/2.7/site-packages (from dateutils)
Requirement already up-to-date: pytz in /Library/Python/2.7/site-packages (from dateutils)
Requirement already up-to-date: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->dateutils)

but still get error message as described on #12 

any help?

**Comment by hanbeibei** [comment]
the fixed method is here:

http://stackoverflow.com/questions/27630114/matplotlib-issue-on-os-x-importerror-cannot-import-name-thread

Please ignore my comment, sorry..
