### ISSUE TITLE
Break up unit tests by module

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#61]
I'm thinking that, given the ever-growing number of unit tests, it seems like it might be better to split "tests.py" into "test_rrule.py", "test_parser.py", etc, to more cleanly delineate between the testing modules, and make it easier for people to add new tests with their PRs.

I can do this, but I just thought I'd open an issue first to see if there's any obvious reason why not.

**Comment by AndrewPashkin** [comment]
I noticed that there is a lot of similar tests, like here:
https://github.com/dateutil/dateutil/blob/5415505dba36b71836c05b28279c6e67f15b7977/dateutil/test/test.py#L3268

They can be refactored using parametrized tests, in such fashion:
https://pytest.org/latest/parametrize.html
