### ISSUE TITLE
Documentation unclear about relativedelta

### ISSUE THREAD

**Issue by woutervisee** [dateutil/dateutil#631]
Docs here:
http://dateutil.readthedocs.io/en/latest/relativedelta.html

Have this to say:

    >Absolute information (argument is singular); adding or subtracting a
    >relativedelta with absolute information does not perform an arithmetic
    >operation, but rather REPLACES the corresponding value in the
    >original datetime with the value(s) in relativedelta.

What does that mean? How does adding a delta replace the value? And if the original datetime-boject is changed, how does that happen? That means a+b changes a, is that correct? From looking at how this function is used (https://stackoverflow.com/questions/4130922/how-to-increment-datetime-by-custom-months-in-python-without-using-library, answer by Atul) this function does not match what the documentation says it does.

**Comment by pganssle** [comment]
@woutervisee I think it's pretty clear, but fundamentally this class is designed in a confusing way, not much can be done about it in the documentation. The documentation you link to actually does make clear both how it works and which ones are absolute and which are relative. There is even an example of each:

Relative:

```python
>>> NOW+relativedelta(years=+1, months=-1)
datetime.datetime(2004, 8, 17, 20, 54, 47, 282310)
```

Absolute:

```python
>>> NOW+relativedelta(year=1, month=1)
datetime.datetime(1, 1, 17, 20, 54, 47, 282310)
```

If you or someone else comes up with a better way to very clearly demonstrate this to people reading the documentation that is better than what we have now, I'd be happy to look at a PR.
