### ISSUE TITLE
InvalidOperation ConversionSyntax after replacing float with Decimal (Refs #570)

### ISSUE THREAD

**Issue by amureki** [dateutil/dateutil#632]
Hey there,
Thanks for a great package!

We encountered an issue with 2.7.0 release and exactly this change (float to Decimal):
https://github.com/dateutil/dateutil/pull/570/files#diff-4b65e7edb2b73639d2d3360fa8d05343R937

Before release it was float and producing `ValueError`:
```
>>> float('TEST')
ValueError: could not convert string to float: 'TEST'
```
After release, same operation goes with `Decimal`, which produces a different error:
```
>>> Decimal('TEST')
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

I am not 100% familiar with `dateutil` code, but I see, that `ValueError` was covered in `dateutil.parser._parser.parser#_parse` here: https://github.com/dateutil/dateutil/blob/master/dateutil/parser/_parser.py#L689-L825

But now that piece is raising `decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]` which is not covered at all and breaking the code, that uses it.

What shall we do in that case? Shall we wrap it in `try/except` like it says in leftovers `TODO` comment?

My environment (just in case):
```
>>> import dateutil; print(dateutil.__version__)
2.7.0

13:16 $ python --version
Python 3.6.4
```

**Upd.** Code example with failing parser:

```
>dateutil.parser.parse('1: test')
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

>dateutil.parser.parse('9999: 12, test')
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by pganssle** [comment]
I believe this is a bug. I would add this decimal exception to your exception catching logic until it is fixed.


Luckily it seems like a reasonably easy fix.

**Comment by amureki** [comment]
@pganssle thank you for a fast reply.

We are freezing library to `2.6.1` for now.
I can try to take a look at some spare time and provide a PR for this bug.
But if someone else could take care of it, feel free to go!

**Comment by pganssle** [comment]
Can you provide some strings that recreate this error? I think that would help speed things along.

**Comment by amureki** [comment]
@pganssle I am not sure I can imagine other cases (at least for our purposes). All those are failing is just any strings (like the example I provided in the first message), which are raising a `decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]`

So, I guess, that would be the only different case here.

**Comment by pganssle** [comment]
@amureki I mean what do I pass to `dateutil.parser.parse` that will cause an error?

**Comment by amureki** [comment]
@pganssle ah, I am sorry, did not provide an example for `parse` itself.

Adding it here also will update the first message with it:
```
>dateutil.parser.parse('1: test')
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

>dateutil.parser.parse('9999: 12, test')
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by pganssle** [comment]
@amureki Thanks, perfect.

**Comment by amureki** [comment]
@pganssle thank you for covering this so fast!
Amazing work! <3
