### ISSUE TITLE
No documentation for gettz

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#647]
Currently there is no documentation for `gettz`, which is the primary interface through which one gets Olson database zones.

Some prior art that should be cobbled together to make real documentation:

- [Here are some slides about gettz](https://pganssle.github.io/pygotham-2016-dateutil-talk/#/4/3) - [video here](https://youtu.be/X_bCto95Imc?t=20m25s) (audio is messed up)
- [Here is the actual implementation](https://github.com/dateutil/dateutil/blob/master/dateutil/tz/tz.py#L1431)

Unfortunately not a whole lot to go on.

**Comment by weatherpattern** [comment]
I know that @caseyclements claimed this issued, but I was playing around with it, and the docstring in the gettz method wouldn't show when I tried making the docs.
But I was able to make it appear in a new function I created in the tzutc() class, as seenin this branch is my fork [line 70](https://github.com/weatherpattern/dateutil/blob/WIP-gettz-documentation/dateutil/tz/tz.py).

Also, I don't understand why the __get_gettz() method is structured the way it is. Maybe that is related? 

Am I missing something on how sphinx works? Is there a way to programmatically force a docstring to print?

**Comment by pganssle** [comment]
`__get_gettz()` is structured the way it is because I don't want `GettzFunc` to be a public class, so I preferred to define it in a closure in a private function called once.

The problem seems to be with in the `automodule` directive of [`docs/tz.rst`](https://raw.githubusercontent.com/dateutil/dateutil/master/docs/tz.rst). I'm not sure why exactly, but it seems that `gettz` is not being considered a "member" even though it is in `dateutil.tz.__all__`. If you explicitly add it:

```rst
==
tz
==
.. automodule:: dateutil.tz
   :members:
   :undoc-members:

   .. automethod:: dateutil.tz.gettz
```

It will pick up the docstring from `GettzFunc`.

That said, other than manually writing docs for the full public API of `gettz` into `GettzFunc`, I don't know if there's an easy way to include the members of the `gettz` object, like `nocache` and `clear_cache`. We can figure that out later.

**Comment by caseyclements** [comment]
Hey guys. I claimed this during a PyData Meetup sprint, and planned to finish it in my free time, but @weatherpattern, if you're finish it, that's great.
