### ISSUE TITLE
relativedelta division

### ISSUE THREAD

**Issue by MareinK** [dateutil/dateutil#660]
In `datetime`, it is possible to divide two `timedelta`s:

```python
import datetime
print(datetime.timedelta(1) / datetime.timedelta(2))  # output: 05
```

However the same is not possible in `dateutil` with `relativedelta`:

```python
import dateutil.relativedelta
dateutil.relativedelta.relativedelta(days=1) / dateutil.relativedelta.relativedelta(days=2)
# TypeError: unsupported operand type(s) for /: 'relativedelta' and 'relativedelta'
```

I feel it would be good to include this functionality in `dateutil`. I know it would not make sense in some cases but I feel in many it would. Thoughts?

**Comment by jbrockmendel** [comment]
I think this was discussed in a PR a while back and ultimately special-casing was rejected.  If you have a case where division makes sense, why not just use a timedelta?

**Comment by pganssle** [comment]
I think the reasoning laid out in #350 applies here. The division operation will likely be meaningful for `calendardelta` (see #524), but it is not particularly meaningful for `relativedelta`.
