### ISSUE TITLE
Exercise: Martin Luther King day

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#664]
This is an example exercise to be solved by a new user to the library *using only the dateutil documentation*, per #663.

# Exercise: Martin Luther King, Jr Day
> [Martin Luther King, Jr Day](https://en.wikipedia.org/wiki/Martin_Luther_King_Jr._Day) is a US holiday that occurs every year on the third Monday in January.
>
> How would you generate a [recurrence rule](https://dateutil.readthedocs.io/en/latest/rrule.html) that generates Martin Luther King Day, starting from the first observance of the holiday in 1986?

### Test cases:
```python
from datetime import datetime

MLK_TEST_CASES = [
    ((datetime(1970, 1, 1), datetime(1980, 1, 1)),
     []),
    ((datetime(1980, 1, 1), datetime(1989, 1, 1)),
     [datetime(1986, 1, 20),
      datetime(1987, 1, 19),
      datetime(1988, 1, 18)]),
    ((datetime(2017, 2, 1), datetime(2022, 2, 1)),
     [datetime(2018, 1, 15, 0, 0),
      datetime(2019, 1, 21, 0, 0),
      datetime(2020, 1, 20, 0, 0),
      datetime(2021, 1, 18, 0, 0),
      datetime(2022, 1, 17, 0, 0)]
     ),
]


def test_mlk_day(rr):
    for (between_args, expected) in MLK_TEST_CASES:
        assert rr.between(*between_args) == expected
```

To Do:

- [x] Add this exercise to the documentation
- [ ] Add solution to the documentation
- [x] Improve documentation for `rrule` based on this

**Comment by kvn219** [comment]
Hi.

Here is my solution!

```python
def mlk(*dates):
    first_mlk_day = datetime(1986, 1, 20)
    start, end = dates
    if end < start:
        return None
    elif start < first_mlk_day:
        start = first_mlk_day
    yearly_mlk_dates = list(rrule(YEARLY, bymonth=1, byweekday=MO(3), dtstart=start, until=end))
    return yearly_mlk_dates
```

**Comment by rmahajan14** [comment]
start_date = datetime(1986, 1, 1)  
rr = rrule(YEARLY, byweekday=(MO(3)),
                dtstart=start_date)

**Comment by rmahajan14** [comment]
```
start_date = datetime(1986, 1, 1)  
rr = rrule(YEARLY, byweekday=(MO(3)),
           dtstart=start_date)
```

**Comment by ChHeYo** [comment]
```
start_date = datetime(1986, 1, 1)  
rr = rrule(YEARLY, byweekday=(MO(3)),
           dtstart=start_date)
```

**Comment by pganssle** [comment]
@ChHeYo @rmahajan14 @kvn219 Was there anything confusing in the documentation that hindered your ability to figure out this exercise?
