### ISSUE TITLE
2.4.1 PyPi

### ISSUE THREAD

**Issue by monocult** [dateutil/dateutil#67]
Hey Guys,
please put version 2.4.1 back on pypi. At the moment there a lot of broken dependencies out there. 
thx.

**Comment by papachoco** [comment]
Ditto this

**Comment by Jyggafey** [comment]
+1

**Comment by pganssle** [comment]
Whoa, sorry about this - I was forced to rename the file when I uploaded a version that included the test suite. I didn't want to change the version number - I'm guessing they keep track of the hash and when the hash changed they wanted to enforce a version change.

Unfortunately, I'm not sure I actually *have* the old source distributions. Let me see what I can do.

**Comment by pganssle** [comment]
For the moment I was able to put a `.tar.bz2` distribution up there. I'm trying to track down if the old one got mirrored.

@monocult @papachoco @Jyggafey - Does this work for your applications? Also, if any of you happen to have the old .tar.gz (with signature would be ideal) and/or .zip file, please let me know.

@idella Maybe you have the old tarball?

**Comment by Jyggafey** [comment]
works for me, thank you!
Sadly, i can provide neither tar.gz nor zip.

**Comment by idella** [comment]
@pganssle  eeeer yes. You mean the initial one missing the tests?  Iy has been saved in my system.  Do you want it?  (I could see re-uploading to the same name would 'kick back')

**Comment by pganssle** [comment]
@idella Yes, the ones with the tests missing should have a matching md5. I'd rather have them up there than not, even though the .tar.bz2 seems to have alleviated the problem. That said, I'm not sure that PyPi will accept them even if they *do* have a matching hash, but it's worth a try.

If you can, send them to me at p.ganssle@gmail.com.

**Comment by tdsmith** [comment]
If you repack a release and don't want to bump the version number, you can consider using `.post` version suffixes described in PEP 440: https://www.python.org/dev/peps/pep-0440/#post-releases.

**Comment by pganssle** [comment]
@tdsmith Oh, perfect! That seems like a much better resolution. Everything should be now working as desired. Thanks much, sorry for the confusion everyone!
