### ISSUE TITLE
Wrong link syntax in relativedelta examples

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#670]
I noticed that in the [relativedelta examples](https://dateutil.readthedocs.io/en/latest/relativedelta.html#examples) there is a link using the wrong syntax for RST, so it's not getting turned into a link.

The issue is [this line](https://github.com/dateutil/dateutil/blame/master/docs/relativedelta.rst#L143), which currently reads:

> [http://www.cl.cam.ac.uk/~mgk25/iso-time.html ISO year week number notation]

But should read:

> [ISO year week number notation](http://www.cl.cam.ac.uk/~mgk25/iso-time.html)

It needs to be turned into RST syntax, which is I think:

```rst
`ISO year week number notation <http://www.cl.cam.ac.uk/~mgk25/iso-time.html>`_
```

**Comment by ParseThis** [comment]
I was looking around for a way to build the docs locally. Advice? I would clean up as many of these as possible but dont want to push and test.

**Comment by pganssle** [comment]
`tox -e docs` will build the docs with all the tests. You can find the output in `.tox/docs_out`.

You can also enter the `docs` folder and type `make html`, then the output will be built in the `_build`.

I think I would prefer the inline syntax mentioned in my original post:

```rst
`ISO year week number notation <http://www.cl.cam.ac.uk/~mgk25/iso-time.html>`_
```

**Comment by pganssle** [comment]
Just noticed another minor typo that can be fixed at the same time. The `tzfile` documentation reads: "This is a tzinfo subclass **thant** allows one to". Obviously that needs `s/thant/that`
