### ISSUE TITLE
rrulestr Generates Datetime with Incorrect Daylight Savings Value

### ISSUE THREAD

**Issue by DavidMuller** [dateutil/dateutil#72]
I'm using the dateutil 2.4.2 and encountering the following error using `rrulestr`:

```python
import pytz
from datetime import datetime
from dateutil.rrule import rrulestr

pacific_tz = pytz.timezone('America/Los_Angeles')
rrule_string = 'RRULE:FREQ=WEEKLY;COUNT=2;BYDAY=MO'
dt_start = pacific_tz.localize(datetime(2014, 10, 27, 9, 0))
```
 `list(rrulestr(rrule_string, dtstart=dt_start))` outputs the following:
```python
datetime.datetime(2014, 10, 27, 9, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PDT-1 day, 17:00:00 DST>), 
datetime.datetime(2014, 11, 3, 9, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PDT-1 day, 17:00:00 DST>)]
```

The second datetime is incorrect:

`datetime.datetime(2014, 11, 3, 9, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PDT-1 day, 17:00:00 DST>)` --> November 3rd 9AM should not be in DST.

The *correct* datetime would be:
```python
pytz.timezone('America/Los_Angeles').localize(datetime(2014, 11, 3, 9, 0))
datetime.datetime(2014, 11, 3, 9, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PST-1 day, 16:00:00 STD>)

```

**Comment by pganssle** [comment]
@DavidMuller I suspect that either you are using pytz incorrectly or this is a bug in pytz.  Note I can reproduce the bug without using anything from dateutil:

```python
    >>> from datetime import datetime, timedelta
    >>> from pytz import timezone

    >>> pacific_tz = timezone('America/Los_Angeles')
    >>> toff = timedelta(days=7)
    >>> dtstart = pacific_tz.localize(datetime(2014, 10, 27, 9, 0))
    >>> dtstart.tzname()
    'PDT'
    >>> (dtstart + toff).tzname()
    'PDT'
```
Using `dateutil.tz`:

```python
    >>> from datetime import datetime, timedelta
    >>> from dateutil.tz import gettz
    
    >>> pacific_tz = gettz('America/Los_Angeles')
    >>> toff = timedelta(days=7)
    >>> dtstart = datetime(2014, 10, 27, 9, 0, tzinfo=pacific_tz)
    >>> dtstart.tzname()
    'PDT'
    >>> (dtstart + toff).tzname()
    'PST'
```

I am no expert in pytz, but I believe the reason for the difference is that `localize()` is attaching a fixed time zone (PDT) based on the local time of `dtstart`, whereas the `tzfile()` returned by `gettz` is calculating the local time zone on request for each date. I suspect that if you want to use the `.localize()` method, you have to call it on the output of the `rrule`, not the input, e.g.:

```python
    >>> from datetime import datetime, timedelta
    >>> from dateutil import rrule
    >>> from pytz import timezone

    >>> pacific_tz = timezone('America/Los_Angeles')
    >>> dtstart =datetime(2014, 10, 27, 9, 0)
    >>> rr = rrule.rrule(rrule.WEEKLY, count=2, byweekday=rrule.MO)
    >>> rr_res = [pacific_tz.localize(out_date) for out_date in rr]

    >>> rr_res
    [datetime.datetime(2014, 10, 27, 9, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PDT-1 day, 17:00:00 DST>),
     datetime.datetime(2014, 11, 3, 9, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PST-1 day, 16:00:00 STD>)]
```

Hope that helps!

(P.S. Surely you mean dateutil 2.4.2)

**Comment by DavidMuller** [comment]
Ah thanks for your careful response @pganssle that's very helpful.  Interesting, yeah it seems that pytz [does not do arithmetic on local times correctly unless](http://pytz.sourceforge.net/#localized-times-and-date-arithmetic):

> you use the normalize() method to handle daylight saving time and other timezone transitions: ` after = eastern.normalize(before + timedelta(minutes=20))`

I think I thought this was "a bug" in dateutil because I didn't understand that the underlying implementation uses arithmetic beginning with `dtstart` to generate the new datetimes (as opposed to creating the new datetime instances completely from scratch).

> I suspect that if you want to use the .localize() method, you have to call it on the output of the rrule, not the input, e.g.:

Yes great suggestion, that has been my work around thus far 

> (P.S. Surely you mean dateutil 2.4.2)

Indeed thanks, I've updated the original comment accordingly

**Comment by pganssle** [comment]
@DavidMuller Glad I could help, though I will clarify that as far as I know, `rrule` does not actually currently use date arithmetic, just that the effect is the same, because the original `tzinfo` object attached to `dtstart` is simply copied to each new object.

The real problem is that the timezone localization that `pytz` calculates and attaches via the `localize` method is calculated only at the beginning and nothing is triggering its recalculation (as compared with the `tzfile`, which calculates the timezone upon request rather than on creation of the date).

**Comment by DavidMuller** [comment]
> The real problem is that the timezone localization that pytz calculates and attaches via the localize method is calculated only at the beginning and nothing is triggering its recalculation (as compared with the tzfile, which calculates the timezone upon request rather than on creation of the date).

Thanks for the clarification, that makes a lot of sense.  

For what it's worth, btw, I've found dateutil super easy to use, and really powerful.  Unfortunately, django [relies pretty heavily on pytz](https://docs.djangoproject.com/en/1.7/topics/i18n/timezones/) -- so these sorts of behaviors/quirks are probably on me for trying to play mix and match with pytz, dateutil and [icalendar](https://github.com/collective/icalendar) :laughing:
