### ISSUE TITLE
Unable to build msi

### ISSUE THREAD

**Issue by cancan101** [dateutil/dateutil#73]
Using `python setup.py bdist_msi`:
```
...
running install_scripts
creating dist
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    test_suite="dateutil.test.test"
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\bdist_msi.py", line 247, in run
    sversion, author)
  File "C:\Python27\lib\msilib\__init__.py", line 148, in init_database
    si.SetProperty(PID_SUBJECT, ProductName)
TypeError: unsupported type
```

**Comment by pganssle** [comment]
Works fine for me on dateutil 2.4.0, 2.4.1 and 2.4.2, Python 2.7.9, Windows8, amd64. Can you provide any more details about the failing conditions?

**Comment by cancan101** [comment]
I am using the tar ball from https://pypi.python.org/pypi/python-dateutil

**Comment by pganssle** [comment]
@cancan101 OK, I'll see about trying with a 32-bit version. In the meantime, does [version 2.4.0](https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.0.tar.gz) and [version 2.4.1](https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.1.tar.bz2) have the same problem for you as well?

**Comment by pganssle** [comment]
@cancan101 I installed Python 2.7.9 32-bit version and could not replicate the bug. Is it possible that the bug is in `setuptools`? I'm using the latest version, [14.3.1](https://pypi.python.org/pypi/setuptools/14.3.1)

**Comment by cancan101** [comment]
Okay that was it. Apparently the version of setuptools installed with python-2.7.9 installer was v7.
