### ISSUE TITLE
Add readme_renderer check to docs test

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#734]
Right now we don't do any automated testing that the README will be rendered correctly on PyPI. PyPI's long description renderer is very finicky and if there are any mistakes, it will fail to render *at all* and just be a bunch of ugly markup.

I think we can test this in the test suite by adding a [`readme_renderer`](https://pypi.org/project/readme_renderer/) check to the `docs` build for `tox`. So add `readme_renderer` to the `deps` for [`testenv:docs`](https://github.com/dateutil/dateutil/blob/master/tox.ini#L53), and then add to the commands `python setup.py -r -s`.

To test that it works, deliberately break the README in some way and make sure that `tox -e docs` fails.

**Comment by alimcmaster1** [comment]
Hey thanks for the clear description,

Do we want to add "tox -e docs" to the travis and appveyor yml files, or do we not want this to run as part of CI?
