### ISSUE TITLE
Add 'sys.prefix/share/zoneinfo' to the beginning of tz/tz.TZPATH

### ISSUE THREAD

**Issue by ericvw** [dateutil/dateutil#756]
To support non-system prefix installation tree of software (e.g., `$HOME/.local`), it would be great if the search for the `zoneinfo` directory to be consulted first by the prefix where `sys.executable` first, followed by the remaining system default locations.

I don't see any tests related to the `TZPATH`.  Any recommendations for providing one?  Or are you comfortable with a patch to update the `TZPATH` list?

**Comment by pganssle** [comment]
This is related to #613, which makes some build-time modifications to the TZPATH. I am also interested in exposing `TZPATH` more directly to users (a la `sys.path`), but I am not entirely sure what the interface for that should be.

I think I'm OK with something like:

```python
TZPATH = [...]
if sys.prefix:
    TZPATH = [os.path.join(sys.prefix, path_entry) for path_entry in TZPATH] + TZPATH
```

But I'd like some sort of reading material for how standard this is (which can be inserted as a comment to explain WTF we are doing here).

**Comment by ericvw** [comment]
How about:

```python
diff --git a/dateutil/tz/tz.py b/dateutil/tz/tz.py
index f10c1aa..1fc3639 100644
--- a/dateutil/tz/tz.py
+++ b/dateutil/tz/tz.py
@@ -1443,7 +1443,8 @@ class tzical(object):

 if sys.platform != "win32":
     TZFILES = ["/etc/localtime", "localtime"]
-    TZPATHS = ["/usr/share/zoneinfo",
+    TZPATHS = ["%s/share/zoneinfo" % sys.prefix,
+               "/usr/share/zoneinfo",
                "/usr/lib/zoneinfo",
                "/usr/share/lib/zoneinfo",
                "/etc/zoneinfo"]
```

?

**Comment by pganssle** [comment]
I don't understand that well enough to really comment as to why and who uses that. If this is almost entirely something that is done by people who repackage or are likely to repackage `dateutil` (such as Linux distros or corporate systems), then I'd rather solve it with #613 rather than inject an additional path that may or may not be the right thing to do.

Also, `sys.prefix` for my system is showing up as `~/.pyenv/versions/3.6.5` which is way wrong.

**Comment by ericvw** [comment]
Injecting `sys.prefix` probably makes more sense because at build time since you want to bake-in the installation prefix where the interpreter is installed.

In the compilation world of autotools, `./configure --prefix` is how this is done (see https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Default-Prefix.html).

**Comment by ericvw** [comment]
The more I think on this, I don't feel like it is necessary; primarily because there should be a canonical location for the timezone database that is used for the machine.
