### ISSUE TITLE
Lazy-load dateutil submodules?

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#771]
It is a fairly common problem (see, e.g. issue #770) that people assume that `import dateutil` will automatically import all of `dateutil`'s sub-modules. Currently we don't do this because we want to be as lazy as possible about imports.

We'll need to profile it, but I think there is a "best of both worlds" option here, where in `dateutil.__init__` we define lazy-loaded modules, so that the first time  you invoke, e.g. `dateutil.tz` `dateutil.tz` will be imported in the background, and subsequent queries come from a cache.

For Python 3.7+, I think the best / fastest way to do this is to use module-level `__getattr__` and `__dir__` implementations, but for pre-Python 3.7, we may need to do something fancy and module `sys.modules` or something to implement the equivalent to a module-level `__getattr__`.

**Comment by kirit93** [comment]
@pganssle have you considered using [lazy_import](https://github.com/mnmelo/lazy_import) for this? 
I added 
```import lazy_import
tz  = lazy_import.lazy_module("dateutil.tz")``` to __init__.py and I was able to do this
```
>>> import dateutil
>>> tz = dateutil.tz
>>> tz.gettz()
tzfile('/etc/localtime')
>>> 
```

```lazy_import``` is compatible with Python ≥ 2.7 or ≥ 3.4.

**Comment by pganssle** [comment]
I'm not willing to add any new dependencies. It shouldn't be too difficult to implement, though.

**Comment by pganssle** [comment]
Looks like lazy_import is GPL, so it's also an incompatible license.  Our implementation should be a "clean room" implementation not based on theirs.

**Comment by mariocj89** [comment]
Done via https://github.com/dateutil/dateutil/pull/1007
