### ISSUE TITLE
Add installation documentation prominently

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#778]
As brought up in the PyLondinium sprint, the README / documentation does not prominently explain how to install `dateutil`. This is particularly important because the PyPI package is actually called `python-dateutil`, which is in violation of the standard convention!

I think we should put "installation" instructions above "Download" in [README.rst](https://github.com/dateutil/dateutil/blob/master/README.rst). Something like:

> # Installation
> `dateutil` can be installed from PyPI using `pip` (note that the package name is
> different from the importable name):
> ```bash
> pip install python-dateutil
> ```

**Comment by Satyabrat35** [comment]
Is this issue still open?
I would like to work on it.

**Comment by pganssle** [comment]
Closed by #783.
