### ISSUE TITLE
Accept more than 6 digits for fractional seconds in isoparse

### ISSUE THREAD

**Issue by jayschwa** [dateutil/dateutil#786]
Currently, `isoparse` raises an exception if there are more than 6 digits in the fractional second.

```
>>> dateutil.parser.isoparse("2006-01-02T15:04:05.9999999-07:00")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jay/.local/lib/python2.7/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
  File "/home/jay/.local/lib/python2.7/site-packages/dateutil/parser/isoparser.py", line 136, in isoparse
    components += self._parse_isotime(dt_str[pos + 1:])
  File "/home/jay/.local/lib/python2.7/site-packages/dateutil/parser/isoparser.py", line 363, in _parse_isotime
    raise ValueError('Unused components in ISO string')
ValueError: Unused components in ISO string
```

Go, for example, includes up to 9 digits (nanosecond precision) when marshaling a time into JSON. It would be nice if `isoparse` could accept those without issue, even if precision gets truncated a bit.

**Comment by jbrockmendel** [comment]
This would be nice, though I'm a bit wary of the truncating idea.  Until it gets implemented here (PRs welcome BTW), you might want to just use `pandas.Timestamp` since it retains nanoseconds.

**Comment by jayschwa** [comment]
I am willing to take a shot at implementing it. I propose that `isoparse` truncate by default, with an optional argument to raise some kind of `PrecisionError` instead. Truncation would not be unprecedented since `dateutil.parser.parse` already does so on the same input that fails with `isoparse`.

**Comment by pganssle** [comment]
I agree with this. The ISO 8601 spec does not specify the precision of fractional components (this is left to "mutual agreement"). My design principle is that we will be liberal about anything not explicitly forbidden by the spec.

I don't think there's any way to do better than truncation while still returning standard datetimes.

Let's start with expanding the tests to cover up to 12 digits (should be very easy) and the corresponding fixes that makes the tests pass. We'll consider the UI of how to specify the precision later.
