### ISSUE TITLE
seem to get a incorrect result when do a subtraction

### ISSUE THREAD

**Issue by jirawat07** [dateutil/dateutil#789]
Hi,
I do a subtraction and get an incorrect result searching google found nothing. please see detail below. 
code is
print parser.parse('22/08/2018 07:00:50',dayfirst=True)-parser.parse('22/08/2018 06:00',dayfirst=True)
print parser.parse('22/08/2018 06:00',dayfirst=True)-parser.parse('22/08/2018 07:00:59',dayfirst=True)
result is 
1:00:50
-1 day, 22:59:01
expected 
1:00:50
-1:00:59
is this correct or my code is incorrect

**Comment by bspeice** [comment]
Don't think this has anything to do with `dateutil` specifically, that's a question for how Python formats `timedelta` objects. Specifically, you can replicate the second scenario as follows:

```python
from datetime import datetime, timedelta

print datetime(2018, 8, 22, 6) - datetime(2018, 8, 22, 7, 0, 59)
print timedelta(seconds=-3659)
```

They both print `-1 day, 22:59:01`

**Comment by pganssle** [comment]
@bspeice Is correct. `dateutil.parser` produces a `datetime.datetime` and is doing so correctly in this case.

The issue you are seeing is that the formatting of negative `timedelta` objects is horribly confusing.
