### ISSUE TITLE
isoparser doesn't parse time: '09:55:00.22'

### ISSUE THREAD

**Issue by alexbodn** [dateutil/dateutil#793]
hello friends,

thanks a lot for dateutil parsers.
however, i found an issue:
isoparser doesn't parse time: '09:55:00.22'.
hope that would help with improving dateutil.

best regards,
alex

**Comment by pganssle** [comment]
If you want a `datetime.time`, you can use `dateutil.parser.isoparser().parse_isotime`, but `isoparse` is intended for parsing `datetime`, where (for the most part), components can only be truncated off, so a bare time would not be considered a valid ISO8601 datetime.

`dateutil.parser.parse` will work, though, as will `datetime.strptime(dtstr, "%H:%M:%S.f")`.
