### ISSUE TITLE
parser can't handle %d%b%Y format

### ISSUE THREAD

**Issue by DiegoF90** [dateutil/dateutil#797]
Hello, maybe there is no intention to support this format., but I am getting the following:

```
>>> dp.parse('02Apr2019',fuzzy=True).strftime('%d%b%Y')
'10Aug2019'
```

Thanks,
D

datetutil 2.6.0
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

**Comment by jbrockmendel** [comment]
This is fixed in 2.7.  Closing.
