### ISSUE TITLE
COMPAT: dateutil 2.2/2.3 on linux 3.17

### ISSUE THREAD

**Issue by jreback** [dateutil/dateutil#8]
as mentioned in several issues for pandas.
seems that a very recent release of linux kernel has broken dateutil both 2.2. and 2.3

these are showing up in various tests in pandas. essentially the tz files cannot be found.
I don't think this is a pandas bug as we tests compat for 2.2/2.3 on all platforms ok, though
using kernel 2.6 on linux (on travis CI)

2.3
https://github.com/pydata/pandas/issues/9059
OS: Linux
OS-release: 3.17-1-amd64

2.2 & 2.3
https://github.com/pydata/pandas/issues/8639
OS: Linux
OS-release: 3.17.4-lh-nvidia

**Comment by ffe4** [comment]
I'm closing this since it is related to `zoneinfo.gettz()` which has been deprecated since version 2.6. Using tz.gettz() seems to have solved the related issues. We should probably also think about removing deprecated functionality for #653
