### ISSUE TITLE
parser.parse does not apply time zone to date if ignoretz is True and tzinfos is given

### ISSUE THREAD

**Issue by pajusmar** [dateutil/dateutil#80]
Quoting the [docs](https://dateutil.readthedocs.org/en/2.4.2/parser.html#dateutil.parser.parse):

> **tzinfos** – A time zone, to be applied to the date, if ignoretz is True. This can be either a subclass of tzinfo, a time zone string or an integer offset.

I hope that i'm not misinterpreting docs, but i would expect `parse` to return aware datetime.

```python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import dateutil

In [2]: dateutil.__version__
Out[2]: '2.4.2'

In [3]: from dateutil.parser import parse

In [4]: parse("Sat Oct 11 17:13:46 UTC 2003", ignoretz=True, tzinfos='Europe/Tallinn')
Out[4]: datetime.datetime(2003, 10, 11, 17, 13, 46)
```

Instead it returns naive datetime.

**Comment by pganssle** [comment]
Sorry for the delay in responding to this. I'm looking into it, but as a warning, I think that I inferred what `tzinfos` was supposed to be from context when I was expanding `parser`'s documentation, so it may well be that the documentation is inaccurate and `tzinfos` is intended to serve a different purpose.

**Comment by pganssle** [comment]
@pajusmar OK, so I think that the documentation is indeed very inaccurate. For one thing, `ignoretz=True` simply requests a naive object, so `ignoretz` should be False if you want something with a timezone.

The purpose of `tzinfos` seems to be to provide a mapping from timezone strings to specific timezone objects, e.g.:

```python
    >>> from dateutil import tz
    >>> from dateutil import parser

    >>> tzinfos = {'FET': tz.gettz('Europe/Minsk')}

    >>>parser.parse("Saturday October 21, 1975 17:21:00 FET", tzinfos=tzinfos)
    datetime.datetime(1975, 10, 21, 17, 21, tzinfo=tzfile('Europe/Minsk'))
```

It seems like what you want to do is to ignore the timezone and select the specified time in the Europe/Tallinn timezone instead. The best way to do this is probably to set `ignoretz` to `True`, and then add the timezone information to the naive object, like so:

``` python
    from dateutil.parser import parse
    from dateutil.tz import gettz

    naive_dt = parse("Sat Oct 11 17:13:46 UTC 2003", ignoretz=True)
    dt = naive_dt.replace(tzinfo=gettz('Europe/Tallinn'))
```

I'll make sure to get that documentation updated.

**Comment by pajusmar** [comment]
Thank you for the clarification.
