### ISSUE TITLE
utcoffset/tzname incorrect immediately before Samoan offset change

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#812]
First reported by @MartinThoma in [this SO question](https://stackoverflow.com/questions/52136980), it seems that there is a bug in the way `tzfile` handles the local transition times during a base offset change:

```python
from datetime import datetime, timedelta
from dateutil import tz

APIA = tz.gettz('Pacific/Apia')
dt0 = datetime.fromisoformat('2011-12-29T20:00-10:00')

for i in range(5):
    dt = (dt0 + timedelta(hours=i))
    dt = dt.astimezone(APIA)
    print(f'{dt.isoformat()}')

## Result:
# 2011-12-29T20:00:00-10:00
# 2011-12-29T21:00:00-10:00
# 2011-12-29T22:00:00-10:00
# 2011-12-29T23:00:00+14:00
# 2011-12-31T00:00:00+14:00
```

Note that while `fromutc` sets the local datetime correctly, `utcoffset` returns `+14:00` an hour early! This is because the assumption in the code is that these base offset shifts don't happen during DST, which leads to the "local" (but not the UTC) transition time being off by 1 DST offset.

PR #810 should fix this.

**Comment by MartinThoma** [comment]
Thank you for mentioning me :-) It's awesome to see that this indirectly reported bug is not only seen, but also almost immediately fixed!
