### ISSUE TITLE
How to prefer British date format?

### ISSUE THREAD

**Issue by cyberfox1** [dateutil/dateutil#826]
Say this date:

    7/10/2018 12:51:31

I would prefer this to be British interpretation:

    2018-10-7 12:51:31 (not 2018-7-10)

However, if the only valid choice is American dates, e.g.

    7/17/2018 12:51:31

Then parse as:

    2018-7-17 12:51:31

Is it possible?

**Comment by jbrockmendel** [comment]
```
>>> dateutil.parser.parse('7/10/2018 12:51:31', dayfirst=True)
datetime.datetime(2018, 10, 7, 12, 51, 31)
```

**Comment by pganssle** [comment]
@cyberfox1 I think @jbrockmendel solved your issue, so I'm going to close this.
