### ISSUE TITLE
Strange result while parsing 'YYYY-MM'

### ISSUE THREAD

**Issue by cogtepsum** [dateutil/dateutil#834]
Ubuntu 18.04
python3.6
dateutil 2.7.5

Trying to parse 'YYYY-MM' string
```(python)
>>> from dateutil.parser import parse
>>> parse('2018-10')
datetime.datetime(2018, 10, 6, 0, 0)
```
for some reason produces 6th date. I was expecting `datetime.datetime(2018, 10, 1, 0, 0)`

**Comment by jbrockmendel** [comment]
For missing pieces of the date it defaults to using that piece of today's date.  Try passing `default=datetime(1997, 4, 3)`:

```
>>> parse('2018-10')
datetime.datetime(2018, 10, 6, 0, 0)
>>> parse('2018-10', default=datetime(1997,4,3))
datetime.datetime(2018, 10, 3, 0, 0)
```

**Comment by cogtepsum** [comment]
So the problem was with what I was expecting. I guess it's fixed then =) Thanks!
