### ISSUE TITLE
All dates in the past

### ISSUE THREAD

**Issue by glepore70** [dateutil/dateutil#84]
I am parsing data from the Vietnam war era and earlier. These dates are look like this: "11/08/64". Unfortunately, since that date is more than 50 years in the past, dateutil defaults to calling that date 2064-11-08 00:00:00. Is there any way to specify that all dates are in the past? 

Thanks.

**Comment by pganssle** [comment]
@glepore70 I think that the most "official" way to accomplish what you want to accomplish is to subclass `dateutil.parser.ParserInfo`

```python

    from dateutil import parser


    class VietnamParserInfo(parser.parserinfo):
        def convertyear(self, year):
            if year < 100:
                year += 1900        # All dates are in the 20th century

            return year


    if __name__ == "__main__":
        pinfo = VietnamParserInfo()

        d1 = parser.parse("11/08/64", parserinfo=pinfo)

        print(d1)
```

In the unstable version, I've made some changes to how default dates are specified, including a `dates_in_future` toggle. Before closing this issue, I'm going to look into incorporating that argument into the year conversion as well.

**Comment by glepore70** [comment]
My quick and dirty hack was to edit parser.py line 278:
            if abs(year-self._year) >= 50:
to
            if abs(year-self._year) >= 5:

which seemed to work. I implemented your version and it also works, thanks!
