### ISSUE TITLE
Why rrulestr and rrule.__str__ omit RRULE paramter?

### ISSUE THREAD

**Issue by AndrewPashkin** [dateutil/dateutil#86]
`str(rrule.rrulestr('DTSTART:19970105T083000\nRRULE:FREQ=YEARLY;INTERVAL=2;BYMONTH=1;BYDAY=SU;BYHOUR=8,9;BYMINUTE=30'))`
Gives:
`'DTSTART:19970105T083000\nFREQ=YEARLY;INTERVAL=2;BYMONTH=1;BYDAY=SU;BYHOUR=8,9;BYMINUTE=30'`

`str(rrule.rrule(freq=rrule.DAILY, dtstart=dt.datetime.now(), byweekday=rrule.MO(10), count=10))`
Gives:
`'DTSTART:20150526T004628\nFREQ=DAILY;COUNT=10;BYDAY=MO'`

Notice, that `RRULE` token is omitted everywhere.

Why? Is it in iCalendar RFC?

**Comment by pganssle** [comment]
@jarondl Is [this branch](https://github.com/dateutil/dateutil/commit/1e95518f419067ee835d6931ba29afdb23eff595) ready for a PR or merge? I've got this issue assigned to milestone 2.5.0, and I'm thinking it's about time to prep a release.

**Comment by pganssle** [comment]
Pushing this to 2.5.1, because I'm not 100% sure this is necessary.
