### ISSUE TITLE
tz produces strange timezone for datetime.isoformat() 

### ISSUE THREAD

**Issue by cliffxuan** [dateutil/dateutil#866]
When calling datetime.isoformat(), the timezone part of the string has seconds like this: 1840-06-03 23:20:33-04:06:04

Version: 2.8.0

Python Version: 3.6.2, 3.7.1

Code to reproduce behaviour:
```
import datetime as dt
from dateutil.parser import parse
from dateutil.tz import gettz


timestamp = dt.datetime(
    1840, 6, 3, 23, 20, 33, tzinfo=gettz('America/Montserrat')
)
print(timestamp)
parse(timestamp.isoformat())
```

Output:
```
1840-06-03 23:20:33-04:06:04
Traceback (most recent call last):
  File "tzone.py", line 15, in <module>
    parse(timestamp.isoformat())
  File "/root/.virtualenvs/mew-_av6uA16/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/root/.virtualenvs/mew-_av6uA16/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', '1840-06-03T23:20:33-04:06:04')
```

In Version 2.7.5, this is the output:
```
1840-06-03 23:20:33-04:06
```

**Comment by pganssle** [comment]
If you can use Python 3.7, I recommend using `datetime.fromisoformat` to parse the results of `isoformat`. `isoformat` does not always produce a string that is compliant with ISO 8601, and `dateutil.parser.parse` *generally* can only handle so many "edge cases" before the codepaths start to cause parsing failures in the common case.

In this case, the main problem is that time zones were not standardized in the 19th century, so you have all kinds of funky stuff like fractional seconds in your time zone offsets. Exactly how useful the "America/Montserrat" time zone is in 1840 is unclear.

My recommendations for you:

1. When using `datetime.isoformat()` to serialize your datetimes, use `datetime.fromisoformat()` (added in Python 3.7) to deserialize them. The function is guaranteed to invert `datetime.isoformat`, while neither `dateutil.parser.parse` nor `dateutil.parser.isoparse` are guaranteed to handle the edge case of seconds and fractional seconds in a time zone offset. See #572 for more information on whether `isoparse` will support this.
2. For `datetime`s prior to ~1970 (or possibly *all* `datetime`s in the past), you may be best off converting to UTC before serializing them. It really depends what kind of guarantees you want to keep about these things and you definitely don't want to do that for future time stamps, but if all you care about is the actual time that the event occurred and not the civil time, storing in UTC is a good idea. See [my talk from PyLondinium](https://www.youtube.com/watch?v=TPrmyAZZPi0) on this topic for more detailed information.

**Comment by cliffxuan** [comment]
@pganssle thanks for the reply!

So this is a new behaviour in the latest release of `python-dateutil==2.8.0`. It works ok with `2.7.5`. Is there any change that may have caused this and need to be aware of?

> If you can use Python 3.7, I recommend using `datetime.fromisoformat` to parse the results of `isoformat`.

Yes, I'm indeed using `fromisoformat` for Python3.7. https://github.com/cliffxuan/mew/blob/master/mew/serializer.py#L130 `dateutil.parser.parse` is the best alternative for Python3.6 I've found so far.

> Exactly how useful the "America/Montserrat" time zone is in 1840 is unclear.

Probably not very useful :) It was generated by my unit test using hypothesis https://github.com/cliffxuan/mew/blob/master/tests/test_serializable.py#L115

> See [my talk from PyLondinium](https://www.youtube.com/watch?v=TPrmyAZZPi0) on this topic for more detailed information.

Just watched. Really nice talk. Wish I could have joined as I actually live in London :)

**Comment by pganssle** [comment]
> So this is a new behaviour in the latest release of `python-dateutil==2.8.0`. It works ok with `2.7.5`. Is there any change that may have caused this and need to be aware of?

The main difference here is probably #763, which adds support for sub-minute offsets to time zones. Prior to Python 3.6, sub-minute time zone offsets were not supported at the language level, and version 2.8.0 adds support for that. (Interestingly, this was added at the PyLondinium sprint)

> `dateutil.parser.parse` is the best alternative for Python3.6 I've found so far.

I think `dateutil.parser.isoparse` may be a better "backport" of `fromisoformat`, given that I based `fromisoformat` on `isoparse`, though as mentioned above, `isoparse` doesn't support sub-minute offsets.

> It was generated by my unit test using hypothesis

You may want to add an assumption into your test if you don't care about supporting sub-minute offsets:

```python
assume(dt.utcoffset().total_seconds() % 60 == 0)
```

Alternatively, you can craft a strategy that forbids datetimes prior to 1915 or so, but you may still hit into pre-1970 `Africa/Monrovia`. Presumably you can also turn that assumption off for Python == 3.6 (the only version of Python for which this will be an issue - all other versions will either truncate or have a `fromisoformat` constructor).

> Just watched. Really nice talk. Wish I could have joined as I actually live in London :)

Keep your eyes peeled, my understanding is that this will be an annual event. It's quite cheap and all the money goes to the PSF.

**Comment by cliffxuan** [comment]
Thanks. I'm happy to close this issue.
