### ISSUE TITLE
Move all simple constants from setup.py into setup.cfg

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#871]
Nearly all the options in [our `setup.py`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) can be moved over to `setup.cfg`.

The only things that need to stay are:

1. `use_scm_version` (I believe there is no declarative option for this)
2. The README configuration, which involves modifying the README
3. `cmdclass`, which I think has no declarative alternative

The trickiest part will be converting the `find_packages` option over, but that is covered in the setuptools documentation I linked to, you specify it as `packages = find:`, and then pass the options in `[options.packages.find]`.

For bonus points, we may be able to switch over the `README` thing by switching `README` over to using `.. code-block :: python3` directly, and then doing a search-and-replace as part of the [docs build](https://github.com/dateutil/dateutil/blob/master/docs/conf.py) instead. This will be a bit tricky, though, because `README.rst` is included in the docs with an RST include, which means we would have to create a temporary file that would be included. For now, this ticket can be closed if we do everything *except* that.

**Comment by aquinlan82** [comment]
We are currently working on this issue.
