### ISSUE TITLE
Add documentation preview

### ISSUE THREAD

**Issue by pganssle** [dateutil/dateutil#873]
Right now it's kind of a pain to review documentation PRs, since it requires pulling the PR branch and building the documentation locally. In setuptools we [we set up netlify](https://github.com/pypa/setuptools/pull/1367) and it went swimmingly, but it requested a lot more permissions than I was super comfortable with at the time.

@vtbassmatt Has a demo project that isn't totally smooth but involves publishing to an Azure static site that you can find [here](https://github.com/vtbassmatt/static-site-test). Maybe we can do a first pass look at using that and see how hard that would be, otherwise we can go with the netlify approach.

**Comment by ffe4** [comment]
There is actually a [PR documentation autobuild](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html) feature in beta for readthedocs. You can see it live in any PR on the [readthedocs repo](https://github.com/readthedocs/readthedocs.org/pulls). Could we just use that?

**Comment by pganssle** [comment]
Nice! That feature was definitely not available when I opened this issue, but it looks like exactly what I've always wanted. Sometimes it pays to procrastinate I guess.

I can send an e-mail to the RTD project in the next few days.

**Comment by ffe4** [comment]
Yes looks great, doesn't it :)  It was apparently a GSOC project last year. Looking forward to seeing it live!

**Comment by pganssle** [comment]
We're enabled for this and it looks great! Closing!
