### ISSUE TITLE
Problems with rrule and Daylightsavingtime 

### ISSUE THREAD

**Issue by Estartu** [dateutil/dateutil#88]
I'm dealing with some ical problems. 

I have an ical event. 

    BEGIN:VEVENT
    UID:Event/termine/gps/akt@portal.augusta.de 
    DTSTART;TZID=CET:20150529T190000
    DTEND;TZID=CET:20150529T220000
    CATEGORIES:Arbeitsgruppe
    DTSTAMP:20110620T075538Z
    EXDATE;TZID=CET:20151225T190000
    LAST-MODIFIED:20150424T201707Z
    LOCATION:Vereinsräume des Augsburger Computer Forum e.V.
    PRIORITY:5
    RRULE:FREQ=MONTHLY;BYDAY=-1FR
    SUMMARY:GPS-Arbeitsgruppe
    URL:https://www.augusta.de/termine/gps
    END:VEVENT

As you can see there is an RRule repeating this event every last friday of the month. 

I parsed this ical with icalendar. 

I'm using:

    start = iobj.get( 'DTSTART' ).dt
    rrset = rruleset()
    rrule = iobj.get( 'RRULE' )
    exdate = iobj.get( 'EXDATE' )
    rrset.rrule( rrule.rrulestr( rule.to_ical(), dtstart = start ) )
    for edate in exdate.dts : 
        rrset.exdate( edate.dt )

Everything so far works just fine. 

When I Try to get the next say 10 dates with:

    list(rrset)[:10] 

I get:

    [datetime.datetime(2015, 5, 29, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 6, 26, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 7, 31, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 8, 28, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 9, 25, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 10, 30, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 11, 27, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2015, 12, 25, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2016, 1, 29, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>),
     datetime.datetime(2016, 2, 26, 19, 0, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>)]

Which seems okay on the first glance, but on deeper inspection there is a problem starting with October 30th, daylight saving time ends October 25th but tzinfo info of the datetime object is still "DstTzInfo 'CET' CEST+2:00:00 DST"

The second problem is that the 25th of December is in this list instead of being skipped a specified in the EXDATE. The Problem seams to be tat while parsing the exdate rule daylight saving time is calculated correctly and therefore the exdate 19:00:00+01:00 didn't match the calculated repeat time of 19:00:00+02:00. 

Am I doing something wrong there? 

Converting everything to UTC and processing there doesn't help because 17:00:00 UTC don't match 18:00:00 UTC either.

**Comment by pganssle** [comment]
@Estartu Sorry for the long delay in response. See #102 for another manifestation of this same issue. I give a workaround in that case. This may be a different issue. I'm not super familiar with iCal, but the easiest thing to do is probably to try to get it to give you a tzinfo generated by dateutil (`tzlocal()`, `tzfile()`, etc) rather than a pytz object - if, e.g. `tzfile()` is used, you'll see the correct behavior.

Otherwise, you may want to manipulate "start" such that it is a timezone-naive object, e.g. ```start_naive = start.replace(tzinfo=None)```, then apply the time-zone back to the object afterwards, e.g.:

```python
the_tz = start.tzinfo
start_naive = start.replace(tzinfo=None)
rrset = rruleset()
rrule = iobj.get( 'RRULE' )
exdate = iobj.get( 'EXDATE' )
rrset.rrule( rrule.rrulestr( rule.to_ical(), dtstart = start_naive ) )
for edate in exdate.dts : 
    rrset.exdate( edate.dt )

new_rrset_list = [the_tz.localize(cdt) for cdt in rrset]
```

As with #102, I'll look into this more later and see if it's reasonable to make a change on our end or if that's functionality that is better reserved for pytz.

**Comment by pganssle** [comment]
OK, so this is a fundamental limitation of `pytz`-style time zones, so if you want to use that type of time zone, you'll have to strip off the time zone and re-localize at the end.
