### ISSUE TITLE
Issue importing _thread in rrule.py

### ISSUE THREAD

**Issue by cgrin** [dateutil/dateutil#9]
The following code on line 14 of rrule.py

``` python
from six.moves import _thread 
```

Is resulting in an import error on OS X Yosemite in Python 2.7.6. Reverting to 

``` python
import thread as _thread
```

results in a working dateutil.

**Comment by WangWenchao** [comment]
I meet this today ,how to resolve?

**Comment by jarondl** [comment]
@WangWenchao , can you try to run this command and tell us the output?

    python -c 'import six; print(six.__version__)'
