### ISSUE TITLE
How to uninstall/upgrade old, distutils-installed python-dateutil

### ISSUE THREAD

**Issue by MarkusPiotrowski** [dateutil/dateutil#906]
My system: Python 2.7.14, OS: Windows 7, 64 bit

I have an old installation of ```python-dateutil``` (1.5) and trying to update or uninstall with ```pip``` always gives the same message:

> Cannot uninstall 'python-dateutil'. It is a distutils installed project and thus
>  we cannot accurately determine which files belong to it which would lead to onl
> y a partial uninstall.

Can you assist me how to make a complete un-install of the old ```python-dateutil```? Is just deleting the respective foder in my ```site-packages``` folder enough or are there other files, logs etc. that need to be manipulated?

I'd love to see something about this in the docs.

**Comment by pganssle** [comment]
This is not really related to the `dateutil` project, it is presumably some sort of bad state that your system has gotten into. Presumably someone installed `python-dateutil` with `easy_install` ages ago. It's not specific to `dateutil`, presumably anything installed that way would be broken.

**Comment by MarkusPiotrowski** [comment]
What you call 'ages ago' is actually a few years. I installed `python-dateutil` at that time in the recommended way. Now I needed it to update and run into trouble. I mean, it's your software that I wanted to update and I did nothing 'wrong'.  At one point in time you switched from `easy_install` to `pip`, but you can't give instructions how to update?

Or do you mean that an update from version 1.5 should usually work without problems and it's just my particular system?

The recommendation to make a complete new setup of my Python environment isn't particular helpful.
Actually I fixed it, just by manually deleting the dateutil folder and (if I remember correctly) an egg file.
