### ISSUE TITLE
gettz on Python 3 fails with TypeError when passed bytes

### ISSUE THREAD

**Issue by labrys** [dateutil/dateutil#927]
Given the following code on Python 3.7:
```python
import dateutil.tz
dateutil.tz.gettz(b'America/New_York')
```
A `TypeError` is raised:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.7/site-packages/dateutil/tz/tz.py", line 1551, in __call__
    rv = self.nocache(name=name)
  File "lib/python3.7/site-packages/dateutil/tz/tz.py", line 1612, in nocache
    if name.startswith(":"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by labrys** [comment]
To be clear, a `TypeError` being raised for bytes isn't the problem since the docs say "Retrieve a time zone object from a string representation".

The problem is more that the raised error is unhelpful and should consider raising the `TypeError` with a more helpful message such as `TypeError: gettz arg should be str, not bytes`

**Comment by pganssle** [comment]
@labrys Thanks for the report, sorry for the delay in responding. I agree with the proposed solution.

**Comment by labrys** [comment]
@pganssle A try-except-raise should have little to no effect for valid values, but definitely no harm in profiling it :)
