### ISSUE TITLE
pip show gives licence as UNKNOWN

### ISSUE THREAD

**Issue by GadgetSteve** [dateutil/dateutil#929]
I believe that adding a `licence` entry to setup.py/pyproject.toml/equivelent would resolve this - it would remove the step of visiting the repository to check the licence type for those that have to worry about such things.

**Comment by pganssle** [comment]
@GadgetSteve This seems not true:

```
$ pip show python-dateutil
Name: python-dateutil
Version: 2.8.0
Summary: Extensions to the standard Python datetime module
Home-page: https://dateutil.readthedocs.io
Author: Gustavo Niemeyer
Author-email: gustavo@niemeyer.net
License: Dual License
Location: ...
Requires: six
Required-by: 
```

And as mentioned on the `setuptools` tracker, this is not necessarily the right thing to do.
