### ISSUE TITLE
Should dateutil include common TZ abbreviations?

### ISSUE THREAD

**Issue by NicolasLM** [dateutil/dateutil#932]
I am using dateutil to parse dates included in RSS feeds which are mostly RFC 822 dates. These dates often make use of timezone abbreviations like `EDT`, `PST`...

Dateutil does not know these abbreviations so it defaults to returning a naive datetime and warns with a `UnknownTimezoneWarning`.

I know that I can pass a `tzinfos` dict to map these abbreviations to a known timezone, but I'm not sure that application code is the best place to store these mappings.

Should dateutil include common timezone abbreviations?

**Comment by labrys** [comment]
The problem with timezone abbreviations is that they are ambiguous.  For example, do you mean EDT for the US or for Australia.  Now if you know they are all RFC 822 dates and thus limited to only those listed there, you could simply do a string replace before parsing.

**Comment by NicolasLM** [comment]
Makes sense, thank you for pointing that out.

If it can be helpful to anyone, here is what I ended with:

```python
tzinfos = {
    'UT': gettz('GMT'),
    'EST': -18000,
    'EDT': -14400,
    'CST': -21600,
    'CDT': -18000,
    'MST': -25200,
    'MDT': -21600,
    'PST': -28800,
    'PDT': -25200
}
```
