### ISSUE TITLE
request for release

### ISSUE THREAD

**Issue by jozeffrtus** [dateutil/dateutil#937]
I see that last release is version `2.8.0` with data `2018i`. Few days ago `2019b` data have been merged to master. Why is it not released? Is there some rationale behind that?

Pls, is it possible to release new version right after tz data are updated? :pray:

Thanks, Jozef

**Comment by leifwalsh** [comment]
I'm also interested in a dateutil release with the 2019b database. Could we get a release date estimate, and is there anything I can help with to accelerate it?

**Comment by leifwalsh** [comment]
(#701 would also be great, of course, but is going to take more time to roll out safely)

**Comment by pganssle** [comment]
Yeah, I'm waaaaay behind on all my projects. Right now the biggest release blocker is that the CI configuration is broken because something on Travis has changed. I think if someone wants to pick up the work I started in #945 that would make it easier to cut a release next week some time.

And yeah, #701 is the ideal situation, that is one of my highest priorities for this module.

**Comment by hugovk** [comment]
To fix the 3 Travis CI failures:

* PR https://github.com/dateutil/dateutil/pull/945 for PyPy3
* PR https://github.com/dateutil/dateutil/pull/951 for PyPy2
* PR https://github.com/dateutil/dateutil/pull/953 for Python 3.3

**Comment by aexvir** [comment]
@pganssle Seeing that the travis PRs were closed/merged, is there anything blocking a new release?

We also had to manually release our own version of this package just because we need the updated `tzdata`

**Comment by hugovk** [comment]
Dateutil 2.8.1 has just been released! 

https://github.com/dateutil/dateutil/releases/tag/2.8.1

**Comment by pganssle** [comment]
Sorry for the delay everyone. I have cut a new release. I will try to cut new releases as soon as tzdata comes out, at least until #701 is fixed.

**Comment by pganssle** [comment]
Thanks @hugovk for making the release possible and for pointing out that this bug can be closed.

**Comment by hugovk** [comment]
You're very welcome, and thank you for dateutil!
