### ISSUE TITLE
relativedelta - incorrect result

### ISSUE THREAD

**Issue by alexterner** [dateutil/dateutil#946]
from datetime import datetime
from dateutil.relativedelta import relativedelta

print(datetime(2015, 12, 1) + relativedelta(month=+1))
2015-01-01 00:00:00

Actual output: 
datetime.datetime(2015, 1, 1, 0, 0)
Expected to be in 2016

**Comment by jbrockmendel** [comment]
That's the expected result; what you want is `months=1`, not `month=1`

**Comment by alexterner** [comment]
Thanks, it looks much better now
print(datetime(2015, 12, 1) + relativedelta(months=+1))
2016-01-01 00:00:00****
