### ISSUE TITLE
python-dateutil not support pipenv

### ISSUE THREAD

**Issue by luotasha** [dateutil/dateutil#957]
when i execute:

pipenv install python-dateutil

it’s failed by no match version found, and finnally i found it’s caused by https://pypi.org/simple/ have no entrance for
Python-dateutil. Can you feel to free to look this problem

pipenv is more flexable than pip so i think this excellent package should support pipenv

**Comment by pganssle** [comment]
`pipenv` is not really something we support or don't support here, we produce standard packages and upload them to PyPI. If anything this is a bug in `pipenv`, but it's not one I can reproduce:

```python
$ pipenv install python-dateutil
Creating a Pipfile for this project…
Installing python-dateutil…
Adding python-dateutil to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (e5c120)!
Installing dependencies from Pipfile.lock (e5c120)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 —
```

I suspect this is something to do with the directory you are trying to install this in or a pipfile or something, but I don't really know anything about pipenv.

**Comment by luotasha** [comment]
if excute:
pipenv install django-dateutil

here is info:
Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches django-dateutil
No versions found
Was https://pypi.org/simple/ reachable?

i open  https://pypi.org/simple/ and search date-util, surely it's not found. my question is how to add the portal in this link. maybe you can do it when release a new package

**Comment by luotasha** [comment]
i definitely confirm it's caused by missing portal in   https://pypi.org/simple/, but i don't know what's porpose for this link originaly. pipenv is depend on this link

**Comment by GriceTurrble** [comment]
There is no package `django-dateutil` listed because it does not exist. The same is true for `date-util`.

This package is called [`python-dateutil`](https://pypi.org/simple/python-dateutil/). If you try to install anything other than that exact string, you will not find it.

As pipenv simply wraps pip, this is not a question of supporting one package manager or the other.

Please check your local environment first.
