### ISSUE TITLE
In GAE zoneinfo.__init__.py fails when importing from subprocess

### ISSUE THREAD

**Issue by alexxv** [dateutil/dateutil#97]
When running `dateutil` in GAE's sandbox, `zoneinfo.__init__.py` is failing on `from subprocess import check_call`.
`subprocess` module is overriden in GAE's sandbox.
If I move the `import` inside the function that uses it and wrap it with `try ... catch` it solves the problem.
Does this solution makes sense? If so I'll open a PR.

Alex

**Comment by jarondl** [comment]
Hi @alexxv, thanks for the report.
I prefer a different solution: move `rebuild` out of `__init__.py`  and into a file of its own: `zoneinfo/rebuild.py`. That way a simple `import dateutil`  won't import this anymore, but a special `import dateutil.zoneinfo.rebuild`  will work.
It is almost independent anyway, and I have reasons to believe that the only use of this function is within `updatezinfo.py` which we can fix. 

Do you want to submit a PR for that? or should I make the changes?

**Comment by alexxv** [comment]
Hey @jarondl, I've opened a PR with the fix you proposed. I'm not really sure how good the fix is.
I extracted `rebuild` into a separate file, but it has dependencies on globals in `__init__.py`. 
lmk if you think it's good enough.

**Comment by jarondl** [comment]
Hi @alexxv, that's exactly what I had in mind, thank you.
The only problem is in https://github.com/dateutil/dateutil/blob/master/updatezinfo.py#L29   where we should replace `rebuild` with `rebuild.rebuild`. That's also why the tests failed.

**Comment by alexxv** [comment]
Hey @jarondl, I've pushed a fix for the error you mentioned. The build passed.

**Comment by jarondl** [comment]
Thank you @alexxv for providing the solution. Merged
